'use strict';
const byId=id=>document.getElementById(id);
const GEOMETRY_KEY='atlas_sinbad_academy_native_window';
const VOICE_KEY='atlas_sinbad_academy_voice_enabled';
const HISTORY_KEY='atlas_sinbad_academy_messages';
const AVATARS={idle:'./assets/captain-sinbad/captain-sinbad-idle-master.png',teaching:'./assets/captain-sinbad/captain-sinbad-board-teaching.png',speaking:'./assets/captain-sinbad/captain-sinbad-speaking.png',listening:'./assets/captain-sinbad/captain-sinbad-listening.png',thinking:'./assets/captain-sinbad/captain-sinbad-thinking.png'};
const DEFAULT_CLOUD={url:'https://kcvyftrvteqmabvxfebu.supabase.co',key:'sb_publishable_ZBHFlbhQAnhUAOyVg20Szw_nW0QDj_l'};
const academyCharacterEngine=window.SinbadCharacterEngine?.createCharacterEngine({initialState:'idle'})||null;
const academyPerformanceDirector=window.SinbadPerformanceDirector?.createPerformanceDirector()||null;
let voiceEnabled=localStorage.getItem(VOICE_KEY)!=='false',lastNarration='',narrationRun=0,cloudClient=null,cloudSession=null;
let messages=loadMessages(),recognition=null,objectUrls=[];

function renderCharacterSnapshot(snapshot){
  const stage=byId('academyInstructorStage'),image=byId('academySinbadAvatar');if(!stage||!image)return;
  stage.dataset.state=snapshot.state;stage.dataset.gesture=snapshot.gesture;stage.dataset.gaze=snapshot.gaze;stage.dataset.emotion=snapshot.emotion;
  const pose=window.SinbadCharacterRig?.poseForState(snapshot.state),rig=pose?.accepted&&window.SinbadCharacterRig?.cssVariables(pose.controls);
  if(rig?.accepted)Object.entries(rig.variables).forEach(([name,value])=>stage.style.setProperty(name,value));
  image.src=AVATARS[snapshot.state]||AVATARS[snapshot.state==='board-teaching'?'teaching':'idle']||AVATARS.idle;
}
academyCharacterEngine?.subscribe(renderCharacterSnapshot);

function loadMessages(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]').slice(-30)}catch{return[]}}
function saveMessages(){localStorage.setItem(HISTORY_KEY,JSON.stringify(messages.slice(-30)))}
function saveWindowGeometry(){try{localStorage.setItem(GEOMETRY_KEY,JSON.stringify({left:window.screenX,top:window.screenY,width:window.outerWidth,height:window.outerHeight}))}catch{}}
function restoreWindowGeometry(){try{const saved=JSON.parse(localStorage.getItem(GEOMETRY_KEY)||'null');if(!saved)return;const width=Math.max(640,Math.min(Number(saved.width)||1200,screen.availWidth)),height=Math.max(520,Math.min(Number(saved.height)||800,screen.availHeight));window.resizeTo(width,height);window.moveTo(Math.max(screen.availLeft||0,Number(saved.left)||0),Math.max(screen.availTop||0,Number(saved.top)||0))}catch{}}
function setInstructorState(state,status){const safeState=AVATARS[state]?state:'idle';academyPerformanceDirector?.cancel();if(academyCharacterEngine)academyCharacterEngine.setState(safeState);else renderCharacterSnapshot({state:safeState,gesture:'rest',gaze:'audience',emotion:'warm'});if(status)byId('academyInstructorStatus').textContent=status}
function syncVoiceControls(){byId('academyVoiceToggle').textContent=voiceEnabled?'🔊 Voice: On':'🔇 Voice: Off';byId('academyVoiceToggle').setAttribute('aria-pressed',String(voiceEnabled));byId('academyReplayVoice').disabled=!lastNarration}
function stopNarration(status='Voice stopped'){narrationRun+=1;if('speechSynthesis'in window)window.speechSynthesis.cancel();byId('academyStopVoice').disabled=true;setInstructorState('idle',status)}
function selectVoice(){const voices=window.speechSynthesis?.getVoices?.()||[];return voices.find(v=>/^tr([-_]|$)/i.test(v.lang))||voices.find(v=>/^en([-_]|$)/i.test(v.lang))||voices[0]||null}
function narrationChunks(text){return String(text).replace(/\s+/g,' ').match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(x=>x.trim()).filter(Boolean)||[]}
function speak(text,{afterState='teaching',afterStatus='Lesson ready'}={}){lastNarration=String(text||'').trim();syncVoiceControls();if(!lastNarration||!voiceEnabled)return;if(!('speechSynthesis'in window)||!('SpeechSynthesisUtterance'in window)){setInstructorState('teaching','Voice is unavailable in this browser');return}const run=++narrationRun,chunks=narrationChunks(lastNarration),voice=selectVoice();window.speechSynthesis.cancel();byId('academyStopVoice').disabled=false;setInstructorState('speaking','Captain Sinbad is speaking');const play=index=>{if(run!==narrationRun)return;if(index>=chunks.length){byId('academyStopVoice').disabled=true;setInstructorState(afterState,afterStatus);return}const utterance=new SpeechSynthesisUtterance(chunks[index]);utterance.lang=voice?.lang||'tr-TR';utterance.voice=voice;utterance.rate=.94;utterance.pitch=1;utterance.volume=1;utterance.onend=()=>play(index+1);utterance.onerror=event=>{if(event.error!=='canceled'){byId('academyStopVoice').disabled=true;setInstructorState('teaching','Voice playback could not continue')}};window.speechSynthesis.speak(utterance)};play(0)}
function lessonNarration(lesson){return `${lesson.title}. Öğrenme hedeflerimiz: ${lesson.objectives.join('. ')}. Uygulama: ${lesson.practice}. Bu ders eğitim amaçlıdır. Operasyonel kararlar güncel resmî bilgiler ve kaptan onayı gerektirir.`}
function renderLesson(){stopNarration('Preparing lesson');const category=byId('academyModule').value,lesson=window.SinbadAcademy?.lesson(category,window.SINBAD_TRAINING_DATA),output=byId('academyOutput');if(!lesson)return;const progress=JSON.parse(localStorage.getItem('sinbad_academy_progress')||'{}');progress[category]={openedAt:new Date().toISOString(),status:'studying'};localStorage.setItem('sinbad_academy_progress',JSON.stringify(progress));output.textContent=`${lesson.title}\n\nLearning objectives\n${lesson.objectives.map(x=>'• '+x).join('\n')}\n\nPractice\n${lesson.practice}\n\nOfficial offline sources\n${lesson.sources.map((x,i)=>`[S${i+1}] ${x.title} — ${x.authority}`).join('\n')||'No matching offline source.'}\n\n⚠ Training only. Operational decisions require current official information and captain approval.`;setInstructorState('teaching',voiceEnabled?'Lesson opened — narration starting':'Lesson opened');speak(lessonNarration(lesson))}
function renderQuiz(){stopNarration('Preparing question');const category=byId('academyModule').value,items=window.SinbadAcademy?.quiz(category)||[],output=byId('academyOutput');if(!items.length)return;const item=items[Math.floor(Math.random()*items.length)];output.replaceChildren();const title=document.createElement('strong');title.textContent=item.q;output.append(title);const choices=document.createElement('div');choices.className='academy-choices';item.choices.forEach((choice,index)=>{const button=document.createElement('button');button.type='button';button.className='btn';button.textContent=choice;button.addEventListener('click',()=>{stopNarration('Checking answer');setInstructorState('thinking','Checking your answer');[...choices.children].forEach(node=>node.disabled=true);button.classList.add(index===item.answer?'primary':'danger');const result=document.createElement('p');result.textContent=`${index===item.answer?'✓ Correct':'✗ Review'} — ${item.explanation} [${item.source}]`;output.append(result);speak(`${index===item.answer?'Doğru cevap.':'Bu cevabı yeniden inceleyelim.'} ${item.explanation}`,{afterState:'teaching',afterStatus:'Explanation complete'})});choices.append(button)});output.append(choices);const source=document.createElement('small');source.className='academy-source';source.textContent=`Official source: ${item.source}`;output.append(source);speak(`${item.q}. Seçenekler: ${item.choices.join('. ')}`,{afterState:'listening',afterStatus:'Captain Sinbad is listening'})}
function addMessage(role,text,visuals=[]){messages.push({role,text:String(text),visuals:Array.isArray(visuals)?visuals.slice(0,3):[],at:new Date().toISOString()});saveMessages();renderMessages()}
function renderMessages(){const box=byId('academyMessages');box.replaceChildren();const items=messages.length?messages:[{role:'sinbad',text:'Welcome aboard. Ask any maritime question by writing or speaking. I will teach from the approved Atlas library and show verified maritime images when available.',visuals:[]}];items.forEach(message=>{const article=document.createElement('article');article.className=`academy-message ${message.role==='user'?'user':'sinbad'}`;const speaker=document.createElement('strong');speaker.textContent=message.role==='user'?'Captain':'Captain Sinbad';const body=document.createElement('p');body.textContent=message.text;article.append(speaker,body);if(message.role==='sinbad'&&message.visuals?.length){const visualGrid=renderVisuals(message.visuals);if(visualGrid.childElementCount)article.append(visualGrid)}box.append(article)});box.scrollTop=box.scrollHeight}
function renderVisuals(visuals){const grid=document.createElement('div');grid.className='academy-visuals';const safeAsset=/^(?:\.\/visual-library\/assets\/(?:bowditch\/(?:assets\/[a-f0-9]{64}\.[a-z0-9]+|fallback-pages\/volume-[12]-page-[0-9]+\.png)|nga-chart-no-1\/page-[0-9]{3}\.png|curated-safety\/(?:lifebuoy-scarborough|inflatable-life-raft-us-navy|sart-radar-transponder|fully-enclosed-lifeboat|life-jacket-inspection-uscg|epirb-ferry-vi|inflated-life-raft-us-navy-historic|marine-evacuation-life-raft-pod|mob-distress-marker-lights|rescue-boat-retrieval)\.jpg)|http:\/\/127\.0\.0\.1:31983\/visuals\/assets\/[a-f0-9]{64}\.webp)$/u;visuals.filter(visual=>safeAsset.test(visual?.src||'')).forEach(visual=>{const figure=document.createElement('figure');figure.className='academy-atlas-visual';const image=document.createElement('img');image.src=visual.src;image.alt=visual.alt||'Verified maritime visual';image.loading='lazy';const caption=document.createElement('figcaption');caption.textContent=visual.caption||'Verified maritime visual';figure.append(image,caption);grid.append(figure)});return grid}
function getCloudConfig(){return {url:localStorage.getItem('atlas_supabase_url')||DEFAULT_CLOUD.url,key:localStorage.getItem('atlas_supabase_publishable_key')||DEFAULT_CLOUD.key}}
async function initCloud(){if(!window.supabase){byId('academyCloudStatus').textContent='Atlas client unavailable';return}const {url,key}=getCloudConfig();cloudClient=window.supabase.createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await cloudClient.auth.getSession();cloudSession=data.session;byId('academyCloudStatus').textContent=cloudSession?.user?'Atlas knowledge connected':'Sign in to Atlas Marine in the main window';cloudClient.auth.onAuthStateChange((_event,session)=>{cloudSession=session;byId('academyCloudStatus').textContent=session?.user?'Atlas knowledge connected':'Sign in to Atlas Marine in the main window'})}
function coreAnswerIsTrusted(data,envelope){return Boolean(data?.answer&&data.coreGateVersion===window.SinbadCore?.CORE_GATE_VERSION&&data.coreGateVersion===envelope?.gateVersion&&data.permission==='DECISION_SUPPORT_ONLY'&&data.executionPerformed===false)}
async function askSinbad(question){const workspaceId=localStorage.getItem('atlas_selected_workspace')||localStorage.getItem('atlas-v81-workspace')||'';if(!cloudClient||!cloudSession?.user||!workspaceId)throw new Error('Atlas Cloud oturumu veya çalışma alanı bağlı değil. Ana Sinbad penceresinde oturum açın.');const history=messages.slice(0,-1).slice(-12).map(message=>({role:message.role==='sinbad'?'assistant':'user',content:message.text}));const coreEnvelope=window.SinbadCore?.aiEnvelope?.(question,history);const {data,error}=await cloudClient.functions.invoke('sinbad-answer',{body:{workspaceId,question,language:'tr-TR',includeSourceVisuals:false,suppressSourceVisuals:true,coreEnvelope}});if(error)throw error;if(!coreAnswerIsTrusted(data,coreEnvelope))throw new Error('Sinbad güvenlik/kanıt kapısı bu cevabı durdurdu.');const answer=String(data.answer).trim(),visuals=await window.SinbadVisuals?.select?.(question,answer,{max:1})||[];return {answer,spokenSummary:String(data.spokenSummary||data.answer).trim(),visuals}}
async function submitQuestion(question){const clean=String(question||'').trim();if(!clean)return;stopNarration('Thinking');addMessage('user',clean);byId('academyQuestion').value='';byId('academySend').disabled=true;setInstructorState('thinking','Searching approved Atlas sources');byId('academyCloudStatus').textContent='Searching Atlas knowledge and visual library…';try{const result=await askSinbad(clean);addMessage('sinbad',result.answer,result.visuals);byId('academyCloudStatus').textContent=result.visuals.length?`${result.visuals.length} verified maritime image(s) attached`:'Answer ready · no matching maritime image found';speak(result.spokenSummary,{afterState:'listening',afterStatus:'Captain Sinbad is ready for your next question'})}catch(error){addMessage('sinbad',`Bu soruyu şu anda tamamlayamadım: ${error.message||error}`);byId('academyCloudStatus').textContent='Answer stopped safely';setInstructorState('idle','I need a connected source before answering')}finally{byId('academySend').disabled=false;byId('academyQuestion').focus()}}
function setupRecognition(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){byId('academyMic').disabled=true;byId('academyMic').title='Speech recognition is unavailable in this browser';return}recognition=new Recognition();recognition.lang='tr-TR';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{byId('academyMic').setAttribute('aria-pressed','true');setInstructorState('listening','Captain Sinbad is listening')};recognition.onresult=event=>{byId('academyQuestion').value=[...event.results].map(result=>result[0].transcript).join('')};recognition.onend=()=>{byId('academyMic').setAttribute('aria-pressed','false');setInstructorState('idle','Voice question captured')};recognition.onerror=event=>{byId('academyMic').setAttribute('aria-pressed','false');setInstructorState('idle',`Microphone: ${event.error}`)}}
restoreWindowGeometry();renderMessages();syncVoiceControls();initCloud();setupRecognition();
byId('academyChatForm').addEventListener('submit',event=>{event.preventDefault();submitQuestion(byId('academyQuestion').value)});
byId('academyQuestion').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();byId('academyChatForm').requestSubmit()}});
byId('academyMic').addEventListener('click',()=>{if(!recognition)return;if(byId('academyMic').getAttribute('aria-pressed')==='true')recognition.stop();else recognition.start()});
byId('startAcademyLesson').addEventListener('click',renderLesson);byId('startAcademyQuiz').addEventListener('click',renderQuiz);
byId('academyVoiceToggle').addEventListener('click',()=>{voiceEnabled=!voiceEnabled;localStorage.setItem(VOICE_KEY,String(voiceEnabled));if(!voiceEnabled)stopNarration('Voice is off');syncVoiceControls()});byId('academyReplayVoice').addEventListener('click',()=>speak(lastNarration));byId('academyStopVoice').addEventListener('click',()=>stopNarration());
byId('closeAcademyWindow').addEventListener('click',()=>{stopNarration();saveWindowGeometry();window.close()});window.addEventListener('beforeunload',()=>{stopNarration();recognition?.abort();objectUrls.forEach(URL.revokeObjectURL);saveWindowGeometry()});
