'use strict';
const $=id=>document.getElementById(id),DEFAULT_URL='https://kcvyftrvteqmabvxfebu.supabase.co',DEFAULT_KEY='sb_publishable_ZBHFlbhQAnhUAOyVg20Szw_nW0QDj_l';
const config={url:localStorage.getItem('atlas_supabase_url')||DEFAULT_URL,key:localStorage.getItem('atlas_supabase_publishable_key')||DEFAULT_KEY};
const client=window.supabase?.createClient(config.url,config.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,current=null,humanRole='',answerRole='',packages=[],packageCursor=null,selectedPackage=null,questionCursor=0;
const ownerSecurity=client&&window.SinbadOwnerUi?.create(client);
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'ok'}
function workspace(){return $('workspaceId').value.trim()||localStorage.getItem('atlas_selected_workspace')||localStorage.getItem('atlas-v81-workspace')||''}
async function invokeFunction(name,body){if(!client||!session)throw new Error('Sinbad Marine ana sayfasında oturum açmanız gerekir.');const {data,error}=await client.functions.invoke(name,{body:{workspaceId:workspace(),...body}});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
const invoke=body=>invokeFunction('exam-answer-key-review',body),humanInvoke=body=>invokeFunction('human-review',body);
function node(tag,text,className){const out=document.createElement(tag);if(text!==undefined)out.textContent=String(text);if(className)out.className=className;return out}
function setMode(mode){const human=mode==='packages';$('packageSurface').hidden=!human;$('answerSurface').hidden=human;$('showPackages').classList.toggle('active',human);$('showAnswerKeys').classList.toggle('active',!human);$('showPackages').setAttribute('aria-pressed',String(human));$('showAnswerKeys').setAttribute('aria-pressed',String(!human))}
function renderPackages(){
 $('packageCount').textContent=String(packages.length);$('packageList').replaceChildren(...packages.map(pkg=>{const b=node('button',undefined,'package-row');b.type='button';b.append(node('strong',pkg.title),node('small',`${pkg.status} · ${pkg.reviewed_count}/${pkg.present_count} · ${pkg.package_complete?'kaynak tam':'eksik/ertelenmiş'}`));b.addEventListener('click',()=>loadPackage(pkg.id));return b}));$('nextPackages').hidden=!packageCursor;
 const complete=packages.filter(x=>x.package_complete).length,reviewed=packages.reduce((n,x)=>n+x.reviewed_count,0),present=packages.reduce((n,x)=>n+x.present_count,0);$('completenessSummary').textContent=`${complete}/${packages.length}`;$('progressSummary').textContent=`${reviewed}/${present}`;
}
async function loadPackages(append=false){try{status('Paket yetkileri denetleniyor…');const data=await humanInvoke({action:'list_packages',limit:25,cursor:append?packageCursor:null});humanRole=data.role;$('humanRole').textContent=data.role;packages=append?[...packages,...data.items]:data.items;packageCursor=data.nextCursor;renderPackages();$('ownerReviewerPanel').hidden=data.role!=='OWNER';if(data.role==='OWNER')await loadReviewers();status(`${data.role} · ${packages.length} paket gösteriliyor`)}catch(error){status(error.message,true)}}
function metric(label,value){const span=node('span');span.append(node('small',label),node('strong',value));return span}
function reviewOf(item){return Array.isArray(item.human_question_reviews)?item.human_question_reviews[0]:item.human_question_reviews}
function renderQuestions(items){$('questionList').replaceChildren(...items.map(item=>{const review=reviewOf(item),card=node('section',undefined,'question-card');card.append(node('h4',`${item.position}. ${item.question_id}`),node('p',`Teknik durum: ${item.technical_status}`,'muted'));
 const payload=node('pre');payload.textContent=JSON.stringify(item.question_payload,null,2);const evidence=node('pre');evidence.textContent=JSON.stringify(item.evidence_payload,null,2);card.append(payload,node('h5','Kaynak / provenance'),evidence,node('p',`Human: ${review?.human_decision||'PENDING'} · Owner: ${review?.owner_decision||'PENDING'}`,'muted'));
 if(humanRole==='HUMAN_REVIEWER'){const note=node('textarea');note.maxLength=2000;note.placeholder='İnceleme notu';note.value=review?.note||'';const actions=node('div',undefined,'actions');for(const [decision,label,warn] of [['APPROVED','Onayla'],['CORRECTION_REQUIRED','Düzeltme gerekli',true],['SOURCE_HOLD','Kaynak sorunu / beklet',true]]){const b=node('button',label,warn?'warn':'');b.type='button';b.addEventListener('click',()=>saveDecision(item.question_id,decision,note.value));actions.append(b)}card.append(note,actions)}return card}));}
async function loadPackage(id,after=0){try{status('Paket yükleniyor…');const data=await humanInvoke({action:'package_detail',packageId:id,afterPosition:after,limit:25});selectedPackage=data.package;questionCursor=data.nextPosition;$('packageEmpty').hidden=true;$('packageDetail').hidden=false;$('packageState').textContent=`${selectedPackage.status} · atama nesli ${selectedPackage.assignment_generation} · sürüm ${selectedPackage.lock_version}`;$('packageTitle').textContent=selectedPackage.title;$('packageMetrics').replaceChildren(metric('Beklenen',selectedPackage.expected_count),metric('Mevcut',selectedPackage.present_count),metric('Eksik / ertelenmiş',`${selectedPackage.missing_count} / ${selectedPackage.deferred_count}`),metric('İncelenen',selectedPackage.reviewed_count));$('claimPackage').hidden=humanRole!=='HUMAN_REVIEWER'||selectedPackage.status!=='AVAILABLE';$('submitPackage').hidden=humanRole!=='HUMAN_REVIEWER'||!['ASSIGNED','IN_REVIEW'].includes(selectedPackage.status);$('ownerTransfer').hidden=humanRole!=='OWNER';$('ownerFinal').hidden=humanRole!=='OWNER'||!['SUBMITTED_COMPLETE','SUBMITTED_INCOMPLETE'].includes(selectedPackage.status);$('acceptPackage').disabled=selectedPackage.status!=='SUBMITTED_COMPLETE';$('auditPanel').hidden=humanRole!=='OWNER';renderQuestions(data.items);$('nextQuestions').hidden=!questionCursor;if(humanRole==='OWNER')await loadAudit();status('Paket güvenli olarak yüklendi.')}catch(error){status(error.message,true)}}
async function claimPackage(){if(!selectedPackage)return;try{const data=await humanInvoke({action:'claim_package',packageId:selectedPackage.id,expectedLockVersion:selectedPackage.lock_version,requestId:crypto.randomUUID()});selectedPackage={...selectedPackage,...data.result,assignment_generation:data.result.assignmentGeneration,lock_version:data.result.lockVersion,status:data.result.status};await loadPackage(selectedPackage.id);await loadPackages();}catch(error){status(`${error.message}; paket yeniden yükleniyor.`,true);await loadPackage(selectedPackage.id)}}
async function saveDecision(questionId,decision,note){if(!selectedPackage)return;try{const data=await humanInvoke({action:'save_decision',packageId:selectedPackage.id,questionId,decision,note,assignmentGeneration:selectedPackage.assignment_generation,expectedLockVersion:selectedPackage.lock_version,requestId:crypto.randomUUID()});selectedPackage.lock_version=data.result.lockVersion;await loadPackage(selectedPackage.id);status('Human Review kararı kaydedildi.')}catch(error){status(`${error.message}; güncel sürüm yükleniyor.`,true);await loadPackage(selectedPackage.id)}}
async function submitPackage(){if(!selectedPackage)return;try{const data=await humanInvoke({action:'submit_package',packageId:selectedPackage.id,assignmentGeneration:selectedPackage.assignment_generation,expectedLockVersion:selectedPackage.lock_version,requestId:crypto.randomUUID()});await loadPackages();await loadPackage(selectedPackage.id);status(`Paket gönderildi: ${data.result.status}`)}catch(error){status(error.message,true)}}
async function ownerProof(descriptor,summary){if(!ownerSecurity)throw new Error('Owner güvenlik modülü kullanılamıyor.');return ownerSecurity.authorize(descriptor,summary)}
async function importPackage(){try{const manifest=JSON.parse($('manifestInput').value),requestId=crypto.randomUUID(),command={workspaceId:workspace(),manifest},descriptor={action:'identity.human_review.package_import',resourceType:'review_manifest',resourceId:String(manifest.sourceBatchId||''),workspaceId:workspace(),command},stepUp=await ownerProof(descriptor,'Human Review paketini içe al');await humanInvoke({action:'import_package',manifest,requestId,stepUp});$('manifestInput').value='';await loadPackages();status('Manifest doğrulandı; paket Human Review kuyruğuna eklendi.')}catch(error){status(error instanceof SyntaxError?'Manifest geçerli JSON değil.':error.message,true)}}
async function setReviewerState(){try{const userId=$('reviewerUserId').value.trim(),state=$('reviewerState').value,note=$('reviewerNote').value.trim(),requestId=crypto.randomUUID(),command={workspaceId:workspace(),userId,state,note},descriptor={action:'identity.human_reviewer.set_state',resourceType:'workspace_member',resourceId:userId,workspaceId:workspace(),command},stepUp=await ownerProof(descriptor,'Reviewer erişimini değiştir');await humanInvoke({action:'set_reviewer_state',userId,state,note,requestId,stepUp});await loadReviewers();status('Reviewer yetkisi kaydedildi.')}catch(error){status(error.message,true)}}
async function transferPackage(){if(!selectedPackage)return;try{const targetUserId=$('transferTarget').value.trim()||null,note=$('transferNote').value.trim(),expectedLockVersion=selectedPackage.lock_version,requestId=crypto.randomUUID(),command={workspaceId:workspace(),packageId:selectedPackage.id,targetUserId,expectedLockVersion,note},descriptor={action:'identity.human_review.package_transfer',resourceType:'review_package',resourceId:selectedPackage.id,workspaceId:workspace(),command},stepUp=await ownerProof(descriptor,'Paket atamasını değiştir');await humanInvoke({action:'transfer_package',packageId:selectedPackage.id,targetUserId,expectedLockVersion,note,requestId,stepUp});await loadPackages();await loadPackage(selectedPackage.id);status('Paket ataması güncellendi.')}catch(error){status(error.message,true)}}
async function finalizePackage(decision){if(!selectedPackage)return;try{const note=$('ownerFinalNote').value.trim(),expectedLockVersion=selectedPackage.lock_version,requestId=crypto.randomUUID(),command={workspaceId:workspace(),packageId:selectedPackage.id,decision,note,expectedLockVersion},descriptor={action:'identity.human_review.package_finalize',resourceType:'review_package',resourceId:selectedPackage.id,workspaceId:workspace(),command},stepUp=await ownerProof(descriptor,decision==='ACCEPTED'?'Paketi nihai olarak kabul et':'Paketi Reviewer’a iade et');await humanInvoke({action:'owner_finalize_package',packageId:selectedPackage.id,decision,note,expectedLockVersion,requestId,stepUp});await loadPackages();await loadPackage(selectedPackage.id);status(decision==='ACCEPTED'?'Paket Owner tarafından kabul edildi.':'Paket Reviewer’a iade edildi.')}catch(error){status(`${error.message}; güncel sürüm yükleniyor.`,true);await loadPackage(selectedPackage.id)}}
async function loadReviewers(){const data=await humanInvoke({action:'list_reviewers'});$('reviewerList').replaceChildren(...data.items.map(x=>{const a=node('article');a.append(node('strong',x.user_id),node('small',`${x.state} · ${x.updated_at}`));return a}))}
async function loadAudit(){const data=await humanInvoke({action:'list_audit',packageId:selectedPackage.id,limit:50});$('auditList').replaceChildren(...data.items.map(x=>{const a=node('article');a.append(node('strong',x.action),node('small',`${x.actor_kind} · ${x.actor_id} · ${x.created_at}`),node('p',x.note||''));return a}))}
function clearDetail(){$('detail').hidden=true;$('empty').hidden=false;current=null}
async function loadReviews(){try{status('Cevap anahtarı yetkisi denetleniyor…');const data=await invoke({action:'list'});answerRole=data.role;$('reviewList').replaceChildren(...data.reviews.map(review=>{const button=node('button',undefined,'review');button.type='button';button.append(node('strong',review.question_ref),node('small',`Developer: ${review.developer_decision} · Owner: ${review.owner_final_decision}`));button.addEventListener('click',()=>loadDetail(review.id));return button}));status(`${data.role} · ${data.reviews.length} kayıt`);if(!data.reviews.length)clearDetail()}catch(error){status(error.message,true);clearDetail()}}
async function loadDetail(id){try{const data=await invoke({action:'detail',reviewId:id});current=data.review;answerRole=data.role;$('empty').hidden=true;$('detail').hidden=false;$('role').textContent=`Doğrulanmış rol: ${answerRole}`;$('questionRef').textContent=data.review.question_ref;$('answerHash').textContent=data.review.answer_key_hash;$('answerKey').textContent=JSON.stringify(data.answerKey,null,2);$('developerActions').hidden=answerRole!=='developer';$('ownerActions').hidden=answerRole!=='owner';status('Kayıt güvenli olarak yüklendi.')}catch(error){status(error.message,true);clearDetail()}}
async function decide(action,decision){if(!current)return;try{const id=current.id,data=await invoke({action,decision,reviewId:id,note:$('note').value});await loadReviews();await loadDetail(id);status(`Karar kaydedildi · sonraki kapı: ${data.nextGate}`)}catch(error){status(error.message,true)}}
$('showPackages').onclick=()=>setMode('packages');$('showAnswerKeys').onclick=()=>setMode('answers');$('loadPackages').onclick=()=>loadPackages();$('nextPackages').onclick=()=>loadPackages(true);$('nextQuestions').onclick=()=>loadPackage(selectedPackage.id,questionCursor);$('claimPackage').onclick=claimPackage;$('submitPackage').onclick=submitPackage;$('importPackage').onclick=importPackage;$('saveReviewerState').onclick=setReviewerState;$('transferPackage').onclick=transferPackage;$('acceptPackage').onclick=()=>finalizePackage('ACCEPTED');$('returnPackage').onclick=()=>finalizePackage('RETURNED');$('loadReviews').onclick=loadReviews;$('signOut').onclick=async()=>{await client?.auth.signOut();location.href='./index.html'};document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>decide(b.dataset.action,b.dataset.decision)));
(async()=>{if(!client){status('Supabase istemcisi yüklenemedi.',true);return}const {data,error}=await client.auth.getSession();if(error||!data.session){status('Oturum yok. Önce Sinbad Marine ana sayfasında giriş yapın.',true);return}session=data.session;$('workspaceId').value=workspace();if(!workspace())status('Oturum açık; bir workspace seçin.',true);else await loadPackages()})();
