'use strict';
const $=id=>document.getElementById(id),DEFAULT_URL='https://kcvyftrvteqmabvxfebu.supabase.co',DEFAULT_KEY='sb_publishable_ZBHFlbhQAnhUAOyVg20Szw_nW0QDj_l';
const config={url:localStorage.getItem('atlas_supabase_url')||DEFAULT_URL,key:localStorage.getItem('atlas_supabase_publishable_key')||DEFAULT_KEY};
const client=window.supabase?.createClient(config.url,config.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,current=null,currentRole='';
function status(text,error=false){$('status').textContent=text;$('status').style.color=error?'#ff9d9d':'#a9becf'}
function workspace(){return $('workspaceId').value.trim()||localStorage.getItem('atlas_selected_workspace')||localStorage.getItem('atlas-v81-workspace')||''}
async function invoke(body){if(!client||!session)throw new Error('Sinbad Marine ana sayfasında oturum açmanız gerekir.');const {data,error}=await client.functions.invoke('exam-answer-key-review',{body:{workspaceId:workspace(),...body}});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
function clearDetail(){$('detail').hidden=true;$('empty').hidden=false;current=null}
async function loadReviews(){try{status('Yetki ve kayıtlar denetleniyor…');const data=await invoke({action:'list'});currentRole=data.role;$('reviewList').replaceChildren(...data.reviews.map(review=>{const button=document.createElement('button');button.className='review';button.type='button';button.append(Object.assign(document.createElement('strong'),{textContent:review.question_ref}),Object.assign(document.createElement('small'),{textContent:`Developer: ${review.developer_decision} · Owner: ${review.owner_final_decision}`}));button.addEventListener('click',()=>loadDetail(review.id));return button}));status(`${data.role} erişimi doğrulandı · ${data.reviews.length} kayıt`);if(!data.reviews.length)clearDetail()}catch(error){status(error.message,true);clearDetail()}}
async function loadDetail(id){try{status('Gizli cevap anahtarı yetkili kanaldan alınıyor…');const data=await invoke({action:'detail',reviewId:id});current=data.review;currentRole=data.role;$('empty').hidden=true;$('detail').hidden=false;$('role').textContent=`Doğrulanmış rol: ${data.role}`;$('questionRef').textContent=data.review.question_ref;$('answerHash').textContent=data.review.answer_key_hash;$('answerKey').textContent=JSON.stringify(data.answerKey,null,2);$('developerActions').hidden=data.role!=='developer';$('ownerActions').hidden=data.role!=='owner';status('Kayıt güvenli olarak yüklendi.')}catch(error){status(error.message,true);clearDetail()}}
async function decide(action,decision){if(!current)return;const reviewId=current.id;try{status('Karar kaydediliyor…');const data=await invoke({action,decision,reviewId,note:$('note').value});await loadReviews();await loadDetail(reviewId);status(`Karar kaydedildi · sonraki kapı: ${data.nextGate}`)}catch(error){status(error.message,true)}}
$('loadReviews').addEventListener('click',loadReviews);$('signOut').addEventListener('click',async()=>{await client?.auth.signOut();location.href='./index.html'});document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>decide(button.dataset.action,button.dataset.decision)));
(async()=>{if(!client){status('Supabase istemcisi yüklenemedi.',true);return}const {data,error}=await client.auth.getSession();if(error||!data.session){status('Oturum yok. Önce Sinbad Marine ana sayfasında giriş yapın.',true);return}session=data.session;$('workspaceId').value=workspace();if(!workspace())status('Oturum açık; bir workspace seçin.',true);else await loadReviews()})();
