// RESOURCE_DATA — Blue Voyage / Yacht Tourism Resource Guide
// Turkish Aegean & Mediterranean coast: islands, historical sites, entertainment
// spots, marinas, fuel docks and harbour master's offices for charter and
// itinerary planning. Coordinates are approximate reference points (verify on
// current charts). Contact numbers, VHF channels and opening details change —
// always reconfirm with the facility or official source before relying on them
// operationally.
const RESOURCE_DATA = [

// ---------- Çanakkale & Bozcaada–Gökçeada ----------
{"category":"Island","region":"Çanakkale & Bozcaada–Gökçeada","name":"Bozcaada (Tenedos)","coordinates":"39.82°N, 26.06°E","description":"Aegean island famous for vineyards, a Venetian-Genoese castle above the harbour, and clear-water beaches (Ayana, Habbele, Ayazma).","highlights":["Wine tasting","Castle","Swimming","Small-boat harbour"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Harbour is small and busy in summer; anchoring off the beaches is the more comfortable option for larger yachts."},
{"category":"Island","region":"Çanakkale & Bozcaada–Gökçeada","name":"Gökçeada (Imbros)","coordinates":"40.18°N, 25.85°E","description":"Turkey's largest island; known for Aydıncık beach, diving sites, the historic Rum (Greek) village of Kaleköy, and strong winds favoured by windsurfers.","highlights":["Diving","Windsurfing","Beaches","Village architecture"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Exposed to the meltemi; check wind forecast before planning an overnight anchorage here."},
{"category":"Historical Site","region":"Çanakkale & Bozcaada–Gökçeada","name":"Troy (Truva)","coordinates":"39.96°N, 26.24°E","description":"UNESCO World Heritage archaeological site of ancient Troy, with excavated city layers and a replica Trojan Horse at the visitor entrance.","highlights":["UNESCO World Heritage","Museum","Guided tours"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Not on the shoreline — reached by a short taxi/tour (~30 min) from Çanakkale; plan as a half-day excursion, not a tender stop."},
{"category":"Entertainment & Nightlife","region":"Çanakkale & Bozcaada–Gökçeada","name":"Çanakkale Kordon Waterfront","coordinates":"40.15°N, 26.41°E","description":"Seafront promenade lined with cafés and fish restaurants near the Trojan Horse monument and Çimenlik Castle.","highlights":["Waterfront dining","Sunset views"],"vhf":"—","services":["Restaurants","Cafés"],"contact":"Confirm locally","captainNote":"Good crew-change or provisioning stop; venues and hours change seasonally, verify current status."},
{"category":"Fuel Station","region":"Çanakkale & Bozcaada–Gökçeada","name":"Çanakkale Fuel Dock","coordinates":"40.15°N, 26.41°E","description":"Bunkering point on the Dardanelles serving transiting yachts; duty-free fuel available for foreign-flagged vessels via local agents.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering","Agent-arranged delivery"],"contact":"Confirm via local yacht agent","captainNote":"Order at least a day ahead through an agent; strong current in the strait, plan approach accordingly."},
{"category":"Harbour Master's Office","region":"Çanakkale & Bozcaada–Gökçeada","name":"Çanakkale Liman Başkanlığı","coordinates":"40.15°N, 26.41°E","description":"Regional harbour master's office covering Dardanelles traffic and check-in/out formalities.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 286 212 98 76 (verify before relying on it)","captainNote":"Confirm current entry-port formalities before transiting the Dardanelles with foreign crew/guests aboard."},
{"category":"Harbour Master's Office","region":"Çanakkale & Bozcaada–Gökçeada","name":"Bozcaada Liman Başkanlığı","coordinates":"39.82°N, 26.06°E","description":"Local harbour master's office for Bozcaada island.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 286 697 80 21 (verify before relying on it)","captainNote":"Small office; hours can be limited outside peak season."},

// ---------- Ayvalık & Assos (Edremit Gulf) ----------
{"category":"Island","region":"Ayvalık & Assos (Edremit Gulf)","name":"Cunda (Alibey) Island","coordinates":"39.36°N, 26.65°E","description":"Island in the Ayvalık archipelago connected by causeway to the mainland, known for preserved Greek-era stone houses and a lively seafood-taverna scene.","highlights":["Old town","Seafood","Architecture"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Popular lunch-stop anchorage; the Ayvalık archipelago's many islets offer sheltered swim stops nearby."},
{"category":"Historical Site","region":"Ayvalık & Assos (Edremit Gulf)","name":"Assos (Behramkale)","coordinates":"39.49°N, 26.34°E","description":"Ancient city on a hilltop above a small stone harbour, with a well-known Temple of Athena; Aristotle taught here in the 4th century BC.","highlights":["Temple of Athena","Ancient harbour","Sunset views"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"The small ancient harbour below the ruins can take tenders; larger yachts anchor off and land by tender."},
{"category":"Entertainment & Nightlife","region":"Ayvalık & Assos (Edremit Gulf)","name":"Ayvalık Old Town & Cunda Tavernas","coordinates":"39.32°N, 26.70°E","description":"Cobblestone streets with meyhane-style seafood restaurants, olive-oil shops and waterfront cafés.","highlights":["Meyhane dining","Local olive oil","Live music (seasonal)"],"vhf":"—","services":["Restaurants","Bars"],"contact":"Confirm locally","captainNote":"Verify current opening status of specific venues — turnover is frequent between seasons."},
{"category":"Marina","region":"Ayvalık & Assos (Edremit Gulf)","name":"Setur Ayvalık Marina","coordinates":"39.31°N, 26.69°E","description":"Marina serving the Ayvalık archipelago area, part of the Setur Marinas chain.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Provisioning nearby"],"contact":"Confirm via seturmarinas.com","captainNote":"Good staging point before or after crossing to the Greek islands of Lesvos/Ayvalık archipelago."},
{"category":"Fuel Station","region":"Ayvalık & Assos (Edremit Gulf)","name":"Ayvalık Fuel Dock","coordinates":"39.31°N, 26.69°E","description":"Bunkering point within the marina/harbour area for yachts provisioning fuel.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"Arrange through a yacht agent for duty-free bunkering if flagged foreign."},
{"category":"Harbour Master's Office","region":"Ayvalık & Assos (Edremit Gulf)","name":"Ayvalık Liman Başkanlığı","coordinates":"39.31°N, 26.69°E","description":"Harbour master's office for the Ayvalık area.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 266 312 11 30 (verify before relying on it)","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Ayvalık & Assos (Edremit Gulf)","name":"Edremit Liman Başkanlığı","coordinates":"39.60°N, 27.02°E","description":"Harbour master's office covering the Edremit Gulf.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 266 384 10 15 (verify before relying on it)","captainNote":"—"},

// ---------- Izmir–Çeşme–Foça ----------
{"category":"Island","region":"Izmir–Çeşme–Foça","name":"Eşek Adası (Donkey Island), Foça","coordinates":"38.70°N, 26.70°E","description":"Small islet near Foça known for clear water and free-roaming donkeys; a popular local swim/snorkel stop.","highlights":["Swimming","Snorkelling"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Shallow approaches — check depth on chart before closing the island."},
{"category":"Historical Site","region":"Izmir–Çeşme–Foça","name":"Foça (Ancient Phocaea) & Beş Kapılar Adası","coordinates":"38.67°N, 26.75°E","description":"Ancient Ionian city that founded colonies as far as Marseille; old town walls, Roman-era remains and the nearby Five Gates rock formations.","highlights":["Ancient city walls","Rock formations","Old town"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Foça bay offers sheltered anchoring close to the old town."},
{"category":"Historical Site","region":"Izmir–Çeşme–Foça","name":"Agora of Smyrna, İzmir","coordinates":"38.42°N, 27.14°E","description":"Well-preserved Roman-era agora (marketplace) in central İzmir with standing colonnades and vaulted basement galleries.","highlights":["Roman ruins","City-centre museum site"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Best combined with an İzmir Konak/Kordon city visit rather than a direct tender landing."},
{"category":"Entertainment & Nightlife","region":"Izmir–Çeşme–Foça","name":"Alaçatı","coordinates":"38.28°N, 26.37°E","description":"Boutique town of restored stone houses turned into design hotels, cafés and bars; a windsurfing/kitesurfing hub at nearby Alaçatı Bay.","highlights":["Boutique bars","Windsurfing","Design shopping"],"vhf":"—","services":["Restaurants","Bars","Boutique hotels"],"contact":"Confirm locally","captainNote":"Very popular with Turkish weekenders in summer — book restaurant tables ahead."},
{"category":"Marina","region":"Izmir–Çeşme–Foça","name":"Çeşme Marina","coordinates":"38.32°N, 26.31°E","description":"Marina at the tip of the Çeşme peninsula, close to the ferry connection to Chios (Greece).","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Provisioning"],"contact":"Confirm via marina","captainNote":"Convenient customs/check-out point before crossing to the Greek islands."},
{"category":"Marina","region":"Izmir–Çeşme–Foça","name":"Alaçatı Marina","coordinates":"38.27°N, 26.38°E","description":"Marina serving Alaçatı Bay, close to the windsurfing beaches and the boutique town centre.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via marina","captainNote":"Bay can build a short chop with the prevailing summer meltemi — check wind before berthing approach."},
{"category":"Marina","region":"Izmir–Çeşme–Foça","name":"Teos Marina","coordinates":"38.19°N, 26.80°E","description":"Marina near the ancient city of Teos on the Sığacık peninsula, south of Çeşme.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via marina","captainNote":"Quiet alternative to the busier Çeşme/Alaçatı marinas."},
{"category":"Fuel Station","region":"Izmir–Çeşme–Foça","name":"Çeşme Fuel Dock","coordinates":"38.32°N, 26.31°E","description":"Bunkering point within Çeşme Marina.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Izmir–Çeşme–Foça","name":"İzmir Liman Başkanlığı","coordinates":"38.42°N, 27.14°E","description":"Regional harbour master's office for the İzmir Gulf.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 232 463 73 20 (verify before relying on it)","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Izmir–Çeşme–Foça","name":"Çeşme Liman Başkanlığı","coordinates":"38.32°N, 26.31°E","description":"Harbour master's office for the Çeşme peninsula, a common Turkey/Greece crossing point.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 232 712 60 05 (verify before relying on it)","captainNote":"Handles frequent international check-in/out — allow time in season."},
{"category":"Harbour Master's Office","region":"Izmir–Çeşme–Foça","name":"Foça Liman Başkanlığı","coordinates":"38.67°N, 26.75°E","description":"Harbour master's office for the Foça area.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 232 812 17 46 (verify before relying on it)","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Izmir–Çeşme–Foça","name":"Dikili Liman Başkanlığı","coordinates":"39.07°N, 26.89°E","description":"Harbour master's office covering Dikili, north of the İzmir Gulf.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 232 671 41 01 (verify before relying on it)","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Izmir–Çeşme–Foça","name":"Aliağa Liman Başkanlığı","coordinates":"38.80°N, 26.97°E","description":"Harbour master's office covering the Aliağa industrial/commercial port area.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 232 616 19 93 (verify before relying on it)","captainNote":"Primarily a commercial port — not a typical charter stop."},

// ---------- Kuşadası–Selçuk (Ephesus)–Didim ----------
{"category":"Island","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Güvercinada (Pigeon Island), Kuşadası","coordinates":"37.86°N, 27.25°E","description":"Small islet connected to Kuşadası by a causeway, topped by a Genoese/Ottoman-era fortress and park.","highlights":["Castle walk","Harbour views"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Walkable from the town quay; not a tender/anchoring destination in itself."},
{"category":"Historical Site","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Ephesus (Efes)","coordinates":"37.94°N, 27.34°E","description":"One of the best-preserved ancient cities in the Mediterranean, with the Library of Celsus, the Great Theatre, and (nearby, at Selçuk) the remaining column of the Temple of Artemis, one of the Seven Wonders of the Ancient World.","highlights":["UNESCO World Heritage","Library of Celsus","Great Theatre","Seven Wonders site"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Reached by road (~20–30 min) from Kuşadası; one of the most-requested shore excursions on Aegean charters — book guide/transport ahead in peak season."},
{"category":"Historical Site","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Priene & Miletus (Milet)","coordinates":"37.66°N, 27.30°E","description":"Well-preserved Hellenistic grid-plan city (Priene) and the once-great port city of Miletus with its large Roman theatre, both near the Büyük Menderes delta.","highlights":["Hellenistic city plan","Roman theatre"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Both sites are inland of the silted ancient coastline — plan as a land excursion, not a tender landing."},
{"category":"Historical Site","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Temple of Apollo, Didyma (Didim)","coordinates":"37.38°N, 27.26°E","description":"Massive, partly-standing oracle temple of Apollo, one of the largest temples of the ancient Greek world.","highlights":["Ancient oracle site","Monumental columns"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Short taxi ride from Didim/D-Marin Didim marina."},
{"category":"Entertainment & Nightlife","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Kuşadası Bar Street & Marina Promenade","coordinates":"37.86°N, 27.26°E","description":"Lively waterfront strip of bars, clubs and restaurants catering to the cruise-ship and charter crowd.","highlights":["Bars","Live music","Waterfront dining"],"vhf":"—","services":["Restaurants","Bars","Clubs"],"contact":"Confirm locally","captainNote":"Can be very crowded on cruise-ship call days."},
{"category":"Marina","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Kuşadası Marina (Setur)","coordinates":"37.86°N, 27.26°E","description":"Full-service marina at the foot of Kuşadası old town, the usual base for Ephesus shore excursions.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel","Provisioning","Technical support"],"contact":"Confirm via seturmarinas.com","captainNote":"Popular embarkation/disembarkation point for charter guests flying via İzmir."},
{"category":"Marina","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"D-Marin Didim","coordinates":"37.38°N, 27.26°E","description":"Large marina (500+ berths) near Didim with wintering and maintenance facilities, close to the Temple of Apollo.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Haul-out/maintenance"],"contact":"Confirm via d-marin.com","captainNote":"Good option for technical work or winter lay-up in the northern Aegean."},
{"category":"Fuel Station","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Kuşadası Fuel Dock","coordinates":"37.86°N, 27.26°E","description":"Bunkering point within Kuşadası Marina.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Kuşadası–Selçuk (Ephesus)–Didim","name":"Kuşadası Liman Başkanlığı","coordinates":"37.86°N, 27.26°E","description":"Harbour master's office for the Kuşadası area, a major cruise and charter port of entry.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 256 614 10 25 (verify before relying on it)","captainNote":"Busy with cruise-ship traffic; allow extra time for formalities in season."},

// ---------- Bodrum Peninsula ----------
{"category":"Island","region":"Bodrum Peninsula","name":"Karaada (Black Island)","coordinates":"37.00°N, 27.49°E","description":"Small island off Bodrum with a natural hot-spring sea cave where swimmers cover themselves in mineral-rich clay/mud.","highlights":["Hot spring cave","Mud swim stop"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Popular day-charter stop from Bodrum; anchor off and tender in."},
{"category":"Historical Site","region":"Bodrum Peninsula","name":"Bodrum Castle (Castle of St. Peter)","coordinates":"37.03°N, 27.43°E","description":"Crusader-built castle overlooking Bodrum harbour, now home to the Museum of Underwater Archaeology.","highlights":["Museum of Underwater Archaeology","Harbour views"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Walkable from the town quay/marina."},
{"category":"Historical Site","region":"Bodrum Peninsula","name":"Mausoleum at Halicarnassus (ruins)","coordinates":"37.03°N, 27.43°E","description":"Site of one of the Seven Wonders of the Ancient World, the tomb of Mausolus; little remains above ground but the site and small museum explain its scale.","highlights":["Seven Wonders site"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Modest ruins today — best paired with the castle and old-town walk rather than as a standalone stop."},
{"category":"Historical Site","region":"Bodrum Peninsula","name":"Gümüşlük (Ancient Myndos)","coordinates":"37.05°N, 27.25°E","description":"Small fishing village built over the sunken remains of ancient Myndos; visible submerged walls and columns just off the beach.","highlights":["Snorkelling over ruins","Seafood village"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Protected archaeological zone — anchoring restrictions apply directly over the ruins; check current regulations."},
{"category":"Entertainment & Nightlife","region":"Bodrum Peninsula","name":"Bodrum Marina / Neyzen Tevfik Waterfront","coordinates":"37.03°N, 27.43°E","description":"Bodrum's main waterfront strip of restaurants, bars and boutiques between the castle and the marina.","highlights":["Waterfront dining","Bars","Shopping"],"vhf":"—","services":["Restaurants","Bars","Clubs"],"contact":"Confirm locally","captainNote":"Bodrum's historic disco/club scene (e.g. the former Halikarnas) has changed hands and venues repeatedly — verify current venues before promising guests a specific spot."},
{"category":"Entertainment & Nightlife","region":"Bodrum Peninsula","name":"Yalıkavak Palmarina Promenade","coordinates":"37.10°N, 27.29°E","description":"Upscale marina village with designer boutiques, waterfront restaurants and beach clubs, popular with the superyacht crowd.","highlights":["Boutique shopping","Fine dining","Beach clubs"],"vhf":"—","services":["Restaurants","Bars","Boutiques"],"contact":"Confirm locally","captainNote":"Book high-end restaurant tables well ahead in July–August."},
{"category":"Marina","region":"Bodrum Peninsula","name":"Yalıkavak Marina (Palmarina)","coordinates":"37.10°N, 27.29°E","description":"Premium marina on the Bodrum peninsula with superyacht berths, a boutique retail village and a yacht club.","highlights":[],"vhf":"Confirm with marina","services":["Berths (incl. superyacht)","Water","Shore power","Fuel (confirm)","Technical support"],"contact":"Confirm via marina","captainNote":"One of the busiest superyacht bases on the Turkish coast in high season — book berths well ahead."},
{"category":"Marina","region":"Bodrum Peninsula","name":"Milta Bodrum Marina","coordinates":"37.03°N, 27.43°E","description":"Central Bodrum marina beside the town and castle.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Provisioning"],"contact":"Confirm via marina","captainNote":"Most central option for guest embarkation in Bodrum town."},
{"category":"Marina","region":"Bodrum Peninsula","name":"D-Marin Turgutreis","coordinates":"37.02°N, 27.26°E","description":"Large marina (~550 berths) at the western tip of the Bodrum peninsula, with wintering and repair facilities.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Haul-out/maintenance"],"contact":"Confirm via d-marin.com","captainNote":"Good base for technical work or laying up for winter."},
{"category":"Fuel Station","region":"Bodrum Peninsula","name":"Bodrum Fuel Dock","coordinates":"37.03°N, 27.43°E","description":"Bunkering point serving Bodrum town/marina.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Fuel Station","region":"Bodrum Peninsula","name":"Yalıkavak / Turgutreis Fuel Docks","coordinates":"37.10°N, 27.29°E","description":"Bunkering points at the two western-peninsula marinas.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Bodrum Peninsula","name":"Bodrum Liman Başkanlığı","coordinates":"37.03°N, 27.43°E","description":"Regional harbour master's office covering the whole Bodrum peninsula.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 252 316 25 31 (verify before relying on it)","captainNote":"Handles a very high volume of charter traffic in season — allow time for formalities."},

// ---------- Datça–Knidos–Gökova Bay ----------
{"category":"Island","region":"Datça–Knidos–Gökova Bay","name":"Sedir Adası (Cleopatra Island)","coordinates":"37.02°N, 28.06°E","description":"Small island in Gökova Bay famous for a protected sand beach, legendarily brought from Egypt for Cleopatra; also has ancient Cedrae ruins.","highlights":["Legendary beach","Ancient ruins","Protected area"],"vhf":"—","services":[],"contact":"Confirm locally (Ministry-managed protected site)","captainNote":"Landing/entrance fee and rules apply — sand removal is prohibited and swimwear/behaviour rules are enforced; confirm current access conditions."},
{"category":"Historical Site","region":"Datça–Knidos–Gökova Bay","name":"Knidos (Cnidus)","coordinates":"36.69°N, 27.37°E","description":"Ancient city at the very tip of the Datça peninsula, with twin harbours, a theatre and terraces; once home to Praxiteles' celebrated statue of Aphrodite of Knidos.","highlights":["Twin ancient harbours","Theatre ruins","Praxiteles' Aphrodite (site)"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"One of the most scenic overnight anchorages on this coast; can be exposed to swell — check forecast before committing to an overnight stay."},
{"category":"Entertainment & Nightlife","region":"Datça–Knidos–Gökova Bay","name":"Eski Datça (Old Datça)","coordinates":"36.73°N, 27.68°E","description":"Restored stone village a short walk from Datça harbour, with quiet cafés, art galleries and taverna-style restaurants.","highlights":["Boutique cafés","Local crafts"],"vhf":"—","services":["Restaurants","Cafés"],"contact":"Confirm locally","captainNote":"Low-key, nature-focused region — Gökova Bay's coves are valued for quiet anchorages rather than nightlife."},
{"category":"Marina","region":"Datça–Knidos–Gökova Bay","name":"Datça Harbour","coordinates":"36.73°N, 27.68°E","description":"Small municipal harbour serving Datça town.","highlights":[],"vhf":"Confirm locally","services":["Berths (limited)","Water"],"contact":"Confirm locally","captainNote":"Limited space for larger yachts — anchoring off is often preferable."},
{"category":"Marina","region":"Datça–Knidos–Gökova Bay","name":"Gökova Ören Marina (Rib & Refit Park)","coordinates":"37.05°N, 28.10°E","description":"Marina and refit facility at the head of Gökova Bay.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Technical/refit support"],"contact":"Confirm via seturmarinas.com","captainNote":"Useful technical stop within the sheltered waters of Gökova Bay."},
{"category":"Fuel Station","region":"Datça–Knidos–Gökova Bay","name":"Datça Fuel Dock","coordinates":"36.73°N, 27.68°E","description":"Bunkering point serving Datça harbour.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"Fuel availability can be limited — confirm ahead in shoulder season."},
{"category":"Harbour Master's Office","region":"Datça–Knidos–Gökova Bay","name":"Datça Liman Başkanlığı","coordinates":"36.73°N, 27.68°E","description":"Harbour master's office for the Datça peninsula.","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"0 252 712 22 26 (verify before relying on it)","captainNote":"—"},

// ---------- Marmaris–Dalyan ----------
{"category":"Historical Site","region":"Marmaris–Dalyan","name":"Kaunos (near Dalyan)","coordinates":"36.83°N, 28.60°E","description":"Ancient city reached via the Dalyan river; famous for monumental Lycian rock-cut tombs carved into the cliff face, visible from the water.","highlights":["Lycian rock tombs","River approach","Roman theatre"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Best experienced by tender/small boat up the Dalyan river channel rather than the main yacht anchorage."},
{"category":"Historical Site","region":"Marmaris–Dalyan","name":"İztuzu Beach (Turtle Beach)","coordinates":"36.80°N, 28.62°E","description":"Protected sand-spit beach and nesting site for loggerhead (Caretta caretta) sea turtles, at the mouth of the Dalyan river.","highlights":["Turtle nesting site","Long sand beach","Protected nature area"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Nesting-season access restrictions apply on parts of the beach (roughly May–October) — respect marked areas and lighting rules at night."},
{"category":"Entertainment & Nightlife","region":"Marmaris–Dalyan","name":"Marmaris Bar Street (Barlar Sokağı)","coordinates":"36.85°N, 28.27°E","description":"Marmaris's dense strip of bars and clubs behind the marina, one of the liveliest nightlife areas on this coast.","highlights":["Bars","Clubs","Live DJs"],"vhf":"—","services":["Bars","Clubs","Restaurants"],"contact":"Confirm locally","captainNote":"Can get very crowded and loud in peak season — good for crew nights out, less so for a quiet guest dinner."},
{"category":"Marina","region":"Marmaris–Dalyan","name":"Netsel Marmaris Marina","coordinates":"36.85°N, 28.27°E","description":"Central full-service marina in Marmaris, adjacent to the old town bazaar and bar street.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel","Provisioning","Technical support","Customs"],"contact":"Confirm via seturmarinas.com","captainNote":"Common port of entry/exit and crew-change point for the Turkish southwest coast."},
{"category":"Marina","region":"Marmaris–Dalyan","name":"Martı Marina (Marmaris Bay)","coordinates":"36.80°N, 28.22°E","description":"Marina on the outer part of Marmaris Bay, a quieter alternative to Netsel.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via marina","captainNote":"—"},
{"category":"Marina","region":"Marmaris–Dalyan","name":"Albatros Marina, Marmaris","coordinates":"36.86°N, 28.25°E","description":"Marina option within the greater Marmaris area.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via marina","captainNote":"—"},
{"category":"Fuel Station","region":"Marmaris–Dalyan","name":"Marmaris Fuel Dock","coordinates":"36.85°N, 28.27°E","description":"Bunkering point within Netsel Marmaris Marina.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Marmaris–Dalyan","name":"Marmaris Liman Başkanlığı","coordinates":"36.85°N, 28.27°E","description":"Regional harbour master's office, a major port of entry for the southwest coast.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 252 412 10 13 (verify before relying on it)","captainNote":"One of the busiest check-in/out offices on the coast — allow time in July–August."},

// ---------- Göcek ----------
{"category":"Island","region":"Göcek","name":"Göcek's Twelve Islands (Yassıca, Domuz, Tersane group)","coordinates":"36.72°N, 28.90°E","description":"Cluster of small wooded islands and coves between Göcek and Fethiye, the classic multi-day 'blue cruise' anchorage ground.","highlights":["Sheltered coves","Snorkelling","Multi-day anchoring"],"vhf":"—","services":[],"contact":"—","captainNote":"Extremely popular in July–August; arrive early afternoon to secure swinging room in the best-known coves."},
{"category":"Historical Site","region":"Göcek","name":"Tersane (Cedar) Island","coordinates":"36.72°N, 28.87°E","description":"Island with the ruins of an old shipyard and an abandoned Greek village, reachable by tender from the anchorage.","highlights":["Ruins walk","Sheltered anchorage"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"One of the most sheltered overnight anchorages in the Göcek islands group."},
{"category":"Entertainment & Nightlife","region":"Göcek","name":"Göcek Village Promenade","coordinates":"36.75°N, 28.93°E","description":"Small, upscale marina village with restaurants and boutiques; quieter and more low-key than Marmaris or Bodrum.","highlights":["Fine dining","Boutique shopping"],"vhf":"—","services":["Restaurants","Bars","Boutiques"],"contact":"Confirm locally","captainNote":"Favoured by superyacht guests wanting a calmer evening ashore than Marmaris/Bodrum offer."},
{"category":"Marina","region":"Göcek","name":"D-Marin Göcek","coordinates":"36.75°N, 28.93°E","description":"Premium marina (~380 berths) with pools, family facilities and easy access to the Göcek islands.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Technical support"],"contact":"Confirm via d-marin.com","captainNote":"Popular guest embarkation point for Göcek-islands charters."},
{"category":"Marina","region":"Göcek","name":"Göcek Exclusive Marina / Setur Göcek Village Port","coordinates":"36.75°N, 28.93°E","description":"Additional marina capacity in Göcek village, part of the Setur network.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via seturmarinas.com","captainNote":"—"},
{"category":"Fuel Station","region":"Göcek","name":"Göcek Fuel Dock","coordinates":"36.75°N, 28.93°E","description":"Bunkering point at D-Marin Göcek.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Göcek","name":"Göcek Liman Başkanlığı","coordinates":"36.75°N, 28.93°E","description":"Harbour master's office for the Göcek area.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 252 645 24 94 (verify before relying on it)","captainNote":"—"},

// ---------- Fethiye–Ölüdeniz ----------
{"category":"Island","region":"Fethiye–Ölüdeniz","name":"Gemiler Island (St. Nicholas Island)","coordinates":"36.55°N, 29.13°E","description":"Small island with extensive Byzantine church and monastery ruins, a very popular sunset anchorage.","highlights":["Byzantine ruins","Sunset anchorage"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"One of the most photographed sunset spots on this stretch of coast — arrive with time to secure a good anchoring position."},
{"category":"Historical Site","region":"Fethiye–Ölüdeniz","name":"Kayaköy (Ghost Village)","coordinates":"36.56°N, 29.11°E","description":"Abandoned early-20th-century Greek Orthodox village of stone houses and churches on a hillside above Fethiye, preserved as an open-air museum.","highlights":["Abandoned village","Photography","History of 1923 population exchange"],"vhf":"Confirm locally","services":[],"contact":"Confirm locally","captainNote":"Reached by road excursion from Fethiye/Ölüdeniz — not a shoreline stop."},
{"category":"Historical Site","region":"Fethiye–Ölüdeniz","name":"Fethiye Lycian Rock Tombs (Tomb of Amyntas)","coordinates":"36.62°N, 29.12°E","description":"Monumental Lycian rock-cut tomb façades carved directly into the cliff overlooking Fethiye harbour.","highlights":["Lycian tombs","Harbour views"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Visible from the harbour and marina — an easy short walk from town."},
{"category":"Entertainment & Nightlife","region":"Fethiye–Ölüdeniz","name":"Ölüdeniz Blue Lagoon Beach Clubs","coordinates":"36.55°N, 29.12°E","description":"Turquoise lagoon beach beneath Babadağ mountain, popular for beach clubs, water sports and paragliding landings.","highlights":["Beach clubs","Paragliding","Water sports"],"vhf":"—","services":["Restaurants","Beach clubs"],"contact":"Confirm locally","captainNote":"The lagoon itself is a protected nature reserve with anchoring restrictions — check current rules before entering by tender."},
{"category":"Marina","region":"Fethiye–Ölüdeniz","name":"Ece Saray Marina, Fethiye","coordinates":"36.62°N, 29.12°E","description":"Full-service marina in Fethiye town centre, with its own fuel station.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel","Provisioning","Technical support"],"contact":"Confirm via marina","captainNote":"Sheltered natural bay — a good weather-bound refuge as well as a berthing option."},
{"category":"Fuel Station","region":"Fethiye–Ölüdeniz","name":"Ece Saray Marina Fuel Station","coordinates":"36.62°N, 29.12°E","description":"Fuel dock within Ece Saray Marina, Fethiye.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Fethiye–Ölüdeniz","name":"Fethiye Liman Başkanlığı","coordinates":"36.62°N, 29.12°E","description":"Regional harbour master's office covering Fethiye and the Göcek islands.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 252 614 11 87 (verify before relying on it)","captainNote":"—"},

// ---------- Kalkan–Kaş–Kekova ----------
{"category":"Island","region":"Kalkan–Kaş–Kekova","name":"Kekova Island & the Sunken City (Batık Şehir)","coordinates":"36.19°N, 29.85°E","description":"Protected area where earthquake-submerged Lycian ruins are visible beneath the clear water near Simena; swimming/anchoring directly over the ruins is restricted.","highlights":["Sunken ruins","Glass-bottom/boat viewing","Protected marine area"],"vhf":"—","services":[],"contact":"Confirm locally (protected area rules apply)","captainNote":"No swimming or anchoring is permitted directly over the sunken city — view by slow boat pass or from a permitted nearby anchorage."},
{"category":"Historical Site","region":"Kalkan–Kaş–Kekova","name":"Simena (Kaleköy) & Üçağız","coordinates":"36.19°N, 29.85°E","description":"Small village beneath a Byzantine castle hill dotted with Lycian sarcophagi; reached only by boat, alongside the neighbouring village of Üçağız.","highlights":["Lycian sarcophagi","Byzantine castle","Boat-only access"],"vhf":"—","services":["Small restaurants"],"contact":"Confirm locally","captainNote":"A highlight tender stop on any Kekova-area itinerary; no road access adds to its charm."},
{"category":"Historical Site","region":"Kalkan–Kaş–Kekova","name":"Patara","coordinates":"36.26°N, 29.32°E","description":"Ancient Lycian capital and the birthplace of St. Nicholas, fronted by an 18-km sand beach — the longest in Turkey.","highlights":["Longest beach in Turkey","Ancient Lycian capital","Roman arch and theatre"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"The beach is a protected loggerhead-turtle nesting site — respect seasonal access rules."},
{"category":"Entertainment & Nightlife","region":"Kalkan–Kaş–Kekova","name":"Kalkan Harbour Rooftop Restaurants","coordinates":"36.27°N, 29.42°E","description":"Whitewashed hillside town with upscale rooftop restaurants overlooking the small harbour.","highlights":["Fine dining","Harbour views"],"vhf":"—","services":["Restaurants","Bars"],"contact":"Confirm locally","captainNote":"Harbour is small and depth-limited — most yachts anchor off and tender guests in for dinner."},
{"category":"Entertainment & Nightlife","region":"Kalkan–Kaş–Kekova","name":"Kaş Town Square","coordinates":"36.20°N, 29.64°E","description":"Relaxed, diving-focused town with cafés and low-key bars around the small harbour and amphitheatre.","highlights":["Diving hub","Cafés","Small amphitheatre"],"vhf":"—","services":["Restaurants","Bars","Dive centres"],"contact":"Confirm locally","captainNote":"Popular with divers — good stop if guests want to try a wreck or reef dive."},
{"category":"Marina","region":"Kalkan–Kaş–Kekova","name":"Makmarin / Setur Kaş Marina","coordinates":"36.20°N, 29.64°E","description":"Marina serving Kaş town.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)"],"contact":"Confirm via seturmarinas.com","captainNote":"—"},
{"category":"Fuel Station","region":"Kalkan–Kaş–Kekova","name":"Kaş Fuel Dock","coordinates":"36.20°N, 29.64°E","description":"Bunkering point serving the Kaş marina area.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Kalkan–Kaş–Kekova","name":"Kaş / Kalkan Harbour Authority","coordinates":"36.20°N, 29.64°E","description":"Local harbour/port authority presence for the Kalkan–Kaş–Kekova area (administratively linked to the wider Fethiye/Antalya region).","highlights":[],"vhf":"Confirm locally","services":["Transit log"],"contact":"Confirm locally — exact office and phone number not verified","captainNote":"Confirm the current responsible office directly before relying on this for check-in/out."},

// ---------- Demre–Finike–Kemer (Olympos–Phaselis) ----------
{"category":"Historical Site","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Myra (Demre) & Church of St. Nicholas","coordinates":"36.25°N, 29.99°E","description":"Rock-cut Lycian tombs carved into a cliff above Demre, and the nearby Byzantine-era Church of St. Nicholas (the historical Santa Claus).","highlights":["Lycian rock tombs","Church of St. Nicholas"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Reached by road from Finike/Kaş — not a direct shoreline stop."},
{"category":"Historical Site","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Olympos & the Chimera (Yanartaş)","coordinates":"36.40°N, 30.47°E","description":"Ancient city ruins set in a forested river canyon behind Çıralı beach, near the Chimera — natural gas flames that have burned from the rock for millennia.","highlights":["Ancient ruins in forest","Eternal flames (Chimera)","Beach (Çıralı)"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"The Chimera flames are best visited after dark via a short uphill walk from Çıralı — worth an overnight anchorage to combine with the ruins by day."},
{"category":"Historical Site","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Phaselis","coordinates":"36.52°N, 30.55°E","description":"Ancient port city with three natural harbours set among pine forest, ideal for combining a swim stop with ruins accessible directly from the beach.","highlights":["Three ancient harbours","Beach + ruins combined"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"One of the few ancient sites reachable straight from a tender landing on the beach — good half-day stop."},
{"category":"Entertainment & Nightlife","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Kemer Marina Strip","coordinates":"36.60°N, 30.56°E","description":"Restaurant and bar strip along the Kemer marina waterfront.","highlights":["Waterfront dining","Bars"],"vhf":"—","services":["Restaurants","Bars"],"contact":"Confirm locally","captainNote":"—"},
{"category":"Marina","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Finike Marina (Setur)","coordinates":"36.30°N, 30.15°E","description":"Marina at Finike, a common weather-bound stop between the southwest coast and Antalya.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)"],"contact":"Confirm via seturmarinas.com","captainNote":"Useful shelter option if conditions turn rough rounding toward Antalya."},
{"category":"Marina","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Kemer Türkiz Marina","coordinates":"36.60°N, 30.56°E","description":"Marina at Kemer, close to Phaselis and the Antalya approaches.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power"],"contact":"Confirm via marina","captainNote":"—"},
{"category":"Fuel Station","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Finike / Kemer Fuel Docks","coordinates":"36.30°N, 30.15°E","description":"Bunkering points at Finike and Kemer marinas.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Demre–Finike–Kemer (Olympos–Phaselis)","name":"Kemer Liman Başkanlığı","coordinates":"36.60°N, 30.56°E","description":"Harbour master's office covering the Kemer/Finike stretch of coast.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 242 814 52 62 (verify before relying on it)","captainNote":"—"},

// ---------- Antalya (Kaleiçi–Aspendos–Side–Perge) ----------
{"category":"Historical Site","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Aspendos Roman Theatre","coordinates":"36.93°N, 31.17°E","description":"One of the best-preserved Roman theatres in the world, still used today for opera and ballet performances.","highlights":["Best-preserved Roman theatre","Live performances (seasonal)"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Check the seasonal performance calendar — an evening show here is a memorable guest excursion."},
{"category":"Historical Site","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Side (ancient city & Temple of Apollo)","coordinates":"36.77°N, 31.39°E","description":"Modern resort town built around extensive Roman ruins, including a harbour-front Temple of Apollo and a large amphitheatre.","highlights":["Temple of Apollo","Amphitheatre","Harbour ruins"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"The temple columns at the harbour point are especially striking at sunset."},
{"category":"Historical Site","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Perge","coordinates":"36.96°N, 30.85°E","description":"Well-preserved Hellenistic and Roman city with a stadium, theatre, colonnaded street and monumental gate.","highlights":["Roman stadium","Colonnaded street"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"Often combined with Aspendos as a full-day archaeological excursion from Antalya."},
{"category":"Historical Site","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Antalya Kaleiçi (Old Town)","coordinates":"36.885°N, 30.704°E","description":"Antalya's historic old town around the Roman harbour, with Hadrian's Gate, the Yivli (Fluted) Minaret and narrow Ottoman-era streets.","highlights":["Hadrian's Gate","Roman harbour","Old town streets"],"vhf":"—","services":["Restaurants","Bars","Boutique hotels"],"contact":"Confirm locally","captainNote":"The Roman harbour at the foot of Kaleiçi is itself a small marina — walkable from anchorage/berths."},
{"category":"Entertainment & Nightlife","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Kaleiçi Old Harbour Bars & Restaurants","coordinates":"36.885°N, 30.704°E","description":"Restaurants, rooftop bars and cafés packed into Kaleiçi's old-town lanes above the historic harbour.","highlights":["Rooftop bars","Waterfront dining"],"vhf":"—","services":["Restaurants","Bars"],"contact":"Confirm locally","captainNote":"—"},
{"category":"Marina","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Antalya Marina (Setur / Kaleiçi)","coordinates":"36.88°N, 30.70°E","description":"Marina serving Antalya, at the historic Roman harbour beneath Kaleiçi old town.","highlights":[],"vhf":"Confirm with marina","services":["Berths","Water","Shore power","Fuel (confirm)","Provisioning"],"contact":"Confirm via seturmarinas.com","captainNote":"Excellent base for the Aspendos/Side/Perge archaeological cluster."},
{"category":"Fuel Station","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Antalya Fuel Dock","coordinates":"36.88°N, 30.70°E","description":"Bunkering point within Antalya Marina.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Antalya (Kaleiçi–Aspendos–Side–Perge)","name":"Antalya Liman Başkanlığı","coordinates":"36.88°N, 30.70°E","description":"Regional harbour master's office for Antalya.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 242 259 09 90 (verify before relying on it)","captainNote":"—"},

// ---------- Alanya ----------
{"category":"Historical Site","region":"Alanya","name":"Alanya Castle & Kızıl Kule (Red Tower)","coordinates":"36.54°N, 31.99°E","description":"Seljuk-era hilltop castle with sweeping coastal views, and the iconic octagonal Red Tower guarding the old shipyard (Tersane) below.","highlights":["Seljuk castle","Red Tower","Old shipyard"],"vhf":"—","services":[],"contact":"Confirm locally","captainNote":"The castle headland and Damlataş Cave nearby make a good half-day shore excursion."},
{"category":"Entertainment & Nightlife","region":"Alanya","name":"Alanya Harbour Front & Cleopatra Beach Strip","coordinates":"36.54°N, 32.00°E","description":"Restaurants, bars and beach clubs along Alanya's harbour and the popular Cleopatra Beach.","highlights":["Beach clubs","Waterfront dining"],"vhf":"—","services":["Restaurants","Bars","Beach clubs"],"contact":"Confirm locally","captainNote":"—"},
{"category":"Marina","region":"Alanya","name":"Alanya Harbour/Marina","coordinates":"36.54°N, 32.00°E","description":"Harbour beneath Alanya castle, historically an Ottoman/Seljuk naval shipyard, now serving leisure and fishing craft.","highlights":[],"vhf":"Confirm locally","services":["Berths (limited)","Water"],"contact":"Confirm locally","captainNote":"Space and depth can be limited for larger yachts — confirm before planning to berth rather than anchor off."},
{"category":"Fuel Station","region":"Alanya","name":"Alanya Fuel Dock","coordinates":"36.54°N, 32.00°E","description":"Bunkering point serving Alanya harbour.","highlights":[],"vhf":"Confirm locally","services":["Diesel bunkering"],"contact":"Confirm via local yacht agent","captainNote":"—"},
{"category":"Harbour Master's Office","region":"Alanya","name":"Alanya Liman Başkanlığı","coordinates":"36.54°N, 32.00°E","description":"Harbour master's office for the Alanya area, the southeasternmost stop on this guide.","highlights":[],"vhf":"Confirm locally","services":["Transit log","Customs coordination"],"contact":"0 242 511 94 98 (verify before relying on it)","captainNote":"—"}

];

