const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const readCart=()=>{try{return JSON.parse(localStorage.getItem('atlas_store_cart')||'[]')}catch{return []}};
const writeCart=value=>localStorage.setItem('atlas_store_cart',JSON.stringify(value));
const tryPrice=value=>'₺'+Number(value).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
let activeCategory='';
function productsInCart(){return readCart().map(item=>({...item,product:STORE_DATA.find(product=>product.id===item.id)})).filter(item=>item.product)}
function renderCategories(){const categories=['Tümü',...new Set(STORE_DATA.map(product=>product.category))];$('storeCategories').innerHTML=categories.map(category=>`<button type="button" class="store-chip${(category==='Tümü'&&!activeCategory)||category===activeCategory?' active':''}" data-cat="${category==='Tümü'?'':esc(category)}">${esc(category)}</button>`).join('')}
function renderGrid(){const query=$('storeSearch').value.toLocaleLowerCase('tr-TR');const rows=STORE_DATA.filter(product=>(!activeCategory||product.category===activeCategory)&&(!query||JSON.stringify(product).toLocaleLowerCase('tr-TR').includes(query)));$('storeResultCount').textContent=`${rows.length} ürün gösteriliyor · Toplam ${STORE_DATA.length} ürün`;$('storeGrid').innerHTML=rows.length?rows.map(product=>`<article class="store-card">${product.badge?`<span class="store-badge-tag">${esc(product.badge)}</span>`:''}<div class="store-image-tile"><img src="${esc(product.image)}" alt="${esc(product.name)}" loading="lazy" referrerpolicy="no-referrer"></div><div class="store-card-category">${esc(product.category)}</div><h2>${esc(product.name)}</h2><p class="store-card-desc">${esc(product.description)}</p><div class="store-card-footer"><div class="store-price">${Number.isFinite(product.price)?tryPrice(product.price):'Güncel fiyat'}<small>${Number.isFinite(product.price)?'Siparişte teyit edilir':'Teklif ile bildirilir'}</small></div><button type="button" class="store-add-btn" data-id="${esc(product.id)}">${Number.isFinite(product.price)?'Sepete Ekle':'Teklif İste'}</button></div></article>`).join(''):'<p class="empty">Bu kategoride/aramada ürün bulunamadı.</p>';$('storeGrid').querySelectorAll('.store-add-btn').forEach(button=>button.addEventListener('click',()=>addToCart(button.dataset.id)))}
function addToCart(id){const cart=readCart(),line=cart.find(item=>item.id===id);if(line)line.qty+=1;else cart.push({id,qty:1});writeCart(cart);renderCart()}
function updateQuantity(id,delta){const cart=readCart(),line=cart.find(item=>item.id===id);if(!line)return;line.qty+=delta;writeCart(cart.filter(item=>item.qty>0));renderCart()}
function removeFromCart(id){writeCart(readCart().filter(item=>item.id!==id));renderCart()}
function renderCart(){const lines=productsInCart(),count=lines.reduce((sum,line)=>sum+line.qty,0),subtotal=lines.reduce((sum,line)=>sum+(Number.isFinite(line.product.price)?line.product.price*line.qty:0),0);$('storeCartCount').textContent=count;$('storeCartSubtotal').textContent=tryPrice(subtotal);$('storeCartItems').innerHTML=lines.length?lines.map(line=>`<div class="store-cart-item"><div class="store-cart-item-icon"><img src="${esc(line.product.image)}" alt=""></div><div><h3>${esc(line.product.name)}</h3><div class="store-qty-row"><button type="button" class="store-qty-btn" data-id="${esc(line.id)}" data-delta="-1">−</button><span>${line.qty}</span><button type="button" class="store-qty-btn" data-id="${esc(line.id)}" data-delta="1">+</button></div></div><div><div class="store-cart-item-price">${Number.isFinite(line.product.price)?tryPrice(line.product.price*line.qty):'Fiyat teyidi'}</div><button type="button" class="store-cart-remove" data-id="${esc(line.id)}">Kaldır</button></div></div>`).join(''):'<div class="store-cart-empty">Sepetiniz boş.<br>Mağazadan ürün ekleyin.</div>';$('storeCartItems').querySelectorAll('.store-qty-btn').forEach(button=>button.addEventListener('click',()=>updateQuantity(button.dataset.id,Number(button.dataset.delta))));$('storeCartItems').querySelectorAll('.store-cart-remove').forEach(button=>button.addEventListener('click',()=>removeFromCart(button.dataset.id)))}
function closeCart(){$('storeCartOverlay').classList.remove('open');$('storeCartDrawer').classList.remove('open')}
function orderText(){const lines=productsInCart(),subtotal=lines.reduce((sum,line)=>sum+(Number.isFinite(line.product.price)?line.product.price*line.qty:0),0),items=lines.map(line=>`• ${line.product.name} x${line.qty} — ${Number.isFinite(line.product.price)?tryPrice(line.product.price*line.qty):'Güncel fiyat teyidi'}`).join('\n');return `SİNBAD MARINE STORE — Sipariş / Teklif Talebi\n\nMüşteri: ${$('storeName').value.trim()||'—'}\nTelefon: ${$('storePhone').value.trim()||'—'}\nE-posta: ${$('storeEmail').value.trim()||'—'}\nTeslimat/Yat: ${$('storeDelivery').value.trim()||'—'}\n\nÜrünler:\n${items||'—'}\n\nFiyatı görünen ürünler toplamı: ${tryPrice(subtotal)}\nNot: ${$('storeNote').value.trim()||'—'}`}
function openCheckout(){if(!readCart().length)return;$('storeCheckoutSummary').textContent=orderText();$('storeCheckoutOverlay').classList.add('open')}
$('storeCategories').addEventListener('click',event=>{const button=event.target.closest('.store-chip');if(!button)return;activeCategory=button.dataset.cat;renderCategories();renderGrid()});
$('storeSearch').addEventListener('input',renderGrid);
$('storeCartFab').addEventListener('click',()=>{$('storeCartOverlay').classList.add('open');$('storeCartDrawer').classList.add('open')});
$('storeCartClose').addEventListener('click',closeCart);$('storeCartOverlay').addEventListener('click',closeCart);
$('storeCheckoutBtn').addEventListener('click',openCheckout);$('storeCheckoutClose').addEventListener('click',()=>$('storeCheckoutOverlay').classList.remove('open'));
$('storeSendWhatsapp').addEventListener('click',()=>window.open(`https://wa.me/?text=${encodeURIComponent(orderText())}`,'_blank','noopener'));
$('storeSendEmail').addEventListener('click',()=>window.open(`mailto:?subject=${encodeURIComponent('Sinbad Marine Store — Sipariş Talebi')}&body=${encodeURIComponent(orderText())}`,'_blank','noopener'));
$('storeBack').addEventListener('click',()=>history.length>1?history.back():window.close());
$('storeHome').addEventListener('click',()=>{if(window.opener&&!window.opener.closed){window.opener.focus();return}location.href='./index.html'});
$('storeClose').addEventListener('click',()=>window.close());
renderCategories();renderGrid();renderCart();
