const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8'),migration=fs.readFileSync('supabase/migrations/20260829_developer_owner_approval_workflow.sql','utf8');
test('developers can contribute Academy documents media drawings and tables',()=>{assert.match(html,/\.mp4,\.webm,\.mov/);assert.match(html,/\.csv,\.xls,\.xlsx/);assert.match(html,/\.svg/);assert.match(html,/value="sinbad-academy"/)});
test('developer review and Owner final approval are separate non-publishing stages',()=>{assert.match(app,/roleCanDeveloperReview/);assert.match(app,/roleCanOwnerFinalize/);assert.match(app,/developer-review-contribution/);assert.match(app,/owner-finalize-contribution/);assert.match(migration,/developer_review_status/);assert.match(migration,/owner_final_status/)});
test('design changes are plans routed to Owner and cannot directly publish',()=>{assert.match(html,/Send Plan to Owner/);assert.match(app,/design_change_proposals/);assert.match(app,/owner-review-design-plan/);assert.match(migration,/owner_approved/);assert.doesNotMatch(app,/functions\.invoke\('publish-design/)});
test('developer requests accept quarantined supporting files and notify the Owner dashboard',()=>{assert.match(html,/id="designPlanAttachments"/);assert.match(html,/id="ownerDeveloperMessageCount"/);assert.match(app,/attachment_submission_ids/);assert.match(app,/developer-change-request/);assert.match(migration,/attachment_submission_ids uuid\[\]/)});
test('dashboard modules use independent real browser windows with back and home navigation',()=>{assert.match(app,/openDashboardWorkspaceWindow/);assert.match(app,/popup=yes/);assert.match(app,/resizable=yes/);assert.match(app,/data-window-back/);assert.match(app,/data-window-home/);assert.match(html,/id="developerProjectCard"[^>]*data-role-hidden="true"/)});
test('answer-key reviews bind a hash and require separate developer and Owner decisions',()=>{assert.match(migration,/exam_answer_key_reviews/);assert.match(migration,/answer_key_hash/);assert.match(migration,/developer_decision/);assert.match(migration,/owner_final_decision/)});
test('answer-key material stays server-only behind an atomic two-person approval gate',()=>{assert.match(migration,/exam_answer_key_materials/);assert.match(migration,/revoke all on public\.exam_answer_key_materials from anon,authenticated/);assert.match(migration,/exam_developer_decide/);assert.match(migration,/exam_owner_finalize/)});
