'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const html=fs.readFileSync('exam-review.html','utf8'),js=fs.readFileSync('exam-review.js','utf8'),css=fs.readFileSync('exam-review.css','utf8');
test('package and legacy answer review coexist on the authenticated surface',()=>{for(const id of ['packageSurface','answerSurface','packageList','questionList','auditList','ownerReviewerPanel','manifestInput','importPackage','ownerFinal','acceptPackage','returnPackage'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/Teknik doğrulama ≠ Human Review ≠ Owner kabulü/);assert.match(html,/exam-review\.js/)});
test('question and evidence values use safe DOM text rendering',()=>{assert.match(js,/payload\.textContent=JSON\.stringify/);assert.match(js,/evidence\.textContent=JSON\.stringify/);assert.doesNotMatch(js,/innerHTML/)});
test('UI binds every write to fresh request version and assignment generation',()=>{assert.match(js,/requestId:crypto\.randomUUID\(\)/);assert.match(js,/assignmentGeneration:selectedPackage\.assignment_generation/);assert.match(js,/expectedLockVersion:selectedPackage\.lock_version/);assert.match(js,/güncel sürüm yükleniyor/)});
test('Owner controls use exact step-up descriptors',()=>{assert.match(js,/identity\.human_reviewer\.set_state/);assert.match(js,/identity\.human_review\.package_import/);assert.match(js,/identity\.human_review\.package_transfer/);assert.match(js,/identity\.human_review\.package_finalize/);assert.match(js,/owner_finalize_package/);assert.match(js,/ownerSecurity\.authorize/)});
test('human package and legacy answer roles cannot overwrite each other',()=>{assert.match(js,/humanRole/);assert.match(js,/answerRole/);assert.doesNotMatch(js,/currentRole/)});
test('review layout includes tablet and mobile breakpoints with touch-sized controls',()=>{assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/@media\(max-width:520px\)/);assert.match(css,/min-height:44px/)});
