const test=require('node:test');
const assert=require('node:assert/strict');
const integration=require('../sinbad-exam-intelligence.js');
const local=()=>({schemaVersion:'1.0.0',integrationMode:'LOCAL_SYNTHETIC',appUrl:'http://127.0.0.1:4192/',releaseAuthorized:false,learnerContextTransport:'AUTHENTICATED_BACKCHANNEL_ONLY'});

test('Academy connects to the separate local exam surface without trusting legacy content',()=>{const opened=[],bridge=integration.create(local(),{openWindow:(...args)=>{opened.push(args);return {};}});assert.deepEqual(bridge.publicStatus(),{configured:true,mode:'LOCAL_SYNTHETIC',releaseAuthorized:false,studentReleaseBlocked:true,legacyAcademyQuestionsTrusted:false,learnerContextTransport:'AUTHENTICATED_BACKCHANNEL_ONLY'});assert.equal(bridge.launch().opened,true);assert.equal(opened[0][0],'http://127.0.0.1:4192/');assert.equal(opened[0][0].includes('learner'),false);});
test('synthetic integration cannot authorize release or target a remote host',()=>{assert.throws(()=>integration.create({...local(),releaseAuthorized:true}),/SYNTHETIC_MODE_CANNOT_AUTHORIZE_RELEASE/);assert.throws(()=>integration.create({...local(),appUrl:'https://example.com/'}),/LOCAL_EXAM_INTEGRATION_REQUIRES_LOOPBACK/);});
test('controlled release requires HTTPS and authenticated backchannel identity',()=>{const release={...local(),integrationMode:'CONTROLLED_RELEASE',appUrl:'https://academy.sinbad.example/exams/',releaseAuthorized:true};assert.equal(integration.create(release,{openWindow:()=>({})}).publicStatus().studentReleaseBlocked,false);assert.throws(()=>integration.create({...release,appUrl:'http://academy.sinbad.example/'}),/CONTROLLED_RELEASE_REQUIRES_HTTPS/);assert.throws(()=>integration.create({...release,learnerContextTransport:'QUERY_STRING'}),/LEARNER_CONTEXT_TRANSPORT_INVALID/);});
test('handshake sends no learner context and accepts only the configured origin',()=>{let sent;const bridge=integration.create(local(),{openWindow:()=>({})});bridge.handshake({postMessage:(message,origin)=>{sent={message,origin};}});assert.equal(sent.origin,'http://127.0.0.1:4192');assert.equal(sent.message.learnerContext,null);assert.equal(bridge.acceptsMessage({origin:sent.origin,data:{version:1,type:'SINBAD_EXAM_INTELLIGENCE_READY'}}),true);assert.equal(bridge.acceptsMessage({origin:'https://evil.example',data:{version:1,type:'SINBAD_EXAM_INTELLIGENCE_READY'}}),false);});
test('hosted Academy never sends the browser to a loopback-only exam service',()=>{const opened=[];const bridge=integration.create(local(),{baseUrl:'https://sinbad-marine.github.io/atlas-marine-os/academy.html',openWindow:(...args)=>{opened.push(args);return {};}});const result=bridge.launch();assert.equal(result.safeFallback,true);assert.equal(opened[0][0],'https://sinbad-marine.github.io/atlas-marine-os/exam-intelligence-local-required.html');assert.equal(opened[0][0].includes('127.0.0.1'),false);});
