export const supportedLocales = ["tr", "en", "es"];

const copy = {
  tr: {
    locale: "tr-TR", language: "Türkçe", metaDescription: "SINBAD Marine Store — yat, tekne ve profesyonel gemi ekipmanları.",
    demo: "Demo katalog · ödeme kapalı", verificationPending: "Teknik veriler doğrulama bekliyor",
    homeLabel: "SINBAD Marine Store ana sayfa", openMenu: "Menüyü aç", mainMenu: "Ana menü", languageLabel: "Dil", productCategoriesLabel: "Ürün kategorileri", quickFindLabel: "Hızlı ürün bulma", supplierNoteLabel: "Tedarik ortağı notu", allCategories: "Tüm kategoriler⌄",
    navVessel: "Teknenize göre", navGuides: "Rehberler", navProfessional: "Profesyonel", navTrust: "Güven", searchLabel: "Ürün ara", cart: "Sepet",
    productFamilies: "ÜRÜN AİLELERİ", lifesaving: "Can kurtarma", lifesavingSmall: "Can yelekleri · ışıklar · işaretler", bridge: "Seyir & köprüüstü", bridgeSmall: "Harita masası · göstergeler · haberleşme", electrical: "Marin elektrik", electricalSmall: "12/24 V · aydınlatma · güç sistemleri",
    deckLife: "GÜVERTE & YAŞAM", deck: "Güverte donanımı", deckSmall: "Bağlama · oturma · paslanmaz ekipman", findVessel: "Teknenize göre bulun", findVesselSmall: "Yat · yelkenli · ticari gemi", buyingGuides: "Satın alma rehberleri", buyingGuidesSmall: "Doğru ürün, doğru ölçü, doğru belge",
    supplyDesk: "GEMİ TEDARİK MASASI", etaDelivery: "ETA’nıza göre limana teslim.", createQuote: "Teklif oluştur",
    expertSupport: "✓ Teknik uzman desteği", marinaDelivery: "⌖ Limana ve marinaya teslim", controlledData: "▣ Belge kontrollü ürün verisi", returns: "↻ Kolay iade altyapısı",
    heroImage: "Yüz metreden uzun yelkenli yat, yunuslar ve deniz yaşamını gösteren sanatsal deniz tablosu", heroEyebrow: "DENİZİN RUHU · TECRÜBENİN GÜVENİ", heroTitle: "Denize hazır.<br><em>Her ayrıntısıyla.</em>", heroText: "Yatınızdan ticari filonuza kadar; güvenlik, seyir ve teknik ekipmanı doğrulanabilir ürün bilgisiyle keşfedin.", explore: "Ürünleri keşfet", vesselQuote: "Gemi için teklif al", technicalEvidence: "Teknik kanıt", docsCompliance: "belge ve uyumluluk", b2cB2b: "B2C + B2B", storeSupply: "mağaza ve gemi tedarik",
    smartFinder: "AKILLI ÜRÜN BULUCU", whatLooking: "Tekneniz için ne arıyorsunuz?", searchPlaceholder: "Ürün, model veya kategori ara…", search: "Ara",
    knowVessel: "GEMİNİZİ TANIYALIM", compatibleTitle: "Ürün değil,<br><em>uyumlu çözüm</em> bulun.", compatibleText: "Tekne tipini ve sistemi seçin. SINBAD yalnızca ilgili ürün ailelerini, gerekli belgeleri ve doğrulama adımlarını öne çıkarsın.", vesselType: "Tekne / gemi tipi", motorYacht: "Motor yat", sailing: "Yelkenli", commercial: "Ticari gemi", workboat: "İş teknesi", systemWanted: "Aradığınız sistem", safetySystem: "Can kurtarma & güvenlik", bridgeSystem: "Seyir & köprüüstü", electricalSystem: "Elektrik & güç", deckSystem: "Güverte & yaşam", showCompatible: "Uyumlu ürünleri göster", finalCompatibility: "Son uyumluluk kararı ürün kodu ve gemi bilgisi doğrulandıktan sonra verilir.",
    safetyHeading: "CAN KURTARMA", safetyTitle: "Denizde güvenlik,<br>her şeyden önce.", openCategory: "Kategoriyi aç →", bridgeHeading: "SEYİR & KÖPRÜÜSTÜ", bridgeTitle: "Rotanız net,<br>köprünüz hazır.", supplyHeading: "GEMİ TEDARİK", supplyTitle: "Limana, marinaya<br>veya doğrudan gemiye.", createQuoteArrow: "Teklif oluştur →",
    selection: "SINBAD SEÇKİSİ · PROVİZYONEL KATALOG", selectedSea: "Deniz için seçildi", provisionalNote: "Demo katalog verileri tedarik ortağı kaynaklarından hazırlanmıştır. Satış öncesi stok, KDV, teknik özellik ve sertifika doğrulanır.", compare: "Karşılaştır", sortLabel: "Ürünleri sırala", featured: "Önerilen sıralama", priceLow: "Fiyat: düşükten yükseğe", priceHigh: "Fiyat: yüksekten düşüğe", empty: "Aramanızla eşleşen ürün bulunamadı.",
    guideEyebrow: "SINBAD DENİZ REHBERİ", knowBefore: "Satın almadan önce bilin", guideIntro: "Teknik ürünlerde güven, yalnızca markadan değil; doğru seçim, doğru kurulum ve doğrulanmış belgeden doğar.", guideSafety: "01 · GÜVENLİK", lifejacketGuide: "Can yeleği seçerken<br>yalnızca Newton değerine bakmayın.", lifejacketGuideText: "Kullanım bölgesi, beden, dönüş performansı ve sertifika birlikte değerlendirilir.", openGuide: "Rehberi ve ürünleri aç →", guideElectrical: "02 · ELEKTRİK", voltageTitle: "12 V mu, 24 V mu?", voltageText: "Gerilim, kablo kesiti ve koruma sınıfını aynı sistemde okuyun.", exploreSystem: "Sistemi keşfet →", guideBridge: "03 · SEYİR", bridgeChecklist: "Köprüüstü kontrol listesi", bridgeChecklistText: "Harita masasından haberleşmeye temel ekipman katmanları.", openList: "Listeyi aç →",
    proEyebrow: "SINBAD PRO · GEMİ TEDARİK MASASI", operationTitle: "Bir sepet değil.<br>Bir operasyon planı.", step1: "Gemi, IMO, liman ve ETA", step2: "Kalem bazlı teknik doğrulama", step3: "Teklif, stok ve teslimat planı", startProQuote: "Profesyonel teklif başlat", supplierPartner: "TEDARİK ORTAĞI", supplierText: "İlk ürün seçkisinin tedarik ve teknik doğrulama ortağı.",
    trustEyebrow: "GÜVENLİ TİCARET MİMARİSİ", trustTitle: "Ödeme güveni tasarımdan başlar", cardTitle: "Kart verisi tutulmaz", cardText: "Ödeme, PCI DSS uyumlu banka veya ödeme kuruluşunun barındırdığı güvenli sayfada tamamlanacak.", proofTitle: "Ürün kanıtı", proofText: "Sertifika, model ve teknik özellikler Owner doğrulamasından geçmeden kesin iddia olarak yayınlanmayacak.", engineTitle: "Ayrı ticaret motoru", engineText: "Sipariş ve müşteri verileri Academy ve SINBAD Core’dan teknik olarak ayrılmış tutulacak.", traceTitle: "İzlenebilir işlemler", traceText: "Stok, fiyat, sipariş ve yönetici değişiklikleri denetlenebilir olay kayıtlarıyla korunacak.",
    products: "Ürünler", security: "Güvenlik", corporateQuote: "Kurumsal teklif", footer: "© 2026 SINBAD Marine Store · Demo ticaret vitrini",
    cartLabel: "Sepet", shoppingCart: "ALIŞVERİŞ SEPETİ", selected: "Seçtikleriniz", closeCart: "Sepeti kapat", subtotal: "Ara toplam", checkoutSoon: "Güvenli ödeme — yakında", noCard: "Kart bilgisi alınmaz. Bu prototipte ödeme özellikle kapalıdır.", close: "Kapat",
    professionalSupply: "PROFESYONEL TEDARİK", quoteTitle: "Gemi için teklif oluştur", quoteIntro: "Bu demo formu bilgi toplamaz veya göndermez. Üretimde güvenli teklif servisine bağlanacaktır.", company: "Ad / Firma", email: "E-posta", vesselName: "Gemi / Yat adı", imo: "IMO numarası", port: "Liman", needs: "İhtiyaç listesi", needsPlaceholder: "Ürün, miktar ve teslimat notları…", prepareQuote: "Demo teklifi hazırla",
    sourceRecorded: "Kaynak kayıtlı", documentCheck: "Belge kontrolü", requestQuote: "Teklif alın", corporateSupply: "Kurumsal tedarik", demoPrice: "Demo fiyat", inspect: "İncele", getQuote: "Teklif al", addCart: "Sepete ekle", maxCompare: "Aynı anda en fazla 3 ürün karşılaştırılabilir.", quote: "Teklif", comparePrompt: "Karşılaştırmak için ürün kartlarından seçim yapın.", added: "sepete eklendi", removeCart: "Ürünü sepetten çıkar", emptyCart: "Sepetiniz henüz boş.<br>Deniz için doğru ekipmanı keşfedin.", technicalFeature: "Teknik özellik", documents: "Belgeler", compatibility: "Uyumluluk", dataSheet: "Teknik veri sayfası", pending: "Doğrulama bekliyor", certificate: "Sertifika / uygunluk", ownerReview: "Owner kontrolü", installGuide: "Kurulum kılavuzu", supplierSource: "Tedarikçi kaynağı", vesselKind: "Gemi tipi", voltageSize: "Gerilim / ölçü", mounting: "Montaj alanı", region: "Sertifika bölgesi", fitText: "Kesin uyumluluk gemi ve ürün kodu birlikte doğrulanınca yayınlanır.", provisionalRecord: "Bu prototip kaydı provizyoneldir. Ürün kodu, stok, fiyat, sertifika ve teknik değerler SDM tarafından doğrulandıktan sonra satışa açılır.", requestQuoteAction: "Teklif iste", technicalCompare: "TEKNİK KARŞILAŞTIRMA", chosenProducts: "Seçtiğiniz ürünler", closeCompare: "Karşılaştırmayı kapat", familyOpened: "için ilgili ürün ailesi açıldı.", checkoutDisabled: "Demo güvenliği: banka entegrasyonu gelene kadar ödeme kapalı.", quotePrepared: "Demo teklif hazırlandı; hiçbir bilgi gönderilmedi.",
    categories: { all: "Tüm Ürünler", safety: "Can Kurtarma", bridge: "Seyir & Köprüüstü", electrical: "Marin Elektrik", deck: "Güverte", professional: "Profesyonel Tedarik" }
  },
  en: {
    locale: "en-US", language: "English", metaDescription: "SINBAD Marine Store — equipment for yachts, boats and professional vessels.", demo: "Demo catalogue · checkout disabled", verificationPending: "Technical data awaiting verification", homeLabel: "SINBAD Marine Store home", openMenu: "Open menu", mainMenu: "Main menu", languageLabel: "Language", productCategoriesLabel: "Product categories", quickFindLabel: "Quick product finder", supplierNoteLabel: "Supply partner note", allCategories: "All categories⌄", navVessel: "By vessel", navGuides: "Guides", navProfessional: "Professional", navTrust: "Trust", searchLabel: "Search products", cart: "Cart",
    productFamilies: "PRODUCT FAMILIES", lifesaving: "Life-saving", lifesavingSmall: "Lifejackets · lights · signals", bridge: "Navigation & bridge", bridgeSmall: "Chart table · instruments · communications", electrical: "Marine electrical", electricalSmall: "12/24 V · lighting · power systems", deckLife: "DECK & LIVING", deck: "Deck equipment", deckSmall: "Mooring · seating · stainless hardware", findVessel: "Find by vessel", findVesselSmall: "Yacht · sailing boat · commercial vessel", buyingGuides: "Buying guides", buyingGuidesSmall: "The right product, size and document", supplyDesk: "VESSEL SUPPLY DESK", etaDelivery: "Delivered to port for your ETA.", createQuote: "Create quote", expertSupport: "✓ Technical expert support", marinaDelivery: "⌖ Port and marina delivery", controlledData: "▣ Document-controlled product data", returns: "↻ Easy-return infrastructure",
    heroImage: "Artistic seascape showing a sailing yacht over one hundred metres long, dolphins and marine life", heroEyebrow: "SPIRIT OF THE SEA · TRUST OF EXPERIENCE", heroTitle: "Ready for sea.<br><em>Down to every detail.</em>", heroText: "From your yacht to your commercial fleet, discover safety, navigation and technical equipment backed by verifiable product information.", explore: "Explore products", vesselQuote: "Get a vessel quote", technicalEvidence: "Technical evidence", docsCompliance: "documents and compliance", b2cB2b: "B2C + B2B", storeSupply: "store and vessel supply", smartFinder: "SMART PRODUCT FINDER", whatLooking: "What are you looking for on your vessel?", searchPlaceholder: "Search product, model or category…", search: "Search",
    knowVessel: "TELL US ABOUT YOUR VESSEL", compatibleTitle: "Find a compatible solution,<br><em>not just a product.</em>", compatibleText: "Select the vessel type and system. SINBAD will highlight only the relevant product families, required documents and verification steps.", vesselType: "Vessel type", motorYacht: "Motor yacht", sailing: "Sailing boat", commercial: "Commercial vessel", workboat: "Workboat", systemWanted: "System required", safetySystem: "Life-saving & safety", bridgeSystem: "Navigation & bridge", electricalSystem: "Electrical & power", deckSystem: "Deck & living", showCompatible: "Show compatible products", finalCompatibility: "Final compatibility is confirmed only after the product code and vessel details have been verified.",
    safetyHeading: "LIFE-SAVING", safetyTitle: "Safety at sea<br>comes first.", openCategory: "Open category →", bridgeHeading: "NAVIGATION & BRIDGE", bridgeTitle: "A clear route.<br>A prepared bridge.", supplyHeading: "VESSEL SUPPLY", supplyTitle: "To port, marina<br>or directly to the vessel.", createQuoteArrow: "Create quote →", selection: "SINBAD SELECTION · PROVISIONAL CATALOGUE", selectedSea: "Selected for the sea", provisionalNote: "Demo catalogue data is prepared from supply-partner sources. Stock, tax, technical specifications and certification are verified before sale.", compare: "Compare", sortLabel: "Sort products", featured: "Recommended", priceLow: "Price: low to high", priceHigh: "Price: high to low", empty: "No products match your search.",
    guideEyebrow: "SINBAD MARINE GUIDE", knowBefore: "Know before you buy", guideIntro: "Trust in technical products comes not only from the brand, but from correct selection, installation and verified documentation.", guideSafety: "01 · SAFETY", lifejacketGuide: "When choosing a lifejacket,<br>do not consider Newton rating alone.", lifejacketGuideText: "Operating area, size, turning performance and certification must be assessed together.", openGuide: "Open guide and products →", guideElectrical: "02 · ELECTRICAL", voltageTitle: "12 V or 24 V?", voltageText: "Evaluate voltage, cable cross-section and protection class as one system.", exploreSystem: "Explore system →", guideBridge: "03 · NAVIGATION", bridgeChecklist: "Bridge checklist", bridgeChecklistText: "Essential equipment layers from chart table to communications.", openList: "Open list →",
    proEyebrow: "SINBAD PRO · VESSEL SUPPLY DESK", operationTitle: "Not a cart.<br>An operations plan.", step1: "Vessel, IMO, port and ETA", step2: "Line-by-line technical verification", step3: "Quotation, stock and delivery plan", startProQuote: "Start professional quote", supplierPartner: "SUPPLY PARTNER", supplierText: "Supply and technical-verification partner for the initial product selection.", trustEyebrow: "SECURE COMMERCE ARCHITECTURE", trustTitle: "Payment trust begins with design", cardTitle: "Card data is not stored", cardText: "Payment will be completed on a secure page hosted by a PCI DSS-compliant bank or payment provider.", proofTitle: "Product evidence", proofText: "Certificates, models and technical specifications will not be published as definitive claims before Owner verification.", engineTitle: "Separate commerce engine", engineText: "Order and customer data will remain technically separated from Academy and SINBAD Core.", traceTitle: "Traceable operations", traceText: "Stock, price, order and administrator changes will be protected by auditable event records.", products: "Products", security: "Security", corporateQuote: "Corporate quote", footer: "© 2026 SINBAD Marine Store · Demo commerce showcase",
    cartLabel: "Cart", shoppingCart: "SHOPPING CART", selected: "Your selection", closeCart: "Close cart", subtotal: "Subtotal", checkoutSoon: "Secure checkout — coming soon", noCard: "No card data is collected. Checkout is deliberately disabled in this prototype.", close: "Close", professionalSupply: "PROFESSIONAL SUPPLY", quoteTitle: "Create a vessel quote", quoteIntro: "This demo form does not collect or send information. It will connect to the secure quotation service in production.", company: "Name / Company", email: "Email", vesselName: "Vessel / Yacht name", imo: "IMO number", port: "Port", needs: "Requirements", needsPlaceholder: "Products, quantities and delivery notes…", prepareQuote: "Prepare demo quote",
    sourceRecorded: "Source recorded", documentCheck: "Document check", requestQuote: "Request quote", corporateSupply: "Corporate supply", demoPrice: "Demo price", inspect: "View", getQuote: "Get quote", addCart: "Add to cart", maxCompare: "You can compare up to 3 products at once.", quote: "Quote", comparePrompt: "Select products from the product cards to compare them.", added: "added to cart", removeCart: "Remove product from cart", emptyCart: "Your cart is empty.<br>Discover the right equipment for the sea.", technicalFeature: "Technical specifications", documents: "Documents", compatibility: "Compatibility", dataSheet: "Technical data sheet", pending: "Awaiting verification", certificate: "Certificate / conformity", ownerReview: "Owner review", installGuide: "Installation guide", supplierSource: "Supplier source", vesselKind: "Vessel type", voltageSize: "Voltage / size", mounting: "Installation area", region: "Certification region", fitText: "Final compatibility is published only after the vessel and product code are verified together.", provisionalRecord: "This prototype record is provisional. Product code, stock, price, certificates and technical values must be verified by SDM before sale.", requestQuoteAction: "Request quote", technicalCompare: "TECHNICAL COMPARISON", chosenProducts: "Selected products", closeCompare: "Close comparison", familyOpened: "relevant product family opened.", checkoutDisabled: "Demo security: checkout remains disabled until bank integration is available.", quotePrepared: "Demo quote prepared; no information was sent.", categories: { all: "All Products", safety: "Life-Saving", bridge: "Navigation & Bridge", electrical: "Marine Electrical", deck: "Deck", professional: "Professional Supply" }
  },
  es: {
    locale: "es-ES", language: "Español", metaDescription: "SINBAD Marine Store — equipos para yates, embarcaciones y buques profesionales.", demo: "Catálogo de demostración · pago desactivado", verificationPending: "Datos técnicos pendientes de verificación", homeLabel: "Inicio de SINBAD Marine Store", openMenu: "Abrir menú", mainMenu: "Menú principal", languageLabel: "Idioma", productCategoriesLabel: "Categorías de productos", quickFindLabel: "Buscador rápido de productos", supplierNoteLabel: "Nota del socio de suministro", allCategories: "Todas las categorías⌄", navVessel: "Por embarcación", navGuides: "Guías", navProfessional: "Profesional", navTrust: "Confianza", searchLabel: "Buscar productos", cart: "Carrito",
    productFamilies: "FAMILIAS DE PRODUCTOS", lifesaving: "Salvamento", lifesavingSmall: "Chalecos · luces · señales", bridge: "Navegación y puente", bridgeSmall: "Mesa de cartas · instrumentos · comunicaciones", electrical: "Electricidad marina", electricalSmall: "12/24 V · iluminación · sistemas de potencia", deckLife: "CUBIERTA Y HABITABILIDAD", deck: "Equipo de cubierta", deckSmall: "Amarre · asientos · herrajes inoxidables", findVessel: "Buscar por embarcación", findVesselSmall: "Yate · velero · buque mercante", buyingGuides: "Guías de compra", buyingGuidesSmall: "Producto, medida y documento correctos", supplyDesk: "MESA DE SUMINISTRO NAVAL", etaDelivery: "Entrega en puerto según su ETA.", createQuote: "Crear presupuesto", expertSupport: "✓ Asistencia técnica especializada", marinaDelivery: "⌖ Entrega en puerto y marina", controlledData: "▣ Datos de producto controlados", returns: "↻ Infraestructura de devolución sencilla",
    heroImage: "Paisaje marino artístico con un velero de más de cien metros, delfines y vida marina", heroEyebrow: "ESPÍRITU DEL MAR · CONFIANZA DE LA EXPERIENCIA", heroTitle: "Listo para navegar.<br><em>Hasta el último detalle.</em>", heroText: "Desde su yate hasta su flota comercial, descubra equipos de seguridad, navegación y técnicos con información de producto verificable.", explore: "Explorar productos", vesselQuote: "Solicitar presupuesto naval", technicalEvidence: "Evidencia técnica", docsCompliance: "documentos y conformidad", b2cB2b: "B2C + B2B", storeSupply: "tienda y suministro naval", smartFinder: "BUSCADOR INTELIGENTE", whatLooking: "¿Qué busca para su embarcación?", searchPlaceholder: "Buscar producto, modelo o categoría…", search: "Buscar",
    knowVessel: "CONOZCAMOS SU EMBARCACIÓN", compatibleTitle: "Encuentre una solución compatible,<br><em>no solo un producto.</em>", compatibleText: "Seleccione el tipo de embarcación y el sistema. SINBAD destacará únicamente las familias, documentos y pasos de verificación pertinentes.", vesselType: "Tipo de embarcación", motorYacht: "Yate a motor", sailing: "Velero", commercial: "Buque mercante", workboat: "Embarcación de trabajo", systemWanted: "Sistema requerido", safetySystem: "Salvamento y seguridad", bridgeSystem: "Navegación y puente", electricalSystem: "Electricidad y potencia", deckSystem: "Cubierta y habitabilidad", showCompatible: "Mostrar productos compatibles", finalCompatibility: "La compatibilidad definitiva se confirma tras verificar el código del producto y los datos del buque.",
    safetyHeading: "SALVAMENTO", safetyTitle: "La seguridad en el mar<br>es lo primero.", openCategory: "Abrir categoría →", bridgeHeading: "NAVEGACIÓN Y PUENTE", bridgeTitle: "Ruta clara.<br>Puente preparado.", supplyHeading: "SUMINISTRO NAVAL", supplyTitle: "Al puerto, la marina<br>o directamente al buque.", createQuoteArrow: "Crear presupuesto →", selection: "SELECCIÓN SINBAD · CATÁLOGO PROVISIONAL", selectedSea: "Seleccionado para el mar", provisionalNote: "Los datos del catálogo demo proceden de socios de suministro. Existencias, impuestos, especificaciones y certificados se verifican antes de la venta.", compare: "Comparar", sortLabel: "Ordenar productos", featured: "Recomendados", priceLow: "Precio: menor a mayor", priceHigh: "Precio: mayor a menor", empty: "No se encontraron productos para su búsqueda.",
    guideEyebrow: "GUÍA MARÍTIMA SINBAD", knowBefore: "Infórmese antes de comprar", guideIntro: "La confianza en productos técnicos nace de la selección, instalación y documentación verificadas, no solo de la marca.", guideSafety: "01 · SEGURIDAD", lifejacketGuide: "Al elegir un chaleco salvavidas,<br>no considere solo los Newton.", lifejacketGuideText: "Zona de uso, talla, capacidad de volteo y certificación deben evaluarse conjuntamente.", openGuide: "Abrir guía y productos →", guideElectrical: "02 · ELECTRICIDAD", voltageTitle: "¿12 V o 24 V?", voltageText: "Evalúe tensión, sección del cable y clase de protección como un solo sistema.", exploreSystem: "Explorar sistema →", guideBridge: "03 · NAVEGACIÓN", bridgeChecklist: "Lista de control del puente", bridgeChecklistText: "Capas esenciales de equipamiento, desde la mesa de cartas hasta las comunicaciones.", openList: "Abrir lista →",
    proEyebrow: "SINBAD PRO · MESA DE SUMINISTRO NAVAL", operationTitle: "No es un carrito.<br>Es un plan de operaciones.", step1: "Buque, IMO, puerto y ETA", step2: "Verificación técnica por partida", step3: "Presupuesto, existencias y entrega", startProQuote: "Iniciar presupuesto profesional", supplierPartner: "SOCIO DE SUMINISTRO", supplierText: "Socio de suministro y verificación técnica de la selección inicial.", trustEyebrow: "ARQUITECTURA DE COMERCIO SEGURO", trustTitle: "La confianza en el pago empieza en el diseño", cardTitle: "No se almacenan datos de tarjeta", cardText: "El pago se completará en una página segura alojada por un banco o proveedor conforme a PCI DSS.", proofTitle: "Evidencia del producto", proofText: "Certificados, modelos y datos técnicos no se publicarán como afirmaciones definitivas sin revisión del Owner.", engineTitle: "Motor comercial separado", engineText: "Los datos de pedidos y clientes permanecerán técnicamente separados de Academy y SINBAD Core.", traceTitle: "Operaciones trazables", traceText: "Cambios de existencias, precios, pedidos y administradores quedarán protegidos mediante registros auditables.", products: "Productos", security: "Seguridad", corporateQuote: "Presupuesto corporativo", footer: "© 2026 SINBAD Marine Store · Escaparate comercial de demostración",
    cartLabel: "Carrito", shoppingCart: "CARRITO DE COMPRA", selected: "Su selección", closeCart: "Cerrar carrito", subtotal: "Subtotal", checkoutSoon: "Pago seguro — próximamente", noCard: "No se recopilan datos de tarjeta. El pago está desactivado deliberadamente en este prototipo.", close: "Cerrar", professionalSupply: "SUMINISTRO PROFESIONAL", quoteTitle: "Crear presupuesto naval", quoteIntro: "Este formulario demo no recopila ni envía información. En producción se conectará al servicio seguro de presupuestos.", company: "Nombre / Empresa", email: "Correo electrónico", vesselName: "Nombre del buque / yate", imo: "Número IMO", port: "Puerto", needs: "Lista de necesidades", needsPlaceholder: "Productos, cantidades y notas de entrega…", prepareQuote: "Preparar presupuesto demo",
    sourceRecorded: "Fuente registrada", documentCheck: "Control documental", requestQuote: "Solicitar presupuesto", corporateSupply: "Suministro corporativo", demoPrice: "Precio demo", inspect: "Ver", getQuote: "Presupuesto", addCart: "Añadir al carrito", maxCompare: "Puede comparar hasta 3 productos a la vez.", quote: "Presupuesto", comparePrompt: "Seleccione productos en las tarjetas para compararlos.", added: "añadido al carrito", removeCart: "Quitar producto del carrito", emptyCart: "Su carrito está vacío.<br>Descubra el equipo adecuado para el mar.", technicalFeature: "Especificaciones técnicas", documents: "Documentos", compatibility: "Compatibilidad", dataSheet: "Ficha técnica", pending: "Pendiente de verificación", certificate: "Certificado / conformidad", ownerReview: "Revisión del Owner", installGuide: "Manual de instalación", supplierSource: "Fuente del proveedor", vesselKind: "Tipo de buque", voltageSize: "Tensión / medida", mounting: "Zona de montaje", region: "Región de certificación", fitText: "La compatibilidad definitiva se publica tras verificar conjuntamente el buque y el código del producto.", provisionalRecord: "Este registro de prototipo es provisional. SDM debe verificar código, existencias, precio, certificados y valores técnicos antes de la venta.", requestQuoteAction: "Solicitar presupuesto", technicalCompare: "COMPARACIÓN TÉCNICA", chosenProducts: "Productos seleccionados", closeCompare: "Cerrar comparación", familyOpened: "familia de productos pertinente abierta.", checkoutDisabled: "Seguridad demo: el pago seguirá desactivado hasta integrar el banco.", quotePrepared: "Presupuesto demo preparado; no se envió información.", categories: { all: "Todos los productos", safety: "Salvamento", bridge: "Navegación y Puente", electrical: "Electricidad Marina", deck: "Cubierta", professional: "Suministro Profesional" }
  }
};

const productCopy = {
  en: {
    "sdm-lifejacket-light": ["SDM Lifejacket Light", "Emergency visibility light", "To be verified with supplier", "Certification document pending", "Battery/activation type to be verified"],
    "lifejacket-100n": ["100N Lifejacket", "For coastal and sheltered waters", "To be verified with supplier", "Size and buoyancy capacity to be verified", "Conformity document pending"],
    "lifejacket-solas": ["Lifejacket — SOLAS Listed", "Available after document verification", "Sales disabled · document review", "MED/SOLAS certificate required", "Model and size details pending"],
    "parallel-ruler": ["Parallel Ruler", "Chart-table navigation instrument", "To be verified with supplier", "Dimensions and material pending", "Bridge equipment"],
    "chrome-divider": ["Chrome Dividers", "Professional chart-working dividers", "To be verified with supplier", "Chrome body", "Length to be verified"],
    "horn-24v": ["24V Marine Trumpet Horn", "Sound-signalling device for boats and yachts", "To be verified with supplier", "24 V DC", "dB and type-approval details pending"],
    "clinometer": ["Clinometer", "Bridge heel indicator", "To be verified with supplier", "Measurement range to be verified", "Mounting dimensions pending"],
    "captain-chair": ["Captain's Chair", "For yacht and professional use", "Request quote and stock", "Upholstery options to be verified", "Pedestal inclusion pending"],
    "ship-supply": ["Vessel Stores Supply", "Bulk delivery to port or vessel", "Quotation only", "Vessel/IMO and port details", "ETA-based supply plan"]
  },
  es: {
    "sdm-lifejacket-light": ["Luz SDM para chaleco salvavidas", "Luz de visibilidad de emergencia", "Por verificar con el proveedor", "Certificado pendiente", "Tipo de batería/activación por verificar"],
    "lifejacket-100n": ["Chaleco salvavidas 100N", "Para aguas costeras y protegidas", "Por verificar con el proveedor", "Talla y capacidad de flotación por verificar", "Documento de conformidad pendiente"],
    "lifejacket-solas": ["Chaleco salvavidas — listado SOLAS", "Disponible tras verificar documentos", "Venta desactivada · revisión documental", "Certificado MED/SOLAS obligatorio", "Modelo y talla pendientes"],
    "parallel-ruler": ["Regla paralela", "Instrumento de navegación para mesa de cartas", "Por verificar con el proveedor", "Medidas y material pendientes", "Equipo de puente"],
    "chrome-divider": ["Compás de puntas cromado", "Compás profesional para cartas", "Por verificar con el proveedor", "Cuerpo cromado", "Longitud por verificar"],
    "horn-24v": ["Bocina marina tubular 24V", "Dispositivo de señal acústica para barcos y yates", "Por verificar con el proveedor", "24 V CC", "dB y homologación pendientes"],
    "clinometer": ["Clinómetro", "Indicador de escora del puente", "Por verificar con el proveedor", "Rango de medición por verificar", "Medidas de montaje pendientes"],
    "captain-chair": ["Sillón de capitán", "Para uso en yates y profesional", "Solicite precio y existencias", "Tapicería por verificar", "Inclusión del pedestal pendiente"],
    "ship-supply": ["Suministro de pertrechos navales", "Entrega a granel en puerto o buque", "Solo presupuesto", "Datos de buque/IMO y puerto", "Plan de suministro basado en ETA"]
  }
};

const productVisualCopy = {
  en: { "parallel-ruler": { badge: "NAV" }, "chrome-divider": { badge: "NAV" }, "captain-chair": { badge: "YACHT" } },
  es: { "sdm-lifejacket-light": { art: "LUZ" }, "parallel-ruler": { badge: "NAV" }, "chrome-divider": { badge: "NAV" }, "clinometer": { badge: "PUENTE" }, "captain-chair": { badge: "YATE", art: "ASIENTO" } }
};

export function normalizeLocale(value) { return supportedLocales.includes(value) ? value : "tr"; }
export function dictionary(locale) { return copy[normalizeLocale(locale)]; }
export function localizeProduct(product, locale) {
  if (!product) return null;
  const values = productCopy[normalizeLocale(locale)]?.[product.id];
  if (!values) return product;
  return { ...product, ...productVisualCopy[normalizeLocale(locale)]?.[product.id], name: values[0], subtitle: values[1], stock: values[2], spec: values.slice(3) };
}
