'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const sensors=require('../argos-readonly-sensors');
const clock=()=>new Date('2026-09-01T10:00:00.000Z');
const COMMIT='a'.repeat(40);const ok=async()=>({ok:true,status:200,json:async()=>({sha:COMMIT,state:'success',total_count:3})});

test('Bridge sensor permits only loopback allowlisted GET health endpoints',async()=>{let call;const fetch=async(...args)=>(call=args,{ok:true,status:200});const observation=await sensors.probeBridge({url:'http://127.0.0.1:31983/ai/status',fetch,clock});assert.equal(observation.state,'HEALTHY');assert.equal(call[1].method,'GET');assert.equal(call[1].redirect,'error');});
test('Bridge sensor blocks non-loopback and mutating-looking targets before fetch',async()=>{let calls=0;for(const url of ['https://example.com/ai/status','http://127.0.0.1:31983/ai/chat']){const observation=await sensors.probeBridge({url,fetch:async()=>{calls++;return {ok:true,status:200};},clock});assert.equal(observation.state,'UNKNOWN');assert.equal(observation.reasonCode,'BRIDGE_TARGET_NOT_ALLOWLISTED');}assert.equal(calls,0);});
test('GitHub sensor authenticates one exact read-only commit-status request and validates evidence',async()=>{let call;const token='g'.repeat(40),observation=await sensors.probeGitHub({owner:'sinbad-marine',repo:'sinbad-marine.github.io',ref:COMMIT,token,fetch:async(...args)=>(call=args,ok()),clock});assert.equal(observation.state,'HEALTHY');assert.equal(call[0],`https://api.github.com/repos/sinbad-marine/sinbad-marine.github.io/commits/${COMMIT}/status`);assert.equal(call[1].method,'GET');assert.equal(call[1].headers.Authorization,`Bearer ${token}`);assert.equal(JSON.stringify(observation).includes(token),false);});
test('GitHub sensor rejects mismatched commit evidence and never records credentials',async()=>{const token='t'.repeat(40),observation=await sensors.probeGitHub({owner:'owner',repo:'repo',ref:'b'.repeat(40),token,fetch:ok,clock});assert.equal(observation.state,'DEGRADED');assert.equal(observation.reasonCode,'GITHUB_EVIDENCE_INVALID');assert.equal(JSON.stringify(observation).includes(token),false);});
test('GitHub sensor rejects traversal-like refs without network access',async()=>{let calls=0;const observation=await sensors.probeGitHub({owner:'owner',repo:'repo',ref:'../main',fetch:async()=>{calls++;return ok();},clock});assert.equal(observation.state,'UNKNOWN');assert.equal(calls,0);});
test('Supabase sensor accepts only HTTPS project health endpoint and sends no credentials',async()=>{let call;const observation=await sensors.probeSupabase({baseUrl:'https://abc-123.supabase.co/',fetch:async(...args)=>(call=args,{ok:true,status:200}),clock});assert.equal(observation.state,'HEALTHY');assert.equal(call[0],'https://abc-123.supabase.co/auth/v1/health');assert.deepEqual(call[1].headers,{Accept:'application/json'});assert.equal(call[1].method,'GET');});
test('Supabase sensor blocks arbitrary hosts and data endpoints before fetch',async()=>{let calls=0;for(const input of [{baseUrl:'https://evil.example/'},{baseUrl:'https://abc.supabase.co/',path:'/rest/v1/workspace_members'}]){const observation=await sensors.probeSupabase({...input,fetch:async()=>{calls++;return ok();},clock});assert.equal(observation.state,'UNKNOWN');assert.equal(observation.reasonCode,'SUPABASE_TARGET_INVALID');}assert.equal(calls,0);});
test('sensor failures become bounded unavailable evidence without response bodies or secrets',async()=>{const observation=await sensors.probeBridge({url:'http://localhost:31983/studio/status',fetch:async()=>{throw new Error('token=do-not-leak');},clock});assert.equal(observation.state,'UNAVAILABLE');assert.equal(observation.reasonCode,'BRIDGE_UNAVAILABLE');assert.match(observation.evidenceHash,/^[a-f0-9]{64}$/u);assert.equal(JSON.stringify(observation).includes('do-not-leak'),false);});
