'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const health=require('../argos-health-contracts');const shelfApi=require('../argos-event-shelf');const supervisor=require('../argos-supervisor');
const NOW='2026-09-01T10:00:00.000Z',LATER='2026-09-01T10:05:00.000Z',H='a'.repeat(64);
function observation(component,state='HEALTHY'){return health.observe({component,state,observedAt:NOW,validUntil:LATER,reasonCode:state==='HEALTHY'?null:'TEST_FAILURE',evidenceHash:H});}
function run(t,observations){const root=fs.mkdtempSync(path.join(os.tmpdir(),'argos-supervisor-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return supervisor.supervise({runId:'run-1',now:NOW,observations,agentEnvelopeHash:H,shelf:shelfApi.create({root,shelfId:'health',maxEvents:20})});}
test('records every component assessment as content-free append-only evidence',t=>{const result=run(t,health.COMPONENTS.map(x=>observation(x)));assert.equal(result.status,'ARGOS_SUPERVISION_RECORDED');assert.equal(result.events.length,7);assert.equal(result.proposals.length,0);assert.ok(result.events.every(x=>!Object.hasOwn(x,'payload')));});
test('critical failure creates only a quarantined non-applicable repair proposal',t=>{const observations=health.COMPONENTS.map(x=>observation(x,x==='TEST_SUITE'?'DEGRADED':'HEALTHY'));const result=run(t,observations);assert.equal(result.status,'ARGOS_INCIDENTS_QUARANTINED');assert.equal(result.proposals.length,1);assert.equal(result.proposals[0].status,'ARGOS_REPAIR_QUARANTINED');assert.equal(result.proposals[0].mayApply,false);assert.equal(Object.hasOwn(result.proposals[0],'patch'),false);});
test('optional component degradation is recorded without fabricating a repair',t=>{const observations=health.COMPONENTS.map(x=>observation(x,x==='SUPABASE'?'UNAVAILABLE':'HEALTHY'));const result=run(t,observations);assert.equal(result.status,'ARGOS_SUPERVISION_RECORDED');assert.equal(result.assessment.status,'ARGOS_SYSTEM_DEGRADED');assert.equal(result.proposals.length,0);});
test('invalid supervision input fails closed without touching a shelf',()=>{let calls=0;const result=supervisor.supervise({runId:'x',now:NOW,observations:[],agentEnvelopeHash:'bad',shelf:{append(){calls++;}}});assert.equal(result.status,'ARGOS_SUPERVISION_BLOCKED');assert.equal(calls,0);});
test('supervisor exports no apply repair release deploy or mutation operation',()=>{for(const name of ['apply','repair','release','deploy','push','writeDatabase'])assert.equal(supervisor[name],undefined);});
