'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const shelfApi=require('../argos-event-shelf');const ledgerApi=require('../argos-operations-ledger');const H='a'.repeat(64),V='b'.repeat(64),NOW='2026-09-01T10:00:00.000Z',LATER='2026-09-01T10:05:00.000Z';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'argos-ops-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return ledgerApi.create({shelf:shelfApi.create({root,shelfId:'operations',maxEvents:30})});}
test('persists one start and one terminal result for an assurance run',t=>{const ledger=fixture(t);assert.equal(ledger.startRun({runId:'daily-1',startedAt:NOW,scopeHash:H}).status,'ARGOS_RUN_STARTED');assert.equal(ledger.finishRun({runId:'daily-1',finishedAt:LATER,outcome:'PASSED',evidenceHash:V}).status,'ARGOS_RUN_PASSED');assert.deepEqual(ledger.snapshot().runs,[{runId:'daily-1',state:'PASSED',startedAt:NOW,finishedAt:LATER}]);assert.equal(ledger.finishRun({runId:'daily-1',finishedAt:LATER,outcome:'PASSED',evidenceHash:V}).reasonCode,'RUN_ALREADY_TERMINAL');});
test('run result cannot exist without a start or before start time',t=>{const ledger=fixture(t);assert.equal(ledger.finishRun({runId:'x',finishedAt:LATER,outcome:'FAILED',evidenceHash:H}).reasonCode,'RUN_NOT_STARTED');ledger.startRun({runId:'x',startedAt:LATER,scopeHash:H});assert.equal(ledger.finishRun({runId:'x',finishedAt:NOW,outcome:'FAILED',evidenceHash:H}).reasonCode,'RUN_TIME_REVERSED');});
test('incident requires owner acknowledgement and verification before resolution',t=>{const ledger=fixture(t);ledger.openIncident({incidentId:'incident-1',openedAt:NOW,evidenceHash:H});assert.equal(ledger.resolveIncident({incidentId:'incident-1',resolvedAt:LATER,ownerApprovalHash:H,verificationHash:V}).reasonCode,'OWNER_ACKNOWLEDGEMENT_REQUIRED');ledger.acknowledgeIncident({incidentId:'incident-1',acknowledgedAt:NOW,ownerApprovalHash:H});assert.equal(ledger.resolveIncident({incidentId:'incident-1',resolvedAt:LATER,ownerApprovalHash:V,verificationHash:V}).reasonCode,'OWNER_APPROVAL_MISMATCH');assert.equal(ledger.resolveIncident({incidentId:'incident-1',resolvedAt:LATER,ownerApprovalHash:H,verificationHash:V}).status,'ARGOS_INCIDENT_RESOLVED');assert.equal(ledger.snapshot().incidents[0].state,'RESOLVED');});
test('incident history cannot be duplicated reversed or silently reopened',t=>{const ledger=fixture(t);assert.equal(ledger.openIncident({incidentId:'incident-1',openedAt:LATER,evidenceHash:H}).status,'ARGOS_INCIDENT_OPEN');assert.equal(ledger.openIncident({incidentId:'incident-1',openedAt:LATER,evidenceHash:H}).reasonCode,'INCIDENT_ALREADY_EXISTS');assert.equal(ledger.acknowledgeIncident({incidentId:'incident-1',acknowledgedAt:NOW,ownerApprovalHash:H}).reasonCode,'INCIDENT_STATE_INVALID');});
test('ledger has no deletion mutation release deploy or auto-repair surface',t=>{const ledger=fixture(t);for(const name of ['delete','remove','mutate','release','deploy','repair','apply'])assert.equal(ledger[name],undefined);});
