'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const argos=require('../argos-governance-core.js');

const H1='1'.repeat(64),H2='2'.repeat(64),NOW='2026-09-01T10:00:00.000Z';
function inventory(entries){return argos.createInventory({scopeId:'sinbad-marine',observedAt:NOW,entries});}
function entry(path,hash=H1,protectedValue=false){return {path,sha256:hash,bytes:10,kind:'SOURCE',protected:protectedValue};}

test('ARGOS creates canonical immutable inventories and detects no drift',()=>{const value=inventory([entry('a.js')]);assert.match(value.inventoryHash,/^[a-f0-9]{64}$/u);assert.ok(Object.isFrozen(value));assert.ok(Object.isFrozen(value.entries));const comparison=argos.compareInventories(value,value);assert.equal(comparison.status,'ARGOS_INTEGRITY_CLEAN');assert.equal(comparison.changes.length,0);});
test('protected modification and deletion require review with exact evidence',()=>{const before=inventory([entry('a.js'),entry('core.js',H1,true)]);for(const after of [inventory([entry('a.js'),entry('core.js',H2,true)]),inventory([entry('a.js')])]){const result=argos.compareInventories(before,after);assert.equal(result.status,'ARGOS_PROTECTED_CHANGE_REVIEW_REQUIRED');assert.equal(result.changes.length,1);assert.equal(result.changes[0].path,'core.js');assert.equal(result.changes[0].protected,true);assert.match(result.changeSetHash,/^[a-f0-9]{64}$/u);}});
test('ordinary additions are recorded without becoming execution authority',()=>{const result=argos.compareInventories(inventory([]),inventory([entry('feature.js')]));assert.equal(result.status,'ARGOS_CHANGE_RECORDED');assert.equal(result.reasonCode,'CHANGE_DETECTED');assert.ok(Object.isFrozen(result.changes[0]));});
test('inventory rejects traversal duplicates unsorted entries accessors and fake objects',()=>{assert.throws(()=>inventory([entry('../secret')]),/ARGOS_INVENTORY_ENTRY_INVALID/u);assert.throws(()=>inventory([entry('b'),entry('a')]),/ARGOS_INVENTORY_ENTRY_INVALID/u);assert.throws(()=>inventory([entry('a'),entry('a')]),/ARGOS_INVENTORY_ENTRY_INVALID/u);let reads=0;const hostile={scopeId:'sinbad-marine',observedAt:NOW,entries:[]};Object.defineProperty(hostile,'entries',{get(){reads++;throw new Error('no');}});assert.throws(()=>argos.createInventory(hostile),/ARGOS_INVENTORY_INVALID/u);assert.equal(reads,0);assert.equal(argos.compareInventories({},{}).status,'ARGOS_COMPARISON_BLOCKED');});
test('read and eligible test commands are admitted but mutation is never self-authorized',()=>{const clean=argos.compareInventories(inventory([]),inventory([]));for(const action of ['READ_ONLY','TEST'])assert.equal(argos.evaluateCommand({commandId:`cmd-${action}`,actorId:'agent-1',action,targetRef:'repo',requestedAt:NOW,changeAssessment:clean}).mayExecute,true);for(const action of ['WRITE','REPAIR','DELETE','RELEASE','SUPABASE_MUTATION','CREDENTIAL_CHANGE','PHYSICAL_CONTROL']){const result=argos.evaluateCommand({commandId:`cmd-${action}`,actorId:'agent-1',action,targetRef:'repo',requestedAt:NOW,changeAssessment:clean});assert.equal(result.mayExecute,false);assert.notEqual(result.status,'ARGOS_COMMAND_ADMITTED');}});
test('protected drift blocks tests and malformed commands fail closed',()=>{const changed=argos.compareInventories(inventory([entry('core.js',H1,true)]),inventory([entry('core.js',H2,true)]));assert.equal(argos.evaluateCommand({commandId:'cmd-test',actorId:'agent-1',action:'TEST',targetRef:'repo',requestedAt:NOW,changeAssessment:changed}).mayExecute,false);assert.equal(argos.evaluateCommand({}).reasonCode,'COMMAND_INVALID');});
test('append-only journal forms an immutable hash chain without payload content',()=>{const journal=argos.createJournal({journalId:'argos-main',maxEvents:3});const one=journal.append({eventId:'evt-1',observedAt:NOW,actorId:'agent-1',kind:'OBSERVED',targetRef:'repo',outcome:'RECORDED',evidenceHash:H1});const two=journal.append({eventId:'evt-2',observedAt:'2026-09-01T10:00:01.000Z',actorId:'argos',kind:'TEST_COMPLETED',targetRef:'repo',outcome:'PASSED',evidenceHash:H2});assert.equal(two.previousHash,one.eventHash);const snapshot=journal.snapshot();assert.equal(snapshot.headHash,two.eventHash);assert.equal(snapshot.eventCount,2);assert.ok(Object.isFrozen(snapshot.entries));assert.equal(Object.hasOwn(one,'payload'),false);});
test('journal rejects duplicates hostile events and fails closed at capacity',()=>{const journal=argos.createJournal({journalId:'argos-main',maxEvents:1});const event={eventId:'evt-1',observedAt:NOW,actorId:'argos',kind:'OBSERVED',targetRef:'repo',outcome:'RECORDED',evidenceHash:H1};journal.append(event);assert.throws(()=>journal.append({...event,eventId:'evt-2'}),/ARGOS_JOURNAL_CAPACITY_REACHED/u);assert.throws(()=>argos.createJournal({journalId:'x',maxEvents:0}),/ARGOS_JOURNAL_INVALID/u);});
test('module exports observation and gating only, never repair deploy credential or database executors',()=>{for(const name of ['repair','deploy','push','delete','execute','setCredential','mutateSupabase'])assert.equal(argos[name],undefined);assert.ok(Object.isFrozen(argos));});
