'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const recovery=require('../adapters/supabase-terminal-recovery.js');const key='a'.repeat(64),actor='b'.repeat(64);
function options(handler){return {serviceRole:true,actorHash:actor,client:{rpc:handler}};}
test('requires a service-role client and exposes a health-gated minimal frozen API',()=>{assert.throws(()=>recovery.create(),/service-role client/u);assert.throws(()=>recovery.create({client:{rpc(){}},serviceRole:false}),/service-role client/u);assert.throws(()=>recovery.create({client:{rpc(){}},serviceRole:true,actorHash:'bad'}),/operator identity/u);const value=recovery.create(options(async()=>({data:true,error:null})));assert.deepEqual(Object.keys(value),['healthCheck','listExpired','quarantine']);assert.ok(Object.isFrozen(value));assert.deepEqual(Object.keys(recovery),['create']);});
test('requires successful database capability verification before recovery operations',async()=>{const calls=[],client=recovery.create(options(async(name,args)=>{calls.push([name,args]);return name==='verify_terminal_recovery_access'?{data:true,error:null}:{data:[],error:null};}));assert.equal(await client.healthCheck(),true);assert.deepEqual(calls,[['verify_terminal_recovery_access',{}]]);});
test('lists only validated minimal expired claim metadata',async()=>{const rows=[{claim_key:key,claimed_at:'2026-08-13T00:00:00Z',lease_expires_at:'2026-08-13T00:01:00Z',secret:'no'},{claim_key:'bad',claimed_at:'2026-08-13T00:00:00Z',lease_expires_at:'2026-08-13T00:01:00Z'}],calls=[],client=recovery.create(options(async(name,args)=>{calls.push([name,args]);return name==='verify_terminal_recovery_access'?{data:true,error:null}:{data:rows,error:null};}));const result=await client.listExpired(25);assert.deepEqual(calls,[['verify_terminal_recovery_access',{}],['list_expired_terminal_delivery_claims',{p_limit:25}]]);assert.deepEqual(result,[{claimKey:key,claimedAt:'2026-08-13T00:00:00Z',leaseExpiresAt:'2026-08-13T00:01:00Z'}]);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result[0]));assert.equal('secret'in result[0],false);});
test('invalid list limits and RPC failures fail closed to an empty result',async()=>{let calls=0;const client=recovery.create(options(async name=>{calls++;return name==='verify_terminal_recovery_access'?{data:true,error:null}:{data:null,error:{message:'denied'}};}));for(const limit of [0,501,1.5,'x'])assert.deepEqual(await client.listExpired(limit),[]);assert.equal(calls,0);assert.deepEqual(await client.listExpired(1),[]);assert.equal(calls,2);});
test('quarantines only allowlisted content-free operator decisions',async()=>{const calls=[],client=recovery.create(options(async(name,args)=>{calls.push([name,args]);return {data:true,error:null};}));assert.equal(await client.quarantine({claimKey:key,reasonCode:'PROCESS_CRASH'}),true);assert.deepEqual(calls[1],['quarantine_expired_terminal_delivery_claim',{p_claim_key:key,p_actor_hash:actor,p_reason_code:'PROCESS_CRASH'}]);for(const input of [{claimKey:'bad',reasonCode:'PROCESS_CRASH'},{claimKey:key,reasonCode:'DELIVERED'}])assert.equal(await client.quarantine(input),false);assert.equal(calls.length,2);});
test('forward migration disables automatic takeover and makes quarantine distinct and audited',()=>{const oldSql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260813_terminal_delivery_idempotency.sql'),'utf8'),sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260814_terminal_delivery_recovery.sql'),'utf8');assert.match(oldSql,/on conflict \(claim_key\) do update/iu);assert.match(sql,/on conflict \(claim_key\) do nothing/iu);assert.doesNotMatch(sql,/on conflict \(claim_key\) do update/iu);for(const pattern of [/terminal_delivery_recovery_audit/iu,/status='QUARANTINED'/u,/OPERATOR_QUARANTINED/u,/lease_expires_at<=clock_timestamp\(\)/iu,/insert into public\.terminal_delivery_recovery_audit/iu,/revoke all on function public\.verify_terminal_recovery_access\(\) from public, anon, authenticated/iu,/grant execute on function public\.quarantine_expired_terminal_delivery_claim\(text,text,text\) to service_role/iu])assert.match(sql,pattern);});
