'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');
let sequence=0;function delivery(){const n=++sequence,answer=`Güvenlik şartı ${n}`,answerHash=projector.sha256(answer),sealInput={transactionId:`tx-2o-${n}`,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{section:'II-2',page:'12',chunk:'7',uri:null},publishedAt:'2026-01-01',version:'2026',authority:'authoritative',verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),result=contract.result({status:'GROUNDED_PLAN_READY',transactionId:sealInput.transactionId,publicResponse});return adapter.adapt(result);}
function context(overrides={}){return {sessionId:'session-a',channelId:'atlas-ui',deliveryNonce:`nonce-${sequence}`,...overrides};}
test('authorizes an authentic delivery once and binds session channel and nonce',()=>{const value=delivery(),result=authorizer.authorize(value,context());assert.equal(result.status,'DELIVERY_AUTHORIZED');assert.equal(result.sessionId,'session-a');assert.equal(result.channelId,'atlas-ui');assert.equal(result.answer,value.answer);assert.ok(/^[a-f0-9]{64}$/u.test(result.authorizationHash));assert.ok(Object.isFrozen(result));});
test('same delivery cannot be authorized twice or replayed to another target',()=>{const value=delivery(),first=authorizer.authorize(value,context());assert.equal(first.status,'DELIVERY_AUTHORIZED');for(const changed of [context(),context({sessionId:'session-b'}),context({channelId:'other'}),context({deliveryNonce:'other-nonce'})]){const result=authorizer.authorize(value,changed);assert.equal(result.status,'DELIVERY_AUTHORIZATION_BLOCKED');assert.equal(result.reasonCode,'DELIVERY_AUTHORIZATION_DENIED');assert.equal(result.answer,null);}});
test('nonce cannot be reused for a different authentic delivery in the same target during TTL',()=>{const first=delivery(),shared=context({deliveryNonce:'shared',now:()=>1000});assert.equal(authorizer.authorize(first,shared).status,'DELIVERY_AUTHORIZED');const second=delivery(),result=authorizer.authorize(second,{...shared});assert.equal(result.status,'DELIVERY_AUTHORIZATION_BLOCKED');assert.equal(result.reasonCode,'DELIVERY_AUTHORIZATION_DENIED');const third=delivery();assert.equal(authorizer.authorize(third,{...shared,now:()=>1000+authorizer.NONCE_TTL_MS+1}).status,'DELIVERY_AUTHORIZED');});
test('copied proxy malformed context and altered delivery fail closed',()=>{const first=delivery(),cases=[[{...first},context()],[new Proxy(first,{}),context()],[first,context({sessionId:''})],[first,context({channelId:'bad\u0000channel'})]];for(const [value,target] of cases)assert.equal(authorizer.authorize(value,target).status,'DELIVERY_AUTHORIZATION_BLOCKED');const second=delivery();assert.equal(authorizer.authorize({...second,deliveryHash:'b'.repeat(64)},context()).status,'DELIVERY_AUTHORIZATION_BLOCKED');});
test('session channel and nonce identifiers reject Unicode confusables and normalize NFC',()=>{assert.equal(authorizer.clean('cafe\u0301'),'');assert.equal(authorizer.clean('channel\u202eadmin'),'');assert.equal(authorizer.clean('zero\u200bwidth'),'');assert.equal(authorizer.clean('atlas-ui:main'),'atlas-ui:main');});
test('authorizer invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(authorizer.authorize(delivery(),context()).status,'DELIVERY_AUTHORIZED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
