'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const journal=require('../adapters/supabase-rollout-activation-journal.js');
const hash='a'.repeat(64);function create(handler){return journal.create({serviceRole:true,client:{rpc:handler}});}
test('requires service role and exposes a frozen durable minimal journal',()=>{assert.throws(()=>journal.create(),/service-role client/u);assert.throws(()=>journal.create({serviceRole:false,client:{rpc(){}}}),/service-role client/u);const value=create(async()=>({data:true,error:null}));assert.equal(value.version,journal.JOURNAL_VERSION);assert.equal(value.durable,true);assert.ok(Object.isFrozen(value));});
test('begins settles and inspects with exact content-free RPCs',async()=>{const calls=[],value=create(async(name,args)=>{calls.push([name,args]);if(name==='begin_terminal_rollout_activation')return {data:'BEGUN',error:null};if(name==='settle_terminal_rollout_activation')return {data:'SETTLED',error:null};return {data:[{status:'UNKNOWN',started_at:'2026-08-13T00:00:00Z',updated_at:'2026-08-13T00:01:00Z'}],error:null};});assert.deepEqual(await value.begin(hash),{status:'BEGUN',state:null});assert.deepEqual(await value.settle(hash,'PENDING','UNKNOWN'),{status:'SETTLED',state:null});assert.deepEqual(await value.inspect(hash),{status:'FOUND',state:{status:'UNKNOWN',startedAt:'2026-08-13T00:00:00Z',updatedAt:'2026-08-13T00:01:00Z'}});assert.deepEqual(calls,[['begin_terminal_rollout_activation',{p_attestation_hash:hash}],['settle_terminal_rollout_activation',{p_attestation_hash:hash,p_expected_status:'PENDING',p_status:'UNKNOWN'}],['inspect_terminal_rollout_activation',{p_attestation_hash:hash}]]);});
test('preserves closed RPC outcomes without collapsing conflicts or absence',async()=>{for(const status of ['BEGUN','EXISTS','DENIED'])assert.deepEqual(await create(async()=>({data:status,error:null})).begin(hash),{status,state:null});for(const status of ['SETTLED','ALREADY_SETTLED','CONFLICT','DENIED'])assert.deepEqual(await create(async()=>({data:status,error:null})).settle(hash,'PENDING','APPLIED'),{status,state:null});assert.deepEqual(await create(async()=>({data:[],error:null})).inspect(hash),{status:'ABSENT',state:null});});
test('invalid inputs errors malformed rows and promise rejection fail closed',async()=>{let calls=0;const value=create(async()=>{calls++;throw new Error('offline');});assert.deepEqual(await value.begin('bad'),{status:'INVALID',state:null});assert.deepEqual(await value.settle(hash,'PENDING','PENDING'),{status:'INVALID',state:null});assert.deepEqual(await value.settle(hash,'UNKNOWN','UNKNOWN'),{status:'INVALID',state:null});assert.deepEqual(await value.inspect('bad'),{status:'INVALID',state:null});assert.equal(calls,0);assert.deepEqual(await value.begin(hash),{status:'UNAVAILABLE',state:null});assert.deepEqual(await value.inspect(hash),{status:'UNAVAILABLE',state:null});for(const data of [[{},{}],[{}],[{status:'APPLIED',started_at:'bad',updated_at:'bad'}],[{status:'APPLIED',started_at:'2026-08-13T00:02:00Z',updated_at:'2026-08-13T00:01:00Z'}]])assert.deepEqual(await create(async()=>({data,error:null})).inspect(hash),{status:'UNAVAILABLE',state:null});});
test('unexpected RPC payloads and explicit errors remain unavailable',async()=>{for(const response of [{data:false,error:null},{data:'OTHER',error:null},{data:null,error:new Error('denied')}])assert.deepEqual(await create(async()=>response).begin(hash),{status:'UNAVAILABLE',state:null});});
test('forward migration enforces service-role-only compare-and-set transitions',()=>{const sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260816_rollout_activation_journal.sql'),'utf8');for(const pattern of [/^begin;/iu,/enable row level security/iu,/auth\.role\(\)<>'service_role'/iu,/on conflict \(attestation_hash\) do nothing/iu,/p_expected_status not in \('PENDING','UNKNOWN'\)/iu,/status=p_expected_status/iu,/return 'ALREADY_SETTLED'/iu,/return 'CONFLICT'/iu,/settle_terminal_rollout_activation\(text,text,text\)/iu,/raise exception 'service role required'/iu,/grant execute on function public\.inspect_terminal_rollout_activation\(text\) to service_role/iu,/commit;/iu])assert.match(sql,pattern);});
