'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const library=require('../library/contracts.js');const identity=require('../library/identity.js');const ingest=require('../library/text-ingestor.js');const builder=require('../library/index-builder.js');const trust=require('../library/trust-policy.js');const activator=require('../library/index-activator.js');const reader=require('../library/active-index-reader.js');const adapter=require('../retrieval/indexed-offline-library-adapter.js');const planner=require('../verification/claim-planner.js');const verifier=require('../verification/claim-support-verifier.js');const grounding=require('../grounding/grounded-answer-pipeline.js');const orchestrator=require('../orchestrator/grounded-orchestrator.js');const audit=require('../orchestrator/audit-log.js');
async function fixture(content='First notice\nMiddle safety requirement\nLast notice',searchQuery='notice safety requirement'){const root=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-2f-root-')),state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-2f-state-')),bytes=Buffer.from(content.replace(/\n/g,'\r\n')),parsed=ingest.ingest({path:'official.txt',bytes}),meta={path:'official.txt',issuerId:'imo',publicationKey:'phase2f',logicalDocumentKey:'phase2f-main',editionLabel:'2026',effectiveDate:'2026-01-01T00:00:00.000Z',expiresAt:'2030-01-01T00:00:00.000Z',language:'en',category:'safety',jurisdiction:'international',expectedRawHash:parsed.rawHash,expectedCanonicalHash:parsed.canonicalHash},sourceId=identity.source(meta),documentId=identity.document({sourceId,logicalDocumentKey:meta.logicalDocumentKey}),editionId=identity.edition({documentId,editionLabel:meta.editionLabel,effectiveDate:meta.effectiveDate,canonicalHash:parsed.canonicalHash}),grant={sourceId,documentId,editionId,canonicalHash:parsed.canonicalHash,authority:'authoritative',license:'public-domain',status:'approved'},policy={schemaVersion:library.VERSIONS.policy,policyId:'policy:phase2f',issuers:[{issuerId:'imo',sources:[grant]}]},manifest={schemaVersion:library.VERSIONS.manifest,manifestId:'manifest:phase2f',documents:[meta]},expectedPolicyHash=trust.create({policy}).policyHash,stage=path.join(state,'stage');await fs.writeFile(path.join(root,'official.txt'),bytes);await builder.build({buildId:'phase2f',root,stagingDir:stage,manifest,policy,expectedPolicyId:policy.policyId,expectedPolicyHash,at:'2026-08-12T00:00:00.000Z'});await activator.activate({stateDir:state,stagingDir:stage,buildId:'phase2f',expectedPolicyId:policy.policyId,expectedPolicyHash});const snapshot=await reader.open({stateDir:state,expectedPolicyId:policy.policyId,expectedPolicyHash}),items=adapter.create({snapshot,now:()=> '2026-08-12T00:00:00.000Z'}).search({id:'q',query:searchQuery,limit:100,filters:{}}).items;return {root,state,snapshot,items};}
async function dispose(f){await fs.rm(f.root,{recursive:true,force:true});await fs.rm(f.state,{recursive:true,force:true});}

test('planner emits deterministic exact full-line claims that the independent verifier approves',async()=>{const f=await fixture();try{const log=audit.create({now:()=> '2026-08-12T00:00:00.000Z'}),first=planner.plan({transactionId:'tx',query:'safety requirement',selected:f.items},{audit:log}),second=planner.plan({transactionId:'tx',query:'safety requirement',selected:[...f.items].reverse()});assert.equal(first.status,'CLAIMS_PLANNED');assert.equal(first.claims.length,1);assert.equal(first.claims[0].statement,'Middle safety requirement');assert.equal(first.claims[0].support.mode,'EXACT_SPAN');assert.equal(first.claims[0].requiresAuthoritative,true);assert.equal(verifier.verify(first.claims[0],{selected:f.items}).status,'CLAIM_SUPPORTED');assert.deepEqual(first.claims,second.claims);assert.ok(Object.isFrozen(first));assert.ok(Object.isFrozen(first.claims));assert.deepEqual(log.snapshot().map(x=>x.stage),['claim-planning','claim-planning','claim-planning']);}finally{await dispose(f);}});

test('planner deduplicates overlapping chunks by canonical occurrence identity',async()=>{const f=await fixture(`${'A'.repeat(1300)}\nTARGET SAFETY LINE\n${'B'.repeat(1300)}`);try{assert.ok(f.items.length>=2);const result=planner.plan({transactionId:'overlap',query:'TARGET SAFETY',selected:f.items,limit:8});assert.equal(result.claims.length,1);assert.equal(result.claims[0].statement,'TARGET SAFETY LINE');assert.ok(result.metrics.candidateCount>=2);}finally{await dispose(f);}});

test('planner fails closed for absent authenticated occurrence provenance and unrelated text',async()=>{const f=await fixture();try{const forged={...f.items[0],provenance:{...f.items[0].provenance,occurrencePosition:{...f.items[0].provenance.occurrencePosition}}},bad=planner.plan({transactionId:'bad',query:'safety',selected:[forged]}),unrelated=planner.plan({transactionId:'none',query:'unrelated-token',selected:f.items});assert.equal(bad.status,'NO_ELIGIBLE_CLAIMS');assert.equal(bad.claims.length,0);assert.ok(bad.rejected.length>0);assert.equal(unrelated.status,'NO_ELIGIBLE_CLAIMS');assert.equal(unrelated.claims.length,0);}finally{await dispose(f);}});

test('planner enforces bounded output and never copies query text into a claim',async()=>{const f=await fixture('KEY shared one\nKEY shared two\nKEY shared three\nKEY shared four','KEY shared');try{const result=planner.plan({transactionId:'limit',query:'KEY shared invented instruction',selected:f.items,limit:2});assert.equal(result.claims.length,2);assert.ok(result.claims.every(x=>x.statement.startsWith('KEY shared ')));assert.ok(result.claims.every(x=>!x.statement.includes('invented instruction')));}finally{await dispose(f);}});

test('planner preserves canonical CRLF normalization and UTF-16 surrogate boundaries',async()=>{const f=await fixture('Header\nSAFETY 😀 REQUIREMENT\nFooter','SAFETY REQUIREMENT');try{const result=planner.plan({transactionId:'unicode',query:'SAFETY REQUIREMENT',selected:f.items}),claim=result.claims[0];assert.equal(claim.statement,'SAFETY 😀 REQUIREMENT');assert.equal(claim.support.endOffset-claim.support.startOffset,claim.statement.length);assert.equal(verifier.verify(claim,{selected:f.items}).status,'CLAIM_SUPPORTED');}finally{await dispose(f);}});

test('planner rethrows unexpected internal errors instead of disguising them as provenance rejection',()=>{const evidence={id:'e-internal',content:'SAFETY',relevance:1,get provenance(){throw new TypeError('internal sentinel');}};assert.throws(()=>planner.plan({transactionId:'internal',query:'SAFETY',selected:[evidence]}),/internal sentinel/u);});

test('planner rejects missing provenance explicitly and plan authenticity cannot be copied or forged',()=>{const missing=planner.plan({transactionId:'missing',query:'SAFETY',selected:[{id:'e-missing',content:'SAFETY'}]});assert.equal(missing.status,'NO_ELIGIBLE_CLAIMS');assert.equal(missing.rejected[0].reason,'MALFORMED_EVIDENCE');assert.equal(planner.isAuthenticPlan(missing),true);assert.equal(planner.isAuthenticPlan({...missing}),false);});

test('orchestrator plans only when caller claims are absent and links Phase 2F/2G audit',async()=>{const f=await fixture();try{const selected=f.items,decision={run(){return {status:'SOURCE_INSUFFICIENT',request:{question:'safety requirement',language:'en'},analysis:{intent:'publication',confidence:1,secondaryIntents:[]},safety:{risk:'low'},routing:{routes:[]},audit:[]};}},retrieval={run(){return {version:'fixture',status:'EVIDENCE_SUFFICIENT',evaluation:{selected,rejected:[]},rejected:[],metrics:{}};}},engine=orchestrator.create({decisionPipeline:decision,retrievalEngine:retrieval,groundingPipeline:grounding.create({clock:()=>1}),clock:()=>1,now:()=> '2026-08-12T00:00:00.000Z'}),result=engine.run({transactionId:'phase2f-runtime',question:'safety requirement'});assert.equal(result.status,'GROUNDED_PLAN_READY');assert.equal(result.claimPlan.status,'CLAIMS_PLANNED');assert.equal(result.claimCoverage.status,'COVERAGE_SUFFICIENT');assert.equal(result.groundedAnswer.answer,'Middle safety requirement');assert.equal(result.citations.length,1);assert.ok(result.audit.some(x=>x.phase==='2F'&&x.stage==='claim-planning'));assert.ok(result.audit.some(x=>x.phase==='2G'&&x.stage==='query-coverage'));const supplied=result.claimPlan.claims[0],legacy=engine.run({transactionId:'phase2f-supplied',question:'safety requirement',claims:[supplied]});assert.equal(legacy.claimPlan,null);assert.equal(legacy.claimCoverage,null);assert.equal(legacy.status,'GROUNDED_PLAN_READY');}finally{await dispose(f);}});

test('partial incidental claim matches abstain at the Phase 2G coverage gate',async()=>{const f=await fixture();try{const decision={run(){return {status:'SOURCE_INSUFFICIENT',request:{question:'safety requirement emergency fire',language:'en'},analysis:{intent:'publication',confidence:1,secondaryIntents:[]},safety:{risk:'low'},routing:{routes:[]},audit:[]};}},retrieval={run(){return {version:'fixture',status:'EVIDENCE_SUFFICIENT',evaluation:{selected:f.items,rejected:[]},rejected:[],metrics:{}};}},result=orchestrator.create({decisionPipeline:decision,retrievalEngine:retrieval,groundingPipeline:grounding.create()}).run({transactionId:'partial-coverage'});assert.equal(result.claimPlan.status,'CLAIMS_PLANNED');assert.equal(result.claimCoverage.status,'COVERAGE_INSUFFICIENT');assert.deepEqual(result.claimCoverage.uncoveredTokens,['emergency','fire']);assert.equal(result.status,'SOURCE_INSUFFICIENT');assert.equal(result.groundedAnswer.answer,null);assert.equal(result.citations.length,0);}finally{await dispose(f);}});

test('empty planner outcome is source insufficiency rather than invalid caller claims',async()=>{const f=await fixture();try{const decision={run(){return {status:'SOURCE_INSUFFICIENT',request:{question:'absent',language:'en'},analysis:{intent:'publication',confidence:1,secondaryIntents:[]},safety:{risk:'low'},routing:{routes:[]},audit:[]};}},retrieval={run(){return {version:'fixture',status:'EVIDENCE_SUFFICIENT',evaluation:{selected:f.items,rejected:[]},rejected:[],metrics:{}};}},result=orchestrator.create({decisionPipeline:decision,retrievalEngine:retrieval,groundingPipeline:grounding.create()}).run({transactionId:'empty-plan',question:'absent'});assert.equal(result.claimPlan.status,'NO_ELIGIBLE_CLAIMS');assert.equal(result.status,'SOURCE_INSUFFICIENT');assert.equal(result.groundedAnswer.status,'SOURCE_INSUFFICIENT');assert.equal(result.citations.length,0);}finally{await dispose(f);}});

test('spoofed planning status cannot soften empty caller claims and planner failures stop safely',async()=>{const f=await fixture();try{const retrievalResult={version:'fixture',status:'EVIDENCE_SUFFICIENT',evaluation:{selected:f.items,rejected:[]},rejected:[],metrics:{}},direct=grounding.create().run({transactionId:'spoof',retrievalResult,claims:[],claimPlan:{status:'NO_ELIGIBLE_CLAIMS'}});assert.equal(direct.status,'INVALID_CLAIMS');const decision={run(){return {status:'SOURCE_INSUFFICIENT',request:{question:'safety',language:'en'},analysis:{intent:'publication',confidence:1,secondaryIntents:[]},safety:{risk:'low'},routing:{routes:[]},audit:[]};}},retrieval={run(){return retrievalResult;}},throwing={plan(){throw new TypeError('planner failure');}},result=orchestrator.create({decisionPipeline:decision,retrievalEngine:retrieval,groundingPipeline:grounding.create(),claimPlanner:throwing}).run({transactionId:'planner-failure',question:'safety'});assert.equal(result.claimPlan.status,'PLANNER_UNAVAILABLE');assert.equal(result.claimPlan.reasonCode,'INTERNAL_ERROR');assert.equal(result.status,'SOURCE_INSUFFICIENT');assert.ok(result.audit.some(x=>x.reason==='CLAIM_PLANNER_FAILURE'));}finally{await dispose(f);}});

test('an authentic empty plan cannot be replayed across transaction or query boundaries',async()=>{const f=await fixture();try{const retrievalResult={version:'fixture',status:'EVIDENCE_SUFFICIENT',evaluation:{selected:f.items,rejected:[]},rejected:[],metrics:{}},empty=planner.plan({transactionId:'original',query:'absent phrase',selected:f.items});assert.equal(empty.status,'NO_ELIGIBLE_CLAIMS');const pipeline=grounding.create(),transactionReplay=pipeline.run({transactionId:'other',retrievalResult,claims:[],claimPlan:empty,planningQuery:'absent phrase'}),queryReplay=pipeline.run({transactionId:'original',retrievalResult,claims:[],claimPlan:empty,planningQuery:'different phrase'});assert.equal(transactionReplay.status,'INVALID_CLAIMS');assert.equal(queryReplay.status,'INVALID_CLAIMS');}finally{await dispose(f);}});

test('empty planning stops conclusively and invokes no model expert navigation or network',async()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};const f=await fixture();try{const result=planner.plan({transactionId:'no-capabilities',query:'absent',selected:f.items});assert.equal(result.status,'NO_ELIGIBLE_CLAIMS');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;await dispose(f);}});
