'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const c=require('../library/contracts.js');const ids=require('../library/identity.js');const trust=require('../library/trust-policy.js');const boundary=require('../library/root-boundary.js');const integrity=require('../library/index-integrity.js');const activator=require('../library/index-activator.js');const reader=require('../library/active-index-reader.js');const lineageApi=require('../library/provenance.js');const indexedAdapter=require('../retrieval/indexed-offline-library-adapter.js');const citations=require('../grounding/citation-builder.js');const verifier=require('../verification/claim-support-verifier.js');const claimContracts=require('../verification/claim-contracts.js');const phase2eFixture=require('./phase2e-test-fixtures.js');
function authorityGolden(){const document={issuerId:'imo',sourceId:'src:good',documentId:'doc:good',editionId:'ed:good',canonicalHash:'a'.repeat(64)};const grant={sourceId:document.sourceId,documentId:document.documentId,editionId:document.editionId,canonicalHash:document.canonicalHash,authority:'authoritative',license:'public-domain',status:'approved'};const policy={schemaVersion:c.VERSIONS.policy,policyId:'policy:golden',issuers:[{issuerId:'imo',sources:[grant]}]};return {document,grant,policy};}
function assertNonTargetGolden(g,target){if(target!=='issuer')assert.equal(g.document.issuerId,'imo');if(target!=='source')assert.equal(g.document.sourceId,g.grant.sourceId);if(target!=='document')assert.equal(g.document.documentId,g.grant.documentId);if(target!=='edition')assert.equal(g.document.editionId,g.grant.editionId);if(target!=='hash')assert.equal(g.document.canonicalHash,g.grant.canonicalHash);if(target!=='license')assert.equal(g.grant.license,'public-domain');if(target!=='status')assert.equal(g.grant.status,'approved');}
function expectCode(fn,code){assert.throws(fn,error=>{assert.equal(error.code,code);return true;});}
async function stagedIndex(state,label,editions=[]){const dir=path.join(state,`stage-${label}`);await fs.mkdir(dir);const core={schemaVersion:c.VERSIONS.index,buildId:label,manifestId:'m',policyId:'p',policyHash:'ph',chunkerVersion:c.VERSIONS.chunker,editions,chunks:[]};const indexId=ids.index(core);const index={...core,indexId};const raw=Buffer.from(ids.canonical(index)),hash=ids.sha256(raw);await fs.writeFile(path.join(dir,'index.json'),raw);await fs.writeFile(path.join(dir,'integrity.json'),ids.canonical({schemaVersion:c.VERSIONS.index,indexId,indexHash:hash,artifacts:{'index.json':hash}}));return {dir,indexId,indexHash:hash};}

test('golden authority resolver grants only the exact trusted tuple',()=>{const g=authorityGolden();assertNonTargetGolden(g,'none');const result=trust.create({policy:g.policy}).resolve(g.document,{at:'2026-08-11T00:00:00.000Z'});assert.equal(result.verified,true);assert.equal(result.reason,'TRUST_POLICY_GRANTED');});
test('identity functions ignore caller IDs and remain content-bound',()=>{const sourceInput={issuerId:'imo',publicationKey:'solas',sourceId:'caller-source'},sourceA=ids.source(sourceInput),sourceB=ids.source({...sourceInput,sourceId:'other'});assert.equal(sourceA,sourceB);const documentA=ids.document({sourceId:sourceA,logicalDocumentKey:'main',documentId:'caller-doc'}),documentB=ids.document({sourceId:sourceA,logicalDocumentKey:'main',documentId:'other'});assert.equal(documentA,documentB);const editionA=ids.edition({documentId:documentA,editionLabel:'1',effectiveDate:'2026',canonicalHash:'a'}),editionB=ids.edition({documentId:documentA,editionLabel:'1',effectiveDate:'2026',canonicalHash:'b'});assert.notEqual(editionA,editionB);const base={editionId:editionA,chunkerVersion:c.VERSIONS.chunker,ordinal:0,startOffset:0,endOffset:1};assert.notEqual(ids.chunk({...base,contentHash:'a'}),ids.chunk({...base,contentHash:'b'}));});
for(const row of [
  ['source','sourceId','src:other',c.STATES.AUTHORITY_NOT_GRANTED],
  ['document','documentId','doc:other',c.STATES.AUTHORITY_NOT_GRANTED],
  ['edition','editionId','ed:other',c.STATES.AUTHORITY_NOT_GRANTED],
  ['hash','canonicalHash','b'.repeat(64),c.STATES.HASH_MISMATCH]
])test(`single-variable ${row[0]} mutation fails for its exact reason`,()=>{const g=authorityGolden();const changed={...g.document,[row[1]]:row[2]};assertNonTargetGolden({...g,document:changed},row[0]);expectCode(()=>trust.create({policy:g.policy}).resolve(changed),row[3]);});
test('single-variable policy hash tampering fails while policy schema and trust tuple remain valid',()=>{const g=authorityGolden();assertNonTargetGolden(g,'none');const resolver=trust.create({policy:g.policy});expectCode(()=>trust.create({policy:g.policy,expectedPolicyHash:'0'.repeat(64)}),c.STATES.TRUST_POLICY_INVALID);assert.match(resolver.policyHash,/^[a-f0-9]{64}$/);});
test('single-variable license denial preserves every non-license condition',()=>{const g=authorityGolden();g.grant.license='unknown';assertNonTargetGolden(g,'license');expectCode(()=>trust.create({policy:g.policy}).resolve(g.document),c.STATES.LICENSE_REJECTED);});
test('license expiration boundary rejects at expiry and cannot use historical access',()=>{const g=authorityGolden();g.grant.licenseExpiresAt='2026-08-11T00:00:00.000Z';assertNonTargetGolden(g,'none');const resolver=trust.create({policy:g.policy});assert.equal(resolver.resolve(g.document,{at:'2026-08-10T23:59:59.999Z'}).verified,true);expectCode(()=>resolver.resolve(g.document,{at:'2026-08-11T00:00:00.000Z'}),c.STATES.LICENSE_REJECTED);expectCode(()=>resolver.resolve(g.document,{at:'2026-08-12T00:00:00.000Z',historical:true}),c.STATES.LICENSE_REJECTED);});
test('production build and open require external policy identity and hash',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-policy-root-'));const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-policy-state-'));try{const g=authorityGolden();await assert.rejects(()=>reader.open({stateDir:state}),e=>e.code===c.STATES.TRUST_POLICY_INVALID);await assert.rejects(()=>reader.open({stateDir:state,expectedPolicyId:'p'}),e=>e.code===c.STATES.TRUST_POLICY_INVALID);assert.throws(()=>trust.create({policy:g.policy,expectedPolicyHash:'0'.repeat(64)}),e=>e.code===c.STATES.TRUST_POLICY_INVALID);}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(state,{recursive:true,force:true});}});
test('single-variable revocation preserves every non-status condition',()=>{const g=authorityGolden();g.grant.status='revoked';assertNonTargetGolden(g,'status');expectCode(()=>trust.create({policy:g.policy}).resolve(g.document),c.STATES.EDITION_REVOKED);});
test('single-variable supersession is stale by default and secondary with explicit historical access',()=>{const g=authorityGolden();g.grant.status='superseded';assertNonTargetGolden(g,'status');const resolver=trust.create({policy:g.policy});expectCode(()=>resolver.resolve(g.document),c.STATES.EDITION_STALE);const historical=resolver.resolve(g.document,{historical:true});assert.equal(historical.verified,false);assert.equal(historical.maySatisfyAuthoritativeRequirement,false);});
test('strict policy schema rejects one unknown control field',()=>{const g=authorityGolden();assertNonTargetGolden(g,'none');expectCode(()=>trust.create({policy:{...g.policy,authoritative:true}}),c.STATES.TRUST_POLICY_INVALID);});
test('symlink or junction beneath approved root is rejected',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-root-'));const outside=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-out-'));try{await fs.writeFile(path.join(outside,'x.txt'),'x');try{await fs.symlink(outside,path.join(root,'link'),'junction');}catch(error){t.diagnostic(`junction creation unavailable: ${error.code}`);return;}const b=await boundary.create({root});await assert.rejects(()=>b.resolve('link/x.txt'),error=>error.code===c.STATES.REPARSE_POINT_REJECTED);}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test('citation preserves Phase 2D lineage without fabrication',()=>{const lineage={indexId:'idx:1',indexHash:'h',policyId:'p',policyHash:'ph',issuerId:'i',sourceId:'s',documentId:'d',editionId:'e',canonicalHash:'c',chunkId:'k',chunkContentHash:claimContracts.sha256(Buffer.from('data')),chunkerVersion:'v',license:'public-domain',authorityDecision:'TRUST_POLICY_GRANTED',editionStatus:'current'};const item={id:'k',sourceId:'s',sourceType:'offline-publication',evidenceClass:'verified-authoritative',authority:'authoritative',verified:true,title:'Title',content:'data',location:{chunk:'0'},relevance:1,maySatisfyAuthoritativeRequirement:true,provenance:lineage};const claim=phase2eFixture.exactClaim({content:'data',evidenceId:'k'}),verification=verifier.verify(claim,{selected:[item]}),result=citations.build({selected:[item],claims:[claim],verifications:[verification]});assert.deepEqual(result.citations[0].provenance,lineage);});
test('forged and raw snapshots cannot enter the production adapter',()=>{for(const snapshot of [{},{index:{chunks:[]},indexId:'idx:'+('a'.repeat(64)),indexHash:'h',policyId:'p',policyHash:'ph'}])assert.throws(()=>indexedAdapter.create({snapshot}),e=>e.code===c.STATES.INDEX_UNAVAILABLE);});
test('each missing authoritative lineage field fails without citation',()=>{const complete={indexId:'idx:'+('a'.repeat(64)),indexHash:'h',policyId:'p',policyHash:'ph',issuerId:'i',sourceId:'s',documentId:'d',editionId:'e',canonicalHash:'c',chunkId:'k',chunkContentHash:claimContracts.sha256(Buffer.from('data')),chunkerVersion:'v',license:'public-domain',authorityDecision:'TRUST_POLICY_GRANTED',editionStatus:'current'};for(const field of lineageApi.REQUIRED){const provenance={...complete};delete provenance[field];const item={id:'k',sourceId:'s',sourceType:'offline-publication',evidenceClass:'verified-authoritative',authority:'authoritative',verified:true,title:'Title',content:'data',location:{chunk:'0'},relevance:1,maySatisfyAuthoritativeRequirement:true,provenance};const claim=phase2eFixture.exactClaim({content:'data',evidenceId:'k'});assert.throws(()=>verifier.verify(claim,{selected:[item]}),error=>error.code==='PROVENANCE_INCOMPLETE',field);const result=citations.build({selected:[item],claims:[claim],verifications:[]});assert.equal(result.citations.length,0,field);}});
test('tampered assembled index same ID with different payload fails audit and activation',async()=>{const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-dup-state-')),dir=path.join(state,'candidate');await fs.mkdir(dir);try{const edition={editionId:'ed:1',sourceId:'src:1',documentId:'doc:1'};const common={editionId:'ed:1',chunkerVersion:c.VERSIONS.chunker,ordinal:0,startOffset:0,endOffset:1,contentHash:ids.sha256(Buffer.from('x'))};const chunk={...common,chunkId:ids.chunk(common),sourceId:'src:1',documentId:'doc:1',content:'x'};const conflicting={...chunk,content:'y',contentHash:ids.sha256(Buffer.from('y'))};const core={schemaVersion:c.VERSIONS.index,buildId:'b',manifestId:'m',policyId:'p',policyHash:'ph',chunkerVersion:c.VERSIONS.chunker,editions:[edition],chunks:[chunk,conflicting]};const indexId=ids.index(core),index={...core,indexId},raw=Buffer.from(ids.canonical(index)),hash=ids.sha256(raw);await fs.writeFile(path.join(dir,'index.json'),raw);await fs.writeFile(path.join(dir,'integrity.json'),ids.canonical({schemaVersion:c.VERSIONS.index,indexId,indexHash:hash,artifacts:{'index.json':hash}}));const events=[];await assert.rejects(()=>integrity.validate(dir,{buildId:'dup-build',expectedPolicyId:'p',expectedPolicyHash:'ph',audit:e=>events.push(e)}),error=>error.code===c.STATES.DUPLICATE_ID_CONFLICT);assert.deepEqual(events.map(e=>e.event),['DUPLICATE_ID_CONFLICT','INDEX_VALIDATION_FAILED']);for(const event of events){assert.equal(event.buildId,'dup-build');assert.equal(event.policyId,'p');assert.equal(event.policyHash,'ph');assert.equal(event.outcome,'STOPPED');assert.equal(event.reason,c.STATES.DUPLICATE_ID_CONFLICT);assert.ok(event.componentVersion&&event.schemaVersion);}await assert.rejects(()=>activator.activate({stateDir:state,stagingDir:dir,buildId:'dup-activate',expectedPolicyId:'p',expectedPolicyHash:'ph'}),error=>error.code===c.STATES.DUPLICATE_ID_CONFLICT);await assert.rejects(fs.access(path.join(state,'active.json')));}finally{await fs.rm(state,{recursive:true,force:true});}});
test('second valid activation preserves previous pointer and remains readable',async()=>{const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-act-'));try{async function staged(label){const dir=path.join(state,`stage-${label}`);await fs.mkdir(dir);const core={schemaVersion:c.VERSIONS.index,buildId:label,manifestId:'m',policyId:'p',policyHash:'ph',chunkerVersion:c.VERSIONS.chunker,editions:[],chunks:[]};const indexId=ids.index(core);const index={...core,indexId};const raw=Buffer.from(ids.canonical(index));const hash=ids.sha256(raw);await fs.writeFile(path.join(dir,'index.json'),raw);await fs.writeFile(path.join(dir,'integrity.json'),ids.canonical({schemaVersion:c.VERSIONS.index,indexId,indexHash:hash,artifacts:{'index.json':hash}}));return {dir,indexId};}const one=await staged('one');await activator.activate({stateDir:state,stagingDir:one.dir,buildId:'one'});const two=await staged('two');await activator.activate({stateDir:state,stagingDir:two.dir,buildId:'two'});assert.equal((await reader.open({stateDir:state,expectedPolicyId:'p',expectedPolicyHash:'ph'})).indexId,two.indexId);assert.equal(JSON.parse(await fs.readFile(path.join(state,'previous.json'),'utf8')).indexId,one.indexId);}finally{await fs.rm(state,{recursive:true,force:true});}});
test('corrupt active index rolls back to independently validated LKG with audit',async()=>{const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-lkg-'));try{const one=await stagedIndex(state,'one');await activator.activate({stateDir:state,stagingDir:one.dir,buildId:'one'});const two=await stagedIndex(state,'two');await activator.activate({stateDir:state,stagingDir:two.dir,buildId:'two'});await fs.appendFile(path.join(state,'indexes',two.indexId.replace(':','-'),'index.json'),'corrupt');const events=[];const opened=await reader.open({stateDir:state,expectedPolicyId:'p',expectedPolicyHash:'ph',transactionId:'lkg-tx',audit:e=>events.push(e)});assert.equal(opened.indexId,one.indexId);assert.ok(events.some(e=>e.event==='LKG_ROLLBACK'));assert.ok(events.every(e=>e.component&&e.schemaVersion&&'outcome' in e));}finally{await fs.rm(state,{recursive:true,force:true});}});
test('invalid LKG and tampered activation pointer fail with INDEX_UNAVAILABLE',async()=>{const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-invalid-lkg-'));try{const one=await stagedIndex(state,'one');await activator.activate({stateDir:state,stagingDir:one.dir,buildId:'one'});const activePath=path.join(state,'active.json');const pointer=JSON.parse(await fs.readFile(activePath,'utf8'));await fs.writeFile(activePath,ids.canonical({...pointer,indexHash:'tampered'}));await assert.rejects(()=>reader.open({stateDir:state,expectedPolicyId:'p',expectedPolicyHash:'ph'}),e=>e.code===c.STATES.INDEX_UNAVAILABLE);await fs.writeFile(path.join(state,'previous.json'),ids.canonical({...pointer,indexHash:'tampered'}));await assert.rejects(()=>reader.open({stateDir:state,expectedPolicyId:'p',expectedPolicyHash:'ph'}),e=>e.code===c.STATES.INDEX_UNAVAILABLE);}finally{await fs.rm(state,{recursive:true,force:true});}});
test('revoked candidate cannot validate as active or LKG',async()=>{const state=await fs.mkdtemp(path.join(os.tmpdir(),'sinbad-revoked-lkg-'));try{const revoked=await stagedIndex(state,'revoked',[{editionId:'ed:r',sourceId:'src:r',documentId:'doc:r',status:'revoked'}]);await assert.rejects(()=>integrity.validate(revoked.dir),e=>e.code===c.STATES.EDITION_REVOKED);}finally{await fs.rm(state,{recursive:true,force:true});}});
