'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const authorization=require('../adapters/trusted-terminal-rollout-recovery-authorization.js');const audits=require('../adapters/trusted-rollout-recovery-authorization-audit.js');
const actor='d'.repeat(64),hash='e'.repeat(64);let time=1000;
function journal(){return {version:'sinbad-supabase-rollout-activation-journal/3J-v1',durable:true,inspect:async()=>({status:'FOUND',state:{status:'APPLIED'}}),settle:async()=>({status:'SETTLED'})};}
function audit(overrides={}){return audits.create({durable:true,append:async()=>true,...overrides});}function ready(overrides={}){return {version:authorization.EXPECTED_READINESS_VERSION,check:async()=>({version:authorization.EXPECTED_READINESS_VERSION,status:'AUTHORIZATION_AUDIT_READINESS_READY',reasonCode:null}),...overrides};}function create(overrides={}){return authorization.create({actorHash:actor,recoveryPurpose:'operator-rollout-recovery',authorizationTtlMs:5000,authorizationTimeoutMs:5000,now:()=>time,authorize:async()=>true,authorizationAudit:audit(),auditReadiness:ready(),activationJournal:journal(),resolve:async()=>'PENDING',recoveryTimeoutMs:5000,...overrides});}
test('requires trusted bounded purpose-bound construction',()=>{assert.throws(()=>authorization.create(),/authorize/u);for(const value of [{actorHash:'bad'},{recoveryPurpose:''},{authorizationTtlMs:999},{authorizationTimeoutMs:999},{now:null}])assert.throws(()=>create(value),/policy/u);const gate=create();assert.deepEqual(Object.keys(gate),['issue','recover']);assert.ok(Object.isFrozen(gate));});
test('exact operator approval issues a content-minimized authorization and recovers once',async()=>{time=1000;let seen;const gate=create({authorize:async input=>{seen=input;return true;}}),value=await gate.issue(hash);assert.equal(value.status,'ROLLOUT_RECOVERY_AUTHORIZED');assert.match(value.authorizationHash,/^[a-f0-9]{64}$/u);assert.equal('attestationHash' in value,false);assert.deepEqual(seen,{actorHash:actor,attestationHash:hash,purpose:'operator-rollout-recovery'});assert.ok(Object.isFrozen(seen));assert.equal((await gate.recover(value)).status,'ROLLOUT_RECOVERY_APPLIED');assert.equal((await gate.recover(value)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');});
test('denial non-boolean exception and invalid hash never issue authorization',async()=>{time=1000;for(const authorize of [async()=>false,async()=>1,async()=>{throw new Error('denied');}])assert.equal((await create({authorize}).issue(hash)).reasonCode,'OPERATOR_AUTHORIZATION_DENIED');assert.equal((await create().issue('bad')).reasonCode,'AUTHORIZATION_HASH_INVALID');});
test('copies proxies expiry clock rollback and other instances fail closed',async()=>{time=1000;const gate=create(),value=await gate.issue(hash);for(const candidate of [{...value},structuredClone(value),new Proxy(value,{})])assert.equal((await gate.recover(candidate)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');assert.equal((await create().recover(value)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');time=6000;assert.equal((await gate.recover(value)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');time=1000;const rollback=create(),fresh=await rollback.issue(hash);time=999;assert.equal((await rollback.recover(fresh)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');});
test('authorization is consumed before recovery and cannot replay after downstream failure',async()=>{time=1000;let inspections=0;const gate=create({activationJournal:{...journal(),inspect:async()=>{inspections++;return {status:'UNAVAILABLE',state:null};}}}),value=await gate.issue(hash);assert.equal((await gate.recover(value)).status,'ROLLOUT_RECOVERY_BLOCKED');assert.equal((await gate.recover(value)).reasonCode,'RECOVERY_AUTHORIZATION_DENIED');assert.equal(inspections,1);});
test('concurrent recovery consumes the authorization before the first await',async()=>{time=1000;let release,inspections=0;const wait=new Promise(done=>{release=done;}),gate=create({activationJournal:{...journal(),inspect:async()=>{inspections++;await wait;return {status:'FOUND',state:{status:'APPLIED'}};}}}),value=await gate.issue(hash),first=gate.recover(value),second=gate.recover(value);release();const results=await Promise.all([first,second]);assert.equal(inspections,1);assert.equal(results.filter(x=>x.status==='ROLLOUT_RECOVERY_APPLIED').length,1);assert.equal(results.filter(x=>x.reasonCode==='RECOVERY_AUTHORIZATION_DENIED').length,1);});
test('audit persistence is mandatory before approval or denial returns',async()=>{time=1000;for(const append of [async()=>false,async()=>{throw new Error('offline');}]){const gate=create({authorizationAudit:audit({append})});assert.equal((await gate.issue(hash)).reasonCode,'AUTHORIZATION_AUDIT_REQUIRED');}assert.throws(()=>create({authorizationAudit:null}),/authorizationAudit/u);});
test('audit record rejection malformed success and wrong contract fail closed',async()=>{time=1000;for(const record of [async()=>{throw new Error('offline');},async()=>({status:'RECORDED',eventHash:'bad'})])assert.equal((await create({authorizationAudit:{version:authorization.EXPECTED_AUDIT_VERSION,durable:true,record}}).issue(hash)).reasonCode,'AUTHORIZATION_AUDIT_REQUIRED');for(const authorizationAudit of [{version:'wrong',durable:true,record(){}},{version:authorization.EXPECTED_AUDIT_VERSION,durable:false,record(){}},{version:authorization.EXPECTED_AUDIT_VERSION,durable:true,record:null}])assert.throws(()=>create({authorizationAudit}),/authorizationAudit/u);});
test('authorization audit is content-minimized deterministic and frozen',async()=>{time=1000;const events=[],gate=create({authorizationAudit:audit({append:async event=>{events.push(event);return true;}})});assert.equal((await gate.issue(hash)).status,'ROLLOUT_RECOVERY_AUTHORIZED');assert.equal(events.length,1);assert.deepEqual(Object.keys(events[0]).sort(),['actorHash','attestationHash','decidedAt','decision','eventHash','purposeHash','version']);assert.equal(events[0].decision,'AUTHORIZED');assert.ok(Object.isFrozen(events[0]));assert.match(events[0].eventHash,/^[a-f0-9]{64}$/u);});
test('audit readiness blocks before the operator authorization hook',async()=>{time=1000;let calls=0;const gate=create({auditReadiness:ready({check:async()=>({version:authorization.EXPECTED_READINESS_VERSION,status:'AUTHORIZATION_AUDIT_READINESS_BLOCKED',reasonCode:'AUDIT_SCAN_INCOMPLETE'})}),authorize:async()=>{calls++;return true;}}),value=await gate.issue(hash);assert.equal(value.status,'ROLLOUT_RECOVERY_AUTHORIZATION_BLOCKED');assert.equal(calls,0);assert.throws(()=>create({auditReadiness:null}),/auditReadiness/u);});
