'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const receipts=require('../delivery/terminal-delivery-receipt.js');const receiptVerifier=require('../verification/terminal-delivery-receipt-verifier.js');const closure=require('../delivery/single-use-terminal-closure.js');const verifier=require('../verification/terminal-closure-verifier.js');
let sequence=0;function fixture(outcome='DELIVERED'){const n=++sequence,answer=`Kapanış doğrulaması ${n}`,transactionId=`tx-2s-${n}`,sessionId='session-a',channelId='atlas-ui',attemptId=`attempt-${n}`,closureId=`closure-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse})),authorization=authorizer.authorize(delivery,{sessionId,channelId,deliveryNonce:`nonce-${n}`,now:()=>1000}),receipt=receipts.record(authorization,{outcome,sessionId,channelId,attemptId}),verification=receiptVerifier.verify(receipt,{transactionId,sessionId,channelId,outcome,attemptId}),closed=closure.close(verification,{transactionId,sessionId,channelId,outcome,attemptId,closureId});return {closure:closed,expected:{closureId,outcome},answer};}
test('independently verifies a bound closure with a minimal deterministic result',()=>{const f=fixture(),result=verifier.verify(f.closure,f.expected),snapshot=closure.boundSnapshot(f.closure,f.expected),manifest={version:verifier.VERIFICATION_VERSION,verifierVersion:verifier.VERIFIER_VERSION,status:'TERMINAL_CLOSURE_VERIFIED',closureId:snapshot.closureId,outcome:snapshot.outcome,sourceCount:snapshot.sourceCount,verificationHash:snapshot.verificationHash,closureHash:snapshot.closureHash};assert.equal(result.status,'TERMINAL_CLOSURE_VERIFIED');assert.equal(result.closureVerificationHash,verifier.sha256(verifier.canonical(manifest)));assert.equal(JSON.stringify(result).includes(f.answer),false);for(const key of ['transactionId','sessionId','channelId','attemptId','closureId','verificationHash','answer','sources'])assert.equal(key in result,false);assert.equal(verifier.isAuthenticResult(result),true);assert.ok(Object.isFrozen(result));});
test('verifies FAILED closure outcome',()=>{const f=fixture('FAILED'),result=verifier.verify(f.closure,f.expected);assert.equal(result.status,'TERMINAL_CLOSURE_VERIFIED');assert.equal(result.outcome,'FAILED');});
test('pins Phase 2R and binds every closure verification expectation',()=>{const f=fixture(),value=verifier.verify(f.closure,f.expected);assert.equal(verifier.EXPECTED_CLOSURE_VERSION,closure.CLOSURE_VERSION);assert.equal(verifier.isBound(value,f.expected),true);assert.ok(Object.isFrozen(verifier.boundSnapshot(value,f.expected)));for(const expected of [{closureId:'other',outcome:f.expected.outcome},{closureId:f.expected.closureId,outcome:'FAILED'},{}])assert.equal(verifier.isBound(value,expected),false);for(const candidate of [{...value,status:'other'},{...value,closureHash:'0'.repeat(64)},{...value,sourceCount:2}])assert.equal(verifier.isBound(candidate,f.expected),false);});
test('one closure can produce only one verification result',()=>{const f=fixture();assert.equal(verifier.verify(f.closure,f.expected).status,'TERMINAL_CLOSURE_VERIFIED');const replay=verifier.verify(f.closure,f.expected);assert.equal(replay.status,'TERMINAL_CLOSURE_INVALID');assert.equal(verifier.isAuthenticResult(replay),false);});
test('copies clones proxies and retargeting fail closed uniformly',()=>{const f=fixture(),cases=[[{...f.closure},f.expected],[structuredClone(f.closure),f.expected],[new Proxy(f.closure,{}),f.expected],[f.closure,{...f.expected,closureId:'other'}],[f.closure,{...f.expected,outcome:'FAILED'}],[f.closure,{}]];for(const [value,expected] of cases){const result=verifier.verify(value,expected);assert.equal(result.status,'TERMINAL_CLOSURE_INVALID');assert.equal(result.reasonCode,'TERMINAL_CLOSURE_VERIFICATION_DENIED');assert.equal(result.closureHash,null);}});
test('blocked closures are not authentic and cannot verify',()=>{const blocked=closure.close({},{}),result=verifier.verify(blocked,{});assert.equal(closure.isAuthenticClosure(blocked),false);assert.equal(result.status,'TERMINAL_CLOSURE_INVALID');});
test('closure verifier invokes no model expert navigation or network',()=>{const f=fixture();let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(verifier.verify(f.closure,f.expected).status,'TERMINAL_CLOSURE_VERIFIED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
