'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const readiness=require('../adapters/supabase-terminal-recovery-readiness.js');
const {createHash}=require('node:crypto');const audit=require('../adapters/supabase-terminal-recovery-audit.js');
const actor='b'.repeat(64),now=()=>Date.parse('2026-08-13T00:02:00Z');
function create(handler,overrides={}){return readiness.create({serviceRole:true,actorHash:actor,client:{rpc:handler},limit:10,slaMs:120000,pageSize:10,maxEvents:100,now,...overrides});}
function auditRow(id=1){const time=1786615200000,value={id,event_time_ms:time,claim_key:'a'.repeat(64),actor_hash:actor,action:'OPERATOR_QUARANTINED',reason_code:'PROCESS_CRASH',created_at:new Date(time).toISOString()};value.event_hash=createHash('sha256').update([audit.AUDIT_VERSION,value.id,value.event_time_ms,value.claim_key,value.actor_hash,value.action,value.reason_code].join('\n')).digest('hex');return value;}
test('requires trusted construction and bounded explicit policy',()=>{assert.throws(()=>readiness.create(),/service-role client/u);const handler=async()=>({data:true,error:null}),base={serviceRole:true,actorHash:actor,client:{rpc:handler},limit:10,slaMs:120000,pageSize:10,maxEvents:100};assert.throws(()=>readiness.create({...base,serviceRole:false}),/service-role client/u);assert.throws(()=>readiness.create({...base,actorHash:'bad'}),/operator identity/u);for(const value of [{limit:undefined},{pageSize:undefined},{maxEvents:undefined},{slaMs:999},{limit:0},{limit:501},{pageSize:0},{pageSize:501},{pageSize:10,maxEvents:9},{maxEvents:100001},{now:'clock'}])assert.throws(()=>readiness.create({...base,...value}),/bounds/u);assert.deepEqual(Object.keys(readiness),['READINESS_VERSION','create']);});
test('returns ready only after healthy recovery and a complete audit scan',async()=>{const calls=[],gate=create(async(name,args)=>{calls.push([name,args]);if(name.startsWith('verify_'))return {data:true,error:null};if(name==='list_expired_terminal_delivery_claims')return {data:[],error:null};return {data:[],error:null};}),result=await gate.check();assert.equal(result.status,'RECOVERY_READINESS_READY');assert.equal(result.reasonCode,null);assert.equal(result.expiredCount,0);assert.equal(result.auditEventCount,0);assert.equal(result.auditPageCount,1);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(gate));assert.deepEqual(calls.map(x=>x[0]),['verify_terminal_recovery_access','list_expired_terminal_delivery_claims','verify_terminal_recovery_audit_access','list_terminal_recovery_audit']);});
test('blocks before audit scan when recovery is unavailable or breaches SLA',async()=>{for(const [rows,reason] of [[null,'RECOVERY_STORE_UNAVAILABLE'],[[{claim_key:'a'.repeat(64),claimed_at:'2026-08-13T00:00:00Z',lease_expires_at:'2026-08-13T00:00:00Z'}],'EXPIRED_CLAIM_SLA_EXCEEDED']]){const calls=[],gate=create(async name=>{calls.push(name);if(name==='verify_terminal_recovery_access')return {data:true,error:null};return rows===null?{data:null,error:{message:'offline'}}:{data:rows,error:null};},{slaMs:30000}),result=await gate.check();assert.equal(result.status,'RECOVERY_READINESS_BLOCKED');assert.equal(result.reasonCode,reason);assert.equal(calls.some(name=>name.includes('audit')),false);}});
test('blocks on incomplete unavailable or invalid audit scan without exposing rows',async()=>{const gate=create(async(name)=>{if(name.startsWith('verify_'))return {data:true,error:null};if(name==='list_expired_terminal_delivery_claims')return {data:[],error:null};return {data:null,error:{message:'offline'}};}),result=await gate.check();assert.equal(result.status,'RECOVERY_READINESS_BLOCKED');assert.equal(result.reasonCode,'AUDIT_STORE_UNAVAILABLE');assert.equal('events'in result,false);assert.equal('claims'in result,false);});
test('converts rejected recovery and audit RPC promises into blocked reports',async()=>{const recoveryFailure=await create(async()=>{throw new Error('network');}).check();assert.equal(recoveryFailure.reasonCode,'RECOVERY_CHECK_EXCEPTION');let recoveryDone=false;const auditFailure=await create(async name=>{if(name==='verify_terminal_recovery_access')return {data:true,error:null};if(name==='list_expired_terminal_delivery_claims'){recoveryDone=true;return {data:[],error:null};}throw new Error('network');}).check();assert.equal(recoveryDone,true);assert.equal(auditFailure.reasonCode,'AUDIT_SCAN_EXCEPTION');assert.equal(auditFailure.status,'RECOVERY_READINESS_BLOCKED');});
test('blocks incomplete and integrity-failed audit scans with stable codes',async()=>{for(const [rows,reason] of [[[auditRow()],'AUDIT_SCAN_LIMIT_REACHED'],[[{...auditRow(),event_hash:'c'.repeat(64)}],'AUDIT_EVENT_HASH_MISMATCH']]){const gate=create(async name=>{if(name.startsWith('verify_'))return {data:true,error:null};if(name==='list_expired_terminal_delivery_claims')return {data:[],error:null};return {data:rows,error:null};},{pageSize:1,maxEvents:1}),result=await gate.check();assert.equal(result.status,'RECOVERY_READINESS_BLOCKED');assert.equal(result.reasonCode,reason);assert.equal('events'in result,false);}});
test('unknown failure counters stay null instead of resembling an empty ready state',async()=>{const result=await create(async()=>{throw new Error('offline');}).check();assert.equal(result.expiredCount,null);assert.equal(result.auditEventCount,null);assert.equal(result.auditPageCount,null);});
test('ready preserves consistent empty-scan watermark invariants',async()=>{const gate=create(async name=>{if(name.startsWith('verify_'))return {data:true,error:null};if(name==='list_expired_terminal_delivery_claims')return {data:[],error:null};return {data:[],error:null};}),ready=await gate.check();assert.equal(ready.status,'RECOVERY_READINESS_READY');assert.equal(ready.auditWatermarkId,null);assert.equal(ready.auditPageCount,1);});
