'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');
function fixture(){const answer='Güvenlik şartı',answerHash=projector.sha256(answer),sealInput={transactionId:'tx-2m',query:'Güvenlik şartı',answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:['e1']},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:['e1'],citations:[{id:'c1',claimId:'internal-claim',evidenceId:'e1',title:'SOLAS',location:{section:'II-2',page:12,chunk:'7',uri:null},publishedAt:'2026-01-01',version:'2026',authority:'authoritative',verified:true,metadataComplete:true,provenance:{policyHash:'secret-internal-hash'}}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer});return {answerRelease,groundedAnswer};}
test('projects only release-bound public answer and safe citation fields',()=>{const value=fixture(),result=projector.project(value,{answerReleaseGate:releaseGate});assert.equal(result.status,'PUBLIC_RESPONSE_READY');assert.equal(result.renderingPolicy,'TEXT_ONLY_NO_HTML');assert.equal(result.contentType,'text/plain; charset=utf-8');assert.equal(result.answer,'Güvenlik şartı');assert.equal(result.citations[0].title,'SOLAS');assert.equal('claimId' in result.citations[0],false);assert.equal('evidenceId' in result.citations[0],false);assert.equal('provenance' in result.citations[0],false);assert.equal(JSON.stringify(result).includes('secret-internal-hash'),false);assert.equal(projector.isBound(result,result),true);assert.ok(Object.isFrozen(result.citations[0].location));});
test('copied response and replay across answer release or citation fields fail',()=>{const value=fixture(),result=projector.project(value,{answerReleaseGate:releaseGate});assert.equal(projector.isBound({...result},result),false);for(const mutation of [{answer:'Değişmiş'},{answerHash:'b'.repeat(64)},{releaseHash:'b'.repeat(64)},{citations:[]}])assert.equal(projector.isBound(result,{...result,...mutation}),false);});
test('forged release altered answer duplicate citations and unverified citations block projection',()=>{const value=fixture(),citation=value.groundedAnswer.citations[0],cases=[{...value,answerRelease:{...value.answerRelease}},{...value,groundedAnswer:{...value.groundedAnswer,answer:'Değişmiş'}},{...value,groundedAnswer:{...value.groundedAnswer,citations:[citation,citation]}},{...value,groundedAnswer:{...value.groundedAnswer,citations:[{...citation,verified:false}]}}];for(const candidate of cases){const result=projector.project(candidate,{answerReleaseGate:releaseGate});assert.equal(result.status,'PUBLIC_RESPONSE_BLOCKED');assert.equal(result.responseHash,null);}});
test('unsafe citation URI schemes block public projection',()=>{const value=fixture(),citation=value.groundedAnswer.citations[0];for(const uri of ['javascript:alert(1)','data:text/html,bad','file:///secret','http://insecure.example']){const groundedAnswer={...value.groundedAnswer,citations:[{...citation,location:{...citation.location,uri}}]},result=projector.project({...value,groundedAnswer},{answerReleaseGate:releaseGate});assert.equal(result.status,'PUBLIC_RESPONSE_BLOCKED');assert.equal(result.citations[0].location.uri,null);}});
test('unsafe control characters in public text block projection',()=>{const value=fixture(),citation=value.groundedAnswer.citations[0];for(const mutation of [{answer:`${value.groundedAnswer.answer}\u0000`},{citations:[{...citation,title:'SOLAS\u001b[31m'}]}]){const groundedAnswer={...value.groundedAnswer,...mutation},result=projector.project({...value,groundedAnswer},{answerReleaseGate:releaseGate});assert.equal(result.status,'PUBLIC_RESPONSE_BLOCKED');}});
test('projector invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(projector.project(fixture(),{answerReleaseGate:releaseGate}).status,'PUBLIC_RESPONSE_READY');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
