'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const runtime=require('../adapters/trusted-rollout-recovery-runtime.js');
const actor='d'.repeat(64),hash='e'.repeat(64);let time=1000;
function options(rpc,overrides={}){return {serviceRole:true,client:{rpc},actorHash:actor,recoveryPurpose:'operator-rollout-recovery',authorizationTtlMs:5000,authorizationTimeoutMs:5000,now:()=>time,authorize:async()=>true,resolve:async()=>'PENDING',recoveryTimeoutMs:5000,auditPageSize:10,auditMaxEvents:100,...overrides};}
function healthy(){return async(name,args)=>{if(name==='verify_rollout_recovery_authorization_audit_access')return {data:true,error:null};if(name==='list_rollout_recovery_authorization_audit')return {data:[],error:null};if(name==='append_rollout_recovery_authorization_audit')return {data:'RECORDED',error:null};if(name==='inspect_terminal_rollout_activation')return {data:[{status:'APPLIED',started_at:'2026-08-13T00:00:00Z',updated_at:'2026-08-13T00:01:00Z'}],error:null};throw new Error(`unexpected ${name} ${JSON.stringify(args)}`);};}
test('constructs only the exact bounded service-role runtime and exposes two operations',()=>{assert.throws(()=>runtime.create(),/service-role/u);assert.throws(()=>runtime.create(options(healthy(),{auditPageSize:0})),/policy/u);const value=runtime.create(options(healthy()));assert.deepEqual(Object.keys(value),['version','issue','recover']);assert.equal(value.version,runtime.RUNTIME_VERSION);assert.ok(Object.isFrozen(value));assert.ok(Object.isFrozen(runtime.EXPECTED));});
test('wires readiness authorization audit and restart recovery without exposing internals',async()=>{time=1000;const calls=[],rpc=async(name,args)=>{calls.push([name,args]);return healthy()(name,args);},value=runtime.create(options(rpc)),authorization=await value.issue(hash);assert.equal(authorization.status,'ROLLOUT_RECOVERY_AUTHORIZED');assert.deepEqual(calls.map(x=>x[0]),['verify_rollout_recovery_authorization_audit_access','list_rollout_recovery_authorization_audit','append_rollout_recovery_authorization_audit']);assert.equal((await value.recover(authorization)).status,'ROLLOUT_RECOVERY_APPLIED');assert.equal(calls.at(-1)[0],'inspect_terminal_rollout_activation');});
test('audit capability denial blocks before operator policy and append',async()=>{time=1000;let authorizations=0,appends=0;const rpc=async name=>{if(name==='verify_rollout_recovery_authorization_audit_access')return {data:false,error:null};if(name==='append_rollout_recovery_authorization_audit')appends++;return {data:[],error:null};},value=runtime.create(options(rpc,{authorize:async()=>{authorizations++;return true;}})),result=await value.issue(hash);assert.equal(result.status,'ROLLOUT_RECOVERY_AUTHORIZATION_BLOCKED');assert.equal(authorizations,0);assert.equal(appends,1);});
test('RPC errors and partial runtime policies fail closed',async()=>{time=1000;for(const rpc of [async()=>{throw new Error('offline');},async()=>({data:null,error:{message:'offline'}})]){let authorizations=0;const value=runtime.create(options(rpc,{authorize:async()=>{authorizations++;return true;}}));assert.equal((await value.issue(hash)).status,'ROLLOUT_RECOVERY_AUTHORIZATION_BLOCKED');assert.equal(authorizations,0);}for(const changed of [{authorize:null},{resolve:null},{now:null},{auditMaxEvents:9}])assert.throws(()=>runtime.create(options(healthy(),changed)),/required|policy/u);});
test('runtime remains internal to the package export map',()=>{assert.equal(require('../package.json').exports['./trusted-rollout-recovery-runtime'],undefined);assert.throws(()=>require('@sinbad-ai/core-terminal-delivery/trusted-rollout-recovery-runtime'),error=>error&&error.code==='ERR_PACKAGE_PATH_NOT_EXPORTED');});
