'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const contract=require('../adapters/durable-idempotency-store.js');const supabase=require('../adapters/supabase-durable-idempotency-store.js');
const key='a'.repeat(64),token='123e4567-e89b-42d3-a456-426614174000';
function client(handler){return {rpc:handler};}
const options=(handler,extra={})=>({serviceRole:true,claimLeaseMs:30000,client:client(handler),...extra});
test('creates a versioned durable store only from a bounded trusted client configuration',()=>{assert.throws(()=>supabase.create(),/service-role client/u);assert.throws(()=>supabase.create({client:client(()=>{}),claimLeaseMs:30000}),/serviceRole confirmation/u);assert.throws(()=>supabase.create(options(()=>{}, {claimLeaseMs:999})),/between 1000 and 900000/u);const store=supabase.create(options(async()=>({data:null,error:null})));assert.equal(store.version,contract.STORE_VERSION);assert.equal(store.durable,true);assert.equal(store.claimLeaseMs,30000);assert.deepEqual(Object.keys(supabase),['create']);assert.ok(Object.isFrozen(store));assert.ok(Object.isFrozen(contract.validate(store)));});
test('claims with the exact RPC and retains the fenced lease token internally',async()=>{const calls=[],store=supabase.create(options(async(name,args)=>{calls.push([name,args]);return {data:token,error:null};}));assert.equal(await store.claim(key),true);assert.deepEqual(calls,[['claim_terminal_delivery',{p_claim_key:key,p_lease_ms:30000}]]);assert.equal('tokens' in store,false);assert.equal(await store.claim(key),false);assert.equal(calls.length,1);});
test('settles only with the matching internally retained token and minimal summary',async()=>{const calls=[],store=supabase.create(options(async(name,args)=>{calls.push([name,args]);return name==='claim_terminal_delivery'?{data:token,error:null}:{data:true,error:null};})),summary=Object.freeze({status:'TRUSTED_TERMINAL_DELIVERY_APPLIED',terminalState:'DELIVERY_SUCCEEDED',outcome:'DELIVERED',transitionHash:'b'.repeat(64)});assert.equal(await store.settle(key,summary),false);assert.equal(await store.claim(key),true);assert.equal(await store.settle(key,summary),true);assert.deepEqual(calls[1],['settle_terminal_delivery',{p_claim_key:key,p_lease_token:token,p_summary:summary}]);assert.equal(await store.settle(key,summary),false);});
test('definitive settlement denial clears the local fence and delegates recovery to the RPC',async()=>{let claims=0;const store=supabase.create(options(async name=>name==='claim_terminal_delivery'?{data:++claims===1?token:'223e4567-e89b-42d3-a456-426614174000',error:null}:{data:false,error:null})),summary={status:'TRUSTED_TERMINAL_DELIVERY_APPLIED',terminalState:'DELIVERY_SUCCEEDED',outcome:'DELIVERED',transitionHash:'b'.repeat(64)};assert.equal(await store.claim(key),true);assert.equal(await store.settle(key,summary),false);assert.equal(await store.claim(key),true);assert.equal(claims,2);});
test('ambiguous settlement transport failure retains the token for settle-only retry',async()=>{let claims=0,settles=0;const store=supabase.create(options(async name=>{if(name==='claim_terminal_delivery'){claims++;return {data:token,error:null};}settles++;return settles===1?{data:null,error:{message:'timeout'}}:{data:true,error:null};})),summary={status:'TRUSTED_TERMINAL_DELIVERY_APPLIED',terminalState:'DELIVERY_SUCCEEDED',outcome:'DELIVERED',transitionHash:'b'.repeat(64)};assert.equal(await store.claim(key),true);assert.equal(await store.settle(key,summary),false);assert.equal(await store.claim(key),false);assert.equal(await store.settle(key,summary),true);assert.equal(claims,1);assert.equal(settles,2);});
test('invalid summaries RPC errors malformed tokens denials and invalid keys fail closed',async()=>{for(const response of [{data:null,error:null},{data:'not-a-token',error:null},{data:token,error:{message:'offline'}}]){let calls=0;const store=supabase.create(options(async()=>{calls++;return response;}));assert.equal(await store.claim(key),false);assert.equal(calls,1);}const store=supabase.create(options(async()=>({data:token,error:null})));assert.equal(await store.claim('bad'),false);assert.equal(await store.settle('bad',{}),false);assert.equal(await store.claim(key),true);for(const summary of [{},{status:'TRUSTED_TERMINAL_DELIVERY_APPLIED'},{status:'TRUSTED_TERMINAL_DELIVERY_BLOCKED',outcome:'DELIVERED',stage:'COMPLETION_DENIED'},{status:'TRUSTED_TERMINAL_DELIVERY_APPLIED',terminalState:'DELIVERY_SUCCEEDED',outcome:'DELIVERED',transitionHash:'b'.repeat(64),extra:true}])assert.equal(await store.settle(key,summary),false);});
test('migration enforces RLS service-role-only RPCs fencing expiry and bounded summaries',()=>{const sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260813_terminal_delivery_idempotency.sql'),'utf8');for(const pattern of [/create extension if not exists pgcrypto/iu,/enable row level security/iu,/revoke all on public\.terminal_delivery_idempotency from public, anon, authenticated/iu,/grant execute on function public\.claim_terminal_delivery\(text, integer\) to service_role/iu,/lease_token = p_lease_token/iu,/lease_expires_at > clock_timestamp\(\)/iu,/lease_expires_at <= clock_timestamp\(\)/iu,/pg_column_size\(p_summary\) > 4096/iu,/not \(p_summary \? 'outcome'\)/u,/TRUSTED_TERMINAL_DELIVERY_APPLIED/u,/TRUSTED_TERMINAL_DELIVERY_BLOCKED/u,/v_token uuid;/u])assert.match(sql,pattern);assert.doesNotMatch(sql,/force row level security/iu);assert.doesNotMatch(sql,/v_token uuid :=/u);});
