'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');
const audit=require('../adapters/supabase-terminal-recovery-audit.js'),actor='b'.repeat(64);
function row(id,overrides={}){const time=1786615200000+id,value={id,event_time_ms:time,claim_key:id.toString(16).padStart(64,'0'),actor_hash:actor,action:'OPERATOR_QUARANTINED',reason_code:'PROCESS_CRASH',created_at:new Date(time).toISOString(),...overrides};value.event_hash=createHash('sha256').update([audit.AUDIT_VERSION,value.id,value.event_time_ms,value.claim_key,value.actor_hash,value.action,value.reason_code].join('\n')).digest('hex');return value;}
function client(pages,verify=true){let index=0;return audit.create({serviceRole:true,client:{async rpc(name){if(name==='verify_terminal_recovery_audit_access')return {data:verify,error:null};const value=pages[index++];return value instanceof Error?{data:null,error:value}:{data:value,error:null};}}});}
test('scans descending pages to a bounded immutable completion summary',async()=>{const result=await client([[row(5),row(4)],[row(3),row(2)],[row(1)],[]]).scan({pageSize:2,maxEvents:10});assert.deepEqual(result,{version:audit.SCAN_VERSION,status:'AUDIT_SCAN_COMPLETE',reasonCode:null,eventCount:5,pageCount:4,watermarkId:5});assert.ok(Object.isFrozen(result));});
test('empty audit is a complete zero-event scan',async()=>{const result=await client([[]]).scan({pageSize:2,maxEvents:10});assert.equal(result.status,'AUDIT_SCAN_COMPLETE');assert.equal(result.eventCount,0);assert.equal(result.watermarkId,null);});
test('fails closed on duplicate ascending or tampered events without returning partial rows',async()=>{const bad=row(3);bad.event_hash='c'.repeat(64);for(const pages of [[[row(4),row(3)],[row(3)]],[[row(4),row(3)],[row(5)]],[[row(4),row(3)],[bad]]]){const result=await client(pages).scan({pageSize:2,maxEvents:10});assert.equal(result.status,'AUDIT_SCAN_INTEGRITY_FAILED');assert.equal('events'in result,false);}});
test('reports bounded incomplete scans and unavailable capabilities',async()=>{const limited=await client([[row(4),row(3)],[row(2),row(1)]]).scan({pageSize:2,maxEvents:4});assert.equal(limited.status,'AUDIT_SCAN_INCOMPLETE');assert.equal(limited.reasonCode,'AUDIT_SCAN_LIMIT_REACHED');assert.equal((await client([],false).scan({pageSize:2,maxEvents:4})).reasonCode,'AUDIT_CAPABILITY_DENIED');});
test('never counts beyond a non-multiple event budget',async()=>{const result=await client([[row(6),row(5)],[row(4),row(3)]]).scan({pageSize:2,maxEvents:3});assert.equal(result.status,'AUDIT_SCAN_INCOMPLETE');assert.equal(result.eventCount,3);});
test('does not trust a short page as EOF and rechecks capability per page',async()=>{const calls=[],pages=[[row(2)],[]],value=audit.create({serviceRole:true,client:{async rpc(name){calls.push(name);return name==='verify_terminal_recovery_audit_access'?{data:true,error:null}:{data:pages.shift(),error:null};}}}),result=await value.scan({pageSize:2,maxEvents:4});assert.equal(result.status,'AUDIT_SCAN_COMPLETE');assert.deepEqual(calls,['verify_terminal_recovery_audit_access','list_terminal_recovery_audit','verify_terminal_recovery_audit_access','list_terminal_recovery_audit']);});
test('validates the rest of a budget-ending page before reporting incomplete',async()=>{const duplicate=row(3),result=await client([[row(4),duplicate],[duplicate,row(2)]]).scan({pageSize:2,maxEvents:3});assert.equal(result.status,'AUDIT_SCAN_INTEGRITY_FAILED');assert.equal(result.reasonCode,'AUDIT_ORDER_INVALID');});
test('rejects invalid scan budgets before database access',async()=>{let calls=0;const value=audit.create({serviceRole:true,client:{async rpc(){calls++;return {data:true,error:null};}}});for(const input of [{pageSize:0},{pageSize:501},{pageSize:10,maxEvents:9},{pageSize:1,maxEvents:100001}])assert.equal((await value.scan(input)).reasonCode,'AUDIT_INVALID_SCAN_ARGS');assert.equal(calls,0);});
