'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const receipts=require('../delivery/terminal-delivery-receipt.js');const gate=require('../delivery/terminal-completion-gate.js');
let sequence=0;function fixture(outcome='DELIVERED'){const n=++sequence,answer=`Tamamlama yanıtı ${n}`,transactionId=`tx-2v-${n}`,sessionId='session-a',channelId='atlas-ui',attemptId=`attempt-${n}`,closureId=`closure-${n}`,auditId=`audit-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse})),authorization=authorizer.authorize(delivery,{sessionId,channelId,deliveryNonce:`nonce-${n}`,now:()=>1000});return {authorization,context:{transactionId,sessionId,channelId,attemptId,closureId,auditId,outcome},answer};}
test('forces the complete 2P-2U chain and returns one minimal completion',()=>{const f=fixture(),result=gate.complete(f.authorization,f.context),manifest={version:gate.COMPLETION_VERSION,status:'TERMINAL_COMPLETION_CONFIRMED',...f.context,sourceCount:result.sourceCount,auditHash:result.auditHash,auditVerificationHash:result.auditVerificationHash};assert.equal(result.status,'TERMINAL_COMPLETION_CONFIRMED');assert.equal(result.completionHash,gate.sha256(gate.canonical(manifest)));for(const key of ['transactionId','sessionId','channelId','attemptId','closureId','auditId','answer','sources'])assert.equal(key in result,false);assert.equal(JSON.stringify(result).includes(f.answer),false);assert.equal(gate.isAuthenticCompletion(result),true);assert.ok(Object.isFrozen(result));});
test('supports FAILED only as a fully verified terminal completion',()=>{const f=fixture('FAILED'),result=gate.complete(f.authorization,f.context);assert.equal(result.status,'TERMINAL_COMPLETION_CONFIRMED');assert.equal(result.outcome,'FAILED');});
test('authorization and completion chain are single use',()=>{const f=fixture();assert.equal(gate.complete(f.authorization,f.context).status,'TERMINAL_COMPLETION_CONFIRMED');assert.equal(gate.complete(f.authorization,{...f.context,attemptId:'retry',closureId:'retry',auditId:'retry'}).status,'TERMINAL_COMPLETION_BLOCKED');});
test('a legacy pre-consumed authorization cannot bypass or re-enter the mandatory gate',()=>{const f=fixture();assert.equal(receipts.record(f.authorization,f.context).status,'DELIVERY_RECEIPT_RECORDED');const result=gate.complete(f.authorization,f.context);assert.equal(result.status,'TERMINAL_COMPLETION_BLOCKED');assert.equal(gate.isAuthenticCompletion(result),false);});
test('copies proxies and every target mismatch fail closed',()=>{const f=fixture(),cases=[[{...f.authorization},f.context],[new Proxy(f.authorization,{}),f.context],[f.authorization,{...f.context,transactionId:'other'}],[f.authorization,{...f.context,sessionId:'other'}],[f.authorization,{...f.context,channelId:'other'}],[f.authorization,{...f.context,attemptId:'bad\u200bid'}],[f.authorization,{...f.context,closureId:''}],[f.authorization,{...f.context,auditId:''}],[f.authorization,{...f.context,outcome:'PENDING'}],[f.authorization,{}]];for(const [value,context] of cases){const result=gate.complete(value,context);assert.equal(result.status,'TERMINAL_COMPLETION_BLOCKED');assert.equal(result.reasonCode,'TERMINAL_COMPLETION_DENIED');assert.equal(result.completionHash,null);assert.equal(gate.isAuthenticCompletion(result),false);}});
test('no intermediate object can be presented as a terminal completion',()=>{for(const value of [{},Object.freeze({status:'DELIVERY_RECEIPT_RECORDED'}),Object.freeze({status:'TERMINAL_AUDIT_VERIFIED'})])assert.equal(gate.isAuthenticCompletion(value),false);});
test('completion binding covers the full hidden context and rejects public tampering',()=>{const f=fixture(),result=gate.complete(f.authorization,f.context);assert.equal(gate.isBound(result,f.context),true);assert.deepEqual(gate.boundSnapshot(result,f.context),{...f.context,sourceCount:result.sourceCount,auditHash:result.auditHash,auditVerificationHash:result.auditVerificationHash,completionHash:result.completionHash});for(const key of ['transactionId','sessionId','channelId','attemptId','closureId','auditId','outcome'])assert.equal(gate.isBound(result,{...f.context,[key]:key==='outcome'?'FAILED':'other'}),false);for(const key of ['sourceCount','auditHash','auditVerificationHash','completionHash'])assert.equal(gate.isBound(Object.freeze({...result,[key]:key==='sourceCount'?result.sourceCount+1:'tampered'}),f.context),false);});
test('completion gate invokes no model expert navigation or network',()=>{const f=fixture();let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(gate.complete(f.authorization,f.context).status,'TERMINAL_COMPLETION_CONFIRMED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
