'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {createHash}=require('node:crypto');
const audit=require('../adapters/supabase-terminal-recovery-audit.js'),key='a'.repeat(64),actor='b'.repeat(64);
function event(overrides={}){const value={id:7,event_time_ms:1786615200000,claim_key:key,actor_hash:actor,action:'OPERATOR_QUARANTINED',reason_code:'PROCESS_CRASH',created_at:'2026-08-13T10:00:00Z',...overrides};value.event_hash=createHash('sha256').update([audit.AUDIT_VERSION,value.id,value.event_time_ms,value.claim_key,value.actor_hash,value.action,value.reason_code].join('\n'),'utf8').digest('hex');return value;}
function client(handler){return audit.create({serviceRole:true,client:{rpc:handler}});}
test('requires service role and exposes a frozen minimal verifier',()=>{assert.throws(()=>audit.create(),/service-role client/u);assert.throws(()=>audit.create({serviceRole:false,client:{rpc(){}}}),/service-role client/u);const value=client(async()=>({data:true,error:null}));assert.deepEqual(Object.keys(value),['healthCheck','inspect']);assert.ok(Object.isFrozen(value));assert.deepEqual(Object.keys(audit),['AUDIT_VERSION','create']);});
test('returns only verified immutable audit events',async()=>{const calls=[],value=client(async(name,args)=>{calls.push([name,args]);return name==='verify_terminal_recovery_audit_access'?{data:true,error:null}:{data:[event({secret:'no'})],error:null};}),result=await value.inspect({limit:25,beforeId:9});assert.equal(result.status,'AUDIT_PAGE_VALID');assert.equal(result.eventCount,1);assert.equal('secret'in result.events[0],false);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.events));assert.ok(Object.isFrozen(result.events[0]));assert.deepEqual(calls,[['verify_terminal_recovery_audit_access',{}],['list_terminal_recovery_audit',{p_limit:25,p_before_id:9}]]);});
test('fails closed for tampering malformed rows denied capability and store errors',async()=>{const tampered=event();tampered.event_hash='c'.repeat(64);for(const row of [tampered,event({claim_key:'bad'}),event({created_at:'bad'})]){const value=client(async name=>name==='verify_terminal_recovery_audit_access'?{data:true,error:null}:{data:[row],error:null});assert.equal((await value.inspect()).status,'AUDIT_INTEGRITY_FAILED');}assert.equal((await client(async()=>({data:false,error:null})).inspect()).reasonCode,'AUDIT_CAPABILITY_DENIED');const unavailable=client(async name=>name==='verify_terminal_recovery_audit_access'?{data:true,error:null}:{data:null,error:{message:'offline'}});assert.equal((await unavailable.inspect()).reasonCode,'AUDIT_STORE_UNAVAILABLE');});
test('rejects invalid pagination without calling the database',async()=>{let calls=0;const value=client(async()=>{calls++;return {data:true,error:null};});for(const input of [{limit:0},{limit:501},{limit:1.5},{beforeId:0},{beforeId:Number.MAX_SAFE_INTEGER+1}])assert.equal((await value.inspect(input)).reasonCode,'AUDIT_INVALID_INSPECT_ARGS');assert.equal(calls,0);});
test('forward migration adds hashed single-event immutable service-role audit access',()=>{const sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260815_terminal_recovery_audit_integrity.sql'),'utf8');for(const pattern of [/^begin;/iu,/create extension if not exists pgcrypto/iu,/having count\(\*\)>1/iu,/event_time_ms bigint/iu,/event_hash text/iu,/unique \(claim_key\)/iu,/before insert/iu,/before update or delete/iu,/before truncate/iu,/terminal recovery audit rows are immutable/iu,/sinbad-terminal-recovery-audit\/3D-v2/u,/list_terminal_recovery_audit/iu,/verify_terminal_recovery_audit_access/iu,/service role required/iu,/revoke all on function public\.quarantine_expired_terminal_delivery_claim\(text,text,text\) from public, anon, authenticated/iu,/grant execute on function public\.quarantine_expired_terminal_delivery_claim\(text,text,text\) to service_role/iu,/commit;/iu])assert.match(sql,pattern);});
