'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const composer=require('../grounding/verified-answer-composer.js');
function claim(claimId,statement,citationIds=[`citation:${claimId}`]){return Object.freeze({claimId,statement,supported:true,verificationStatus:'CLAIM_SUPPORTED',citationIds:Object.freeze(citationIds)});}
function citation(id,claimId){return Object.freeze({id,claimId});}

test('maps every answer segment to exact UTF-16 offsets, claims, and resolved citations',()=>{const claims=[claim('b','Beta 😀 rule'),claim('a','Alpha rule')],citations=[citation('citation:b','b'),citation('citation:a','a')],result=composer.compose({claims,citations});assert.equal(result.answer,'Alpha rule Beta 😀 rule');assert.equal(result.answerHash,composer.sha256(result.answer));assert.deepEqual(result.segments.map(segment=>[segment.startOffset,segment.endOffset,result.answer.slice(segment.startOffset,segment.endOffset)]),[[0,10,'Alpha rule'],[11,23,'Beta 😀 rule']]);assert.deepEqual(result.segments.map(segment=>segment.claimIds),[['a'],['b']]);assert.deepEqual(result.segments.map(segment=>segment.citationIds),[['citation:a'],['citation:b']]);assert.ok(result.segments.every(segment=>segment.offsetEncoding==='UTF16_CODE_UNIT'));assert.ok(result.segments.every(segment=>segment.statementHash===composer.sha256(result.answer.slice(segment.startOffset,segment.endOffset))));});

test('citation-map output is insertion-order invariant and deeply immutable',()=>{const a=claim('a','Alpha'),b=claim('b','Beta'),ca=citation('citation:a','a'),cb=citation('citation:b','b'),first=composer.compose({claims:[b,a],citations:[cb,ca]}),second=composer.compose({claims:[a,b],citations:[ca,cb]});assert.deepEqual(first,second);assert.ok(Object.isFrozen(first.segments));assert.ok(Object.isFrozen(first.segments[0]));assert.ok(Object.isFrozen(first.segments[0].claimIds));assert.ok(Object.isFrozen(first.segments[0].citationIds));});

test('deduplicated text segment retains all contributing citation lineage',()=>{const result=composer.compose({claims:[claim('b','Same'),claim('a','Same')],citations:[citation('citation:a','a'),citation('citation:b','b')]});assert.equal(result.answer,'Same');assert.equal(result.segments.length,1);assert.deepEqual(result.segments[0].claimIds,['a','b']);assert.deepEqual(result.segments[0].citationIds,['citation:a','citation:b']);});

test('deduplicated segment preserves exact per-claim citation bindings',()=>{const result=composer.compose({claims:[claim('b','Same',['citation:b:2','citation:b:1']),claim('a','Same',['citation:a'])],citations:[citation('citation:a','a'),citation('citation:b:1','b'),citation('citation:b:2','b')]});assert.deepEqual(result.segments[0].bindings,[{claimId:'a',citationIds:['citation:a']},{claimId:'b',citationIds:['citation:b:1','citation:b:2']}]);assert.ok(Object.isFrozen(result.segments[0].bindings));assert.ok(Object.isFrozen(result.segments[0].bindings[0]));assert.ok(Object.isFrozen(result.segments[0].bindings[0].citationIds));});

test('composer bounds claim cardinality before hashing and mapping',()=>{const claims=Array.from({length:composer.MAX_COMPOSER_CLAIMS+1},(_,index)=>claim(`c${index}`,'Same')),citations=claims.map(item=>citation(item.citationIds[0],item.claimId)),result=composer.compose({claims,citations});assert.equal(result.status,'COMPOSITION_INVALID');assert.equal(result.answer,null);assert.deepEqual(result.segments,[]);});

test('invalid composition emits no answer hash or citation segments',()=>{const result=composer.compose({claims:[claim('a','Alpha')],citations:[]});assert.equal(result.status,'COMPOSITION_INVALID');assert.equal(result.answer,null);assert.equal(result.answerHash,null);assert.deepEqual(result.segments,[]);});
