'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const composer=require('../grounding/verified-answer-composer.js');const verifier=require('../verification/answer-citation-map-verifier.js');
function claim(claimId,statement,citationIds=[`citation:${claimId}`]){return Object.freeze({claimId,statement,supported:true,verificationStatus:'CLAIM_SUPPORTED',citationIds:Object.freeze(citationIds)});}
function citation(id,claimId){return Object.freeze({id,claimId});}
function fixture(){const claims=[claim('b','Beta 😀'),claim('a','Alpha')],citations=[citation('citation:b','b'),citation('citation:a','a')],composition=composer.compose({claims,citations});return {answer:composition.answer,composition,claims,citations};}

test('independently verifies the complete answer citation map',()=>{const first=verifier.verify(fixture()),second=verifier.verify(fixture());assert.equal(first.status,'MAP_VERIFIED');assert.equal(first.answerHash,verifier.sha256('Alpha Beta 😀'));assert.deepEqual(first,second);assert.equal(verifier.isAuthenticResult(first),true);assert.equal(verifier.isAuthenticResult({...first}),false);assert.ok(Object.isFrozen(first));});

test('rejects answer, answer hash, segment hash, range, gap, and schema mutations',()=>{const base=fixture(),segment=base.composition.segments[0],mutations=[{...base,answer:`${base.answer}!`},{...base,composition:{...base.composition,answerHash:'0'.repeat(64)}},{...base,composition:{...base.composition,schemaVersion:'forged'}},{...base,composition:{...base.composition,segments:[{...segment,statementHash:'0'.repeat(64)},...base.composition.segments.slice(1)]}},{...base,composition:{...base.composition,segments:[{...segment,endOffset:segment.endOffset+1},...base.composition.segments.slice(1)]}}];for(const mutation of mutations)assert.equal(verifier.verify(mutation).status,'MAP_INVALID');});

test('rejects missing duplicate crossed and laundered claim citation bindings',()=>{const base=fixture(),first=base.composition.segments[0],second=base.composition.segments[1],mutations=[{...base,composition:{...base.composition,claimIds:['a']}},{...base,composition:{...base.composition,segments:[first,{...second,bindings:first.bindings,claimIds:first.claimIds,citationIds:first.citationIds}]}},{...base,citations:[citation('citation:a','b'),citation('citation:b','b')]},{...base,composition:{...base.composition,segments:[{...first,citationIds:['citation:a','citation:b']},second]}}];for(const mutation of mutations)assert.equal(verifier.verify(mutation).status,'MAP_INVALID');});

test('verifier invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(verifier.verify(fixture()).status,'MAP_VERIFIED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
