'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const authorization=require('../adapters/trusted-terminal-rollout-recovery-authorization.js');
const audits=require('../adapters/trusted-rollout-recovery-authorization-audit.js');
const runtime=require('../adapters/trusted-rollout-recovery-runtime.js');
const actor='a'.repeat(64),attestation='b'.repeat(64);
function journal(){return {version:'sinbad-supabase-rollout-activation-journal/3J-v1',durable:true,inspect:async()=>({status:'FOUND',state:{status:'APPLIED'}}),settle:async()=>({status:'SETTLED'})};}
function ready(){return {version:authorization.EXPECTED_READINESS_VERSION,status:'AUTHORIZATION_AUDIT_READINESS_READY',reasonCode:null,eventCount:0,pageCount:1,watermarkId:null};}
function authorizationOptions(check){return {actorHash:actor,recoveryPurpose:'operator-rollout-recovery',authorizationTtlMs:5000,authorizationTimeoutMs:5000,now:()=>1000,authorize:async()=>true,authorizationAudit:audits.create({durable:true,append:async()=>true}),auditReadiness:{version:authorization.EXPECTED_READINESS_VERSION,check},activationJournal:journal(),resolve:async()=>'PENDING',recoveryTimeoutMs:5000};}
function runtimeOptions(){return {serviceRole:true,client:{rpc:async()=>({data:runtime.DATABASE_FINGERPRINT,error:null})},actorHash:actor,recoveryPurpose:'operator-rollout-recovery',authorizationTtlMs:5000,authorizationTimeoutMs:5000,now:()=>1000,authorize:async()=>true,resolve:async()=>'PENDING',recoveryTimeoutMs:5000,auditPageSize:10,auditMaxEvents:100};}
test('authorization readiness decisions reject accessors traps inherited fields and malformed counters before operator hook',async()=>{let calls=0;for(const response of [Object.create(ready()),new Proxy(ready(),{getOwnPropertyDescriptor(){throw new Error('host failure');}}),{...ready(),pageCount:0},{...ready(),eventCount:1,watermarkId:null}]){const value=authorization.create({...authorizationOptions(async()=>response),authorize:async()=>{calls++;return true;}});assert.equal((await value.issue(attestation)).reasonCode,'AUDIT_READINESS_REQUIRED');}for(const field of authorization.READINESS_FIELDS){const response=ready();Object.defineProperty(response,field,{get(){calls++;throw new Error('must not run');}});const value=authorization.create(authorizationOptions(async()=>response));assert.equal((await value.issue(attestation)).reasonCode,'AUDIT_READINESS_REQUIRED');}assert.equal(calls,0);});
test('runtime rejects coercive identity timing and recovery fields without invoking conversion hooks',()=>{let calls=0;const malicious={toString(){calls++;throw new Error('must not run');},valueOf(){calls++;throw new Error('must not run');}};for(const changed of [{actorHash:malicious},{recoveryPurpose:malicious},{authorizationTtlMs:malicious},{authorizationTimeoutMs:'5000'},{recoveryTimeoutMs:5000n}])assert.throws(()=>runtime.create({...runtimeOptions(),...changed}),/functions|bounded/u);for(const field of ['actorHash','recoveryPurpose','authorizationTtlMs','authorizationTimeoutMs','recoveryTimeoutMs']){const options=runtimeOptions();Object.defineProperty(options,field,{get(){calls++;throw new Error('must not run');}});assert.throws(()=>runtime.create(options),/functions|bounded/u);}assert.equal(calls,0);});
test('readiness producers map unknown reason strings to a closed generic code',async()=>{const readiness=require('../adapters/rollout-recovery-authorization-audit-readiness.js');const gate=readiness.create({auditVerifier:{version:readiness.EXPECTED_VERIFIER_VERSION,scan:async()=>({version:readiness.EXPECTED_VERIFIER_VERSION,status:'AUDIT_SCAN_INCOMPLETE',reasonCode:'ATTACKER_CONTROLLED',eventCount:1,pageCount:1,watermarkId:1})},pageSize:10,maxEvents:100});assert.equal((await gate.check()).reasonCode,'AUDIT_SCAN_NOT_COMPLETE');});
test('runtime health rejects unknown blocked readiness reason strings',()=>{assert.equal(runtime.HEALTH_REASONS.has('ATTACKER_CONTROLLED'),false);});
