'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const publicAdapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const trusted=require('../adapters/trusted-terminal-delivery-adapter.js');const stores=require('../adapters/durable-idempotency-store.js');
let sequence=0;function authorization(){const n=++sequence,answer=`Dayanıklı sunum ${n}`,transactionId=`tx-2y-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerReleaseGate:releaseGate,answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=publicAdapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse}));return authorizer.authorize(delivery,{sessionId:'session-a',channelId:'atlas-ui',deliveryNonce:`nonce-${n}`,now:()=>1000});}
const baseStore=overrides=>({version:stores.STORE_VERSION,durable:true,claimLeaseMs:30000,async claim(){return true;},async settle(){return true;},...overrides});
test('requires an atomic durable store contract',()=>{assert.equal(stores.STORE_VERSION,'sinbad-durable-idempotency-store/2Y-v1');for(const value of [{},{claim(){}},{settle(){}},baseStore({durable:false}),baseStore({claimLeaseMs:0}),baseStore({version:'other'})])assert.throws(()=>stores.validate(value),/versioned durable idempotency store/u);const validated=stores.validate(baseStore());assert.ok(Object.isFrozen(validated));assert.equal(validated.durable,true);});
test('claims a content-free deterministic key before presentation and settles minimal state',async()=>{const auth=authorization(),events=[],store=baseStore({async claim(key){events.push(['claim',key]);return true;},async settle(key,value){events.push(['settle',key,value]);return true;}}),result=await trusted.create({idempotencyStore:store,present:async()=>{events.push(['present']);return true;}}).deliver(auth);assert.equal(result.status,'TRUSTED_TERMINAL_DELIVERY_APPLIED');assert.equal(events[0][0],'claim');assert.equal(events[1][0],'present');assert.equal(events[2][0],'settle');assert.match(events[0][1],/^[a-f0-9]{64}$/u);assert.equal(events[2][1],events[0][1]);assert.deepEqual(Object.keys(events[2][2]).sort(),['outcome','status','terminalState','transitionHash']);assert.equal(JSON.stringify(events).includes(auth.answer),false);});
test('denied or failing claims block before presentation',async()=>{for(const claim of [async()=>false,async()=>{throw new Error('offline');}]){let calls=0;const result=await trusted.create({idempotencyStore:baseStore({claim}),present:async()=>{calls++;return true;}}).deliver(authorization());assert.equal(result.status,'TRUSTED_TERMINAL_DELIVERY_BLOCKED');assert.equal(calls,0);}});
test('a shared atomic store blocks a second adapter instance before presentation',async()=>{const claimed=new Set(),store=baseStore({async claim(key){if(claimed.has(key))return false;claimed.add(key);return true;}}),auth=authorization();let calls=0;const first=trusted.create({idempotencyStore:store,present:async()=>{calls++;return true;}}),second=trusted.create({idempotencyStore:store,present:async()=>{calls++;return true;}});assert.equal((await first.deliver(auth)).status,'TRUSTED_TERMINAL_DELIVERY_APPLIED');assert.equal((await second.deliver(auth)).status,'TRUSTED_TERMINAL_DELIVERY_BLOCKED');assert.equal(calls,1);});
test('settlement denial reports non-retriable UNSETTLED after applied side effects',async()=>{let claims=0,calls=0;const store=baseStore({async claim(){claims++;return claims===1;},async settle(){return false;}}),adapter=trusted.create({idempotencyStore:store,present:async()=>{calls++;return true;}}),auth=authorization(),first=await adapter.deliver(auth);assert.equal(first.status,'TRUSTED_TERMINAL_DELIVERY_UNSETTLED');assert.equal(first.reasonCode,'DURABLE_SETTLEMENT_REQUIRED');assert.equal(first.terminalState,'DELIVERY_SUCCEEDED');assert.equal(first.outcome,'DELIVERED');assert.match(first.transitionHash,/^[a-f0-9]{64}$/u);assert.equal((await adapter.deliver(auth)).status,'TRUSTED_TERMINAL_DELIVERY_BLOCKED');assert.equal(calls,1);});
test('claim and settlement require exact boolean true and diagnose settlement failures',async()=>{for(const value of [1,'true',{},undefined]){let calls=0;const claimResult=await trusted.create({idempotencyStore:baseStore({async claim(){return value;}}),present:async()=>{calls++;return true;}}).deliver(authorization());assert.equal(claimResult.status,'TRUSTED_TERMINAL_DELIVERY_BLOCKED');assert.equal(calls,0);const events=[],settleResult=await trusted.create({idempotencyStore:baseStore({async settle(){return value;}}),present:async()=>true,diagnose:event=>events.push(event)}).deliver(authorization());assert.equal(settleResult.status,'TRUSTED_TERMINAL_DELIVERY_UNSETTLED');assert.deepEqual(events,[{version:trusted.ADAPTER_VERSION,code:'IDEMPOTENCY_SETTLEMENT_DENIED'}]);}});
