'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const runtime=require('../adapters/trusted-rollout-recovery-runtime.js');
const actor='d'.repeat(64),hash='e'.repeat(64);let time=1000;
function options(rpc,overrides={}){return {serviceRole:true,client:{rpc},actorHash:actor,recoveryPurpose:'operator-rollout-recovery',authorizationTtlMs:5000,authorizationTimeoutMs:5000,now:()=>time,authorize:async()=>true,resolve:async()=>'PENDING',recoveryTimeoutMs:5000,auditPageSize:10,auditMaxEvents:100,...overrides};}
function healthy(){return async(name,args)=>{if(name==='verify_rollout_recovery_runtime_access'||name==='verify_rollout_recovery_authorization_audit_access')return {data:true,error:null};if(name==='list_rollout_recovery_authorization_audit')return {data:[],error:null};if(name==='append_rollout_recovery_authorization_audit')return {data:'RECORDED',error:null};if(name==='inspect_terminal_rollout_activation')return {data:[{status:'APPLIED',started_at:'2026-08-13T00:00:00Z',updated_at:'2026-08-13T00:01:00Z'}],error:null};throw new Error(`unexpected ${name} ${JSON.stringify(args)}`);};}
test('constructs only the exact bounded service-role runtime',()=>{assert.throws(()=>runtime.create(),/service-role/u);assert.throws(()=>runtime.create(options(healthy(),{auditPageSize:0})),/policy/u);const value=runtime.create(options(healthy()));assert.deepEqual(Object.keys(value),['version','healthCheck','issue','recover']);assert.ok(Object.isFrozen(value));});
test('preflights once then wires authorization audit and recovery',async()=>{time=1000;const calls=[],rpc=async(name,args)=>{calls.push(name);return healthy()(name,args);},value=runtime.create(options(rpc));assert.equal((await value.healthCheck()).status,'ROLLOUT_RECOVERY_RUNTIME_READY');const authorization=await value.issue(hash);assert.equal(authorization.status,'ROLLOUT_RECOVERY_AUTHORIZED');assert.equal(calls.filter(x=>x==='verify_rollout_recovery_runtime_access').length,1);assert.equal((await value.recover(authorization)).status,'ROLLOUT_RECOVERY_APPLIED');});
test('failed preflight blocks issue and recovery before trusted hooks',async()=>{time=1000;let authorizations=0,resolutions=0;const value=runtime.create(options(async name=>name==='verify_rollout_recovery_runtime_access'?{data:false,error:null}:{data:[],error:null},{authorize:async()=>{authorizations++;return true;},resolve:async()=>{resolutions++;return 'APPLIED';}}));assert.equal((await value.healthCheck()).status,'ROLLOUT_RECOVERY_RUNTIME_BLOCKED');assert.equal((await value.issue(hash)).reasonCode,'RUNTIME_PREFLIGHT_REQUIRED');assert.equal((await value.recover({})).reasonCode,'RUNTIME_PREFLIGHT_REQUIRED');assert.deepEqual({authorizations,resolutions},{authorizations:0,resolutions:0});});
test('RPC errors and partial policies fail closed',async()=>{for(const rpc of [async()=>{throw new Error('offline');},async()=>({data:null,error:{message:'offline'}})])assert.equal((await runtime.create(options(rpc)).healthCheck()).status,'ROLLOUT_RECOVERY_RUNTIME_BLOCKED');for(const changed of [{authorize:null},{resolve:null},{now:null},{auditMaxEvents:9}])assert.throws(()=>runtime.create(options(healthy(),changed)),/required|policy/u);});
test('runtime remains internal to the package export map',()=>{assert.equal(require('../package.json').exports['./trusted-rollout-recovery-runtime'],undefined);});
