'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const verifier=require('../adapters/supabase-rollout-recovery-deployment-reconciliation-audit-verifier.js');
function row(){const value={id:1,actor_hash:'a'.repeat(64),authorization_hash:'b'.repeat(64),purpose_hash:'c'.repeat(64),decision:'AUTHORIZED',decided_at_ms:1001};value.event_hash=createHash('sha256').update([verifier.EVENT_VERSION,value.actor_hash,value.authorization_hash,value.purpose_hash,value.decision,value.decided_at_ms].join('\n')).digest('hex');return value;}
test('verifier rejects accessor inherited and replaced rpc configuration',async()=>{let reads=0,original=0,replacement=0;for(const field of ['client','serviceRole']){const options={serviceRole:true,client:{rpc:async()=>({data:true,error:null})}};Object.defineProperty(options,field,{get(){reads++;throw new Error('must not run');}});assert.throws(()=>verifier.create(options),/service-role/u);}const client={rpc:async name=>{original++;return name.startsWith('verify_')?{data:true,error:null}:{data:[],error:null};}},value=verifier.create({serviceRole:true,client});client.rpc=async()=>{replacement++;throw new Error('must not run');};assert.equal((await value.scan()).status,'AUDIT_SCAN_COMPLETE');assert.deepEqual([reads,replacement],[0,0]);assert.ok(original>0);});
test('verifier rejects inherited rpc configuration',()=>{assert.throws(()=>verifier.create({serviceRole:true,client:Object.create({rpc:async()=>({data:true,error:null})})}),/service-role/u);});
test('verifier rejects accessor and inherited response envelopes without invoking getters',async()=>{let reads=0;for(const name of ['data','error']){const response={data:true,error:null};Object.defineProperty(response,name,{get(){reads++;throw new Error('must not run');}});const value=verifier.create({serviceRole:true,client:{rpc:async()=>response}});assert.equal((await value.scan()).reasonCode,'AUDIT_CAPABILITY_DENIED');}const value=verifier.create({serviceRole:true,client:{rpc:async()=>Object.create({data:true,error:null})}});assert.equal((await value.scan()).reasonCode,'AUDIT_CAPABILITY_DENIED');assert.equal(reads,0);});
test('verifier rejects accessor sparse and trapped page indices',()=>{let reads=0;const accessor=[row()];Object.defineProperty(accessor,'0',{get(){reads++;throw new Error('must not run');}});const sparse=new Array(1);const trapped=new Proxy([row()],{getOwnPropertyDescriptor(){throw new Error('must not run');}});for(const data of [accessor,sparse,trapped])assert.equal(verifier.parse(data),null);assert.equal(reads,0);});
test('verifier sends frozen capability and list arguments',async()=>{const seen=[];const value=verifier.create({serviceRole:true,client:{rpc:async(name,args)=>{seen.push([name,args]);return name.startsWith('verify_')?{data:true,error:null}:{data:[],error:null};}}});assert.equal((await value.scan({pageSize:2,maxEvents:4})).status,'AUDIT_SCAN_COMPLETE');assert.equal(seen.length,2);for(const [,args] of seen)assert.ok(Object.isFrozen(args));});
test('verifier rejects malformed list envelopes and page arrays end to end',async()=>{for(const response of [{data:[],error:undefined},{data:[]},Object.create({data:[],error:null}),{data:new Array(1),error:null}]){const value=verifier.create({serviceRole:true,client:{rpc:async name=>name.startsWith('verify_')?{data:true,error:null}:response}}),result=await value.scan();assert.ok(['AUDIT_STORE_UNAVAILABLE','AUDIT_EVENT_HASH_MISMATCH'].includes(result.reasonCode));}});
