'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const runtime=require('../../tools/trusted-rollout-recovery-deployment-reconciliation-runtime.js');
const actorHash='b'.repeat(64),authorizationHash='a'.repeat(64);
const fields=['client','serviceRole','resolve','diagnose','reconciliationTimeoutMs','authorize','now','actorHash','reconciliationPurpose','authorizationTtlMs','authorizationTimeoutMs','auditPageSize','auditMaxEvents'];
function options(){const calls=[];const client={async rpc(name){calls.push(name);if(name==='verify_rollout_recovery_deployment_reconciliation_audit_access')return {data:true,error:null};if(name==='list_rollout_recovery_deployment_reconciliation_audit')return {data:[],error:null};if(name==='append_rollout_recovery_deployment_reconciliation_audit')return {data:'RECORDED',error:null};if(name==='inspect_rollout_recovery_deployment')return {data:[{status:'APPLIED',started_at:'2026-08-13T00:00:00Z',updated_at:'2026-08-13T00:00:01Z'}],error:null};throw new Error(`Unexpected RPC: ${name}`);}};return {value:{client,serviceRole:true,resolve:async()=>'APPLIED',diagnose:undefined,reconciliationTimeoutMs:1000,authorize:async()=>true,now:()=>1000,actorHash,reconciliationPurpose:'deployment.reconciliation',authorizationTtlMs:1000,authorizationTimeoutMs:1000,auditPageSize:100,auditMaxEvents:10000},calls};}
test('runtime rejects accessor inherited and coercive dependencies without invoking hooks',()=>{let reads=0;for(const field of fields){const {value}=options();Object.defineProperty(value,field,{get(){reads++;throw new Error('must not run');}});assert.throws(()=>runtime.create(value),/dependency|client/u);}const inherited=Object.create(options().value);assert.throws(()=>runtime.create(inherited),/own data|client/u);for(const changed of [{serviceRole:'true'},{reconciliationTimeoutMs:'1000'},{auditPageSize:100n},{auditMaxEvents:'10000'},{auditPageSize:101,auditMaxEvents:100},{actorHash:{toString(){reads++;return 'b'.repeat(64);}}},{reconciliationPurpose:1},{authorizationTtlMs:'1000'},{authorizationTimeoutMs:1000n}])assert.throws(()=>runtime.create({...options().value,...changed}),/client|timeout|scan policy|identity|timing/u);const prototypeDiagnose=Object.create({diagnose(){reads++;}});Object.assign(prototypeDiagnose,options().value);delete prototypeDiagnose.diagnose;assert.doesNotThrow(()=>runtime.create(prototypeDiagnose));assert.equal(reads,0);});
test('runtime rejects accessor rpc without invoking it',()=>{let reads=0;const {value}=options();Object.defineProperty(value.client,'rpc',{get(){reads++;throw new Error('must not run');}});assert.throws(()=>runtime.create(value),/client/u);assert.equal(reads,0);});
test('runtime rejects inherited rpc',()=>{const {value}=options();value.client=Object.create(value.client);assert.throws(()=>runtime.create(value),/client/u);});
test('runtime snapshots outer hooks policy and rpc before later mutation',async()=>{let replacements=0;const {value,calls}=options(),originalClient=value.client;const created=runtime.create(value),replacement=async()=>{replacements++;throw new Error('must not run');};value.client={rpc:replacement};originalClient.rpc=replacement;value.resolve=replacement;value.authorize=replacement;value.now=replacement;value.auditPageSize=0;assert.equal((await created.preflight()).status,'ROLLOUT_RECOVERY_DEPLOYMENT_RECONCILIATION_RUNTIME_READY');const capability=await created.issue(authorizationHash);assert.equal(capability.status,'ROLLOUT_RECOVERY_DEPLOYMENT_RECONCILIATION_AUTHORIZED');assert.equal((await created.reconcile(capability)).status,'ROLLOUT_RECOVERY_DEPLOYMENT_RECONCILED_APPLIED');assert.ok(calls.length>0);assert.equal(replacements,0);});
