'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const contracts=require('../verification/claim-contracts.js');const retrieval=require('../retrieval/contracts.js');
const verifier=require('../verification/claim-support-verifier.js');const auditModule=require('../orchestrator/audit-log.js');const orchestrationContract=require('../orchestrator/grounded-orchestration-contract.js');
const citationBuilder=require('../grounding/citation-builder.js');const grounding=require('../grounding/grounded-answer-pipeline.js');
function spanSupport(overrides={}){return {mode:'EXACT_SPAN',evidenceId:'e1',startOffset:0,endOffset:4,spanHash:contracts.sha256(Buffer.from('Safe')),offsetEncoding:'UTF16_CODE_UNIT',...overrides};}
function claimPayload(overrides={}){const base={schemaVersion:contracts.CLAIM_SCHEMA,claimType:'FACT',statement:'Safe',support:spanSupport(),requiresAuthoritative:true,...overrides};return {...base,claimId:contracts.deriveClaimId(base)};}
function factPayload(overrides={}){return {schemaVersion:contracts.FACT_SCHEMA,subject:'harbor-a',predicate:'SPEED_LIMIT',value:'10',valueType:'INTEGER',unit:'KNOT',polarity:'POSITIVE',modality:'ASSERTED',effectiveAt:'2026-01-01',jurisdiction:'TR',qualifiers:[],...overrides};}
function evidenceFact(evidenceId='e1',overrides={}){const payload=factPayload(overrides);const factHash=contracts.factHash(payload);return {...payload,factHash,factId:contracts.factId({evidenceId,factOrdinal:0,factHash})};}
function lineage(content='Safe harbor rule.',overrides={}){return {indexId:'idx:'+('1'.repeat(64)),indexHash:'2'.repeat(64),policyId:'policy-1',policyHash:'3'.repeat(64),issuerId:'issuer-1',sourceId:'source-1',documentId:'doc-1',editionId:'ed-1',canonicalHash:'4'.repeat(64),chunkId:'chunk-1',chunkContentHash:contracts.sha256(Buffer.from(content)),chunkerVersion:'sinbad-chunker/1',license:'public-domain',authorityDecision:'TRUST_POLICY_GRANTED',editionStatus:'current',...overrides};}
function selected(overrides={}){const content=overrides.content||'Safe harbor rule.';return retrieval.evidence({id:'e1',sourceId:'source-1',sourceType:'offline-publication',evidenceClass:'verified-authoritative',authority:'authoritative',verified:true,title:'Pilot',content,relevance:1,location:{chunk:0},publishedAt:'2026-01-01',version:'2026',provenance:lineage(content),...overrides});}
function verifiedClaim(overrides={}){const base={schemaVersion:contracts.CLAIM_SCHEMA,claimType:'FACT',statement:'Safe',support:spanSupport(),requiresAuthoritative:true,...overrides};return {...base,claimId:contracts.deriveClaimId(base)};}
function factClaim(fact=factPayload(),overrides={}){const support={mode:'STRUCTURED_FACT',evidenceId:'e1',factOrdinal:0,factHash:contracts.factHash(fact),fact};const base={schemaVersion:contracts.CLAIM_SCHEMA,claimType:'FACT',statement:contracts.structuredStatement(fact),support,requiresAuthoritative:true,...overrides};return {...base,claimId:contracts.deriveClaimId(base)};}
test('claim identity is deterministic, canonical, and changes with every identity field',()=>{const a=claimPayload();const reordered={requiresAuthoritative:a.requiresAuthoritative,support:{...a.support},statement:a.statement,claimType:a.claimType,schemaVersion:a.schemaVersion};assert.equal(contracts.deriveClaimId(a),contracts.deriveClaimId(reordered));for(const changed of [{claimType:'INFERENCE'},{statement:'Safe!'},{support:spanSupport({endOffset:3})},{requiresAuthoritative:false}])assert.notEqual(contracts.deriveClaimId({...a,...changed}),a.claimId);assert.deepEqual(contracts.claim(a),contracts.claim({...a}));});
test('caller claim ID mismatch and self-approval fields fail closed',()=>{assert.throws(()=>contracts.claim({...claimPayload(),claimId:'clm:'+('0'.repeat(64))}),e=>e.code==='CLAIM_INVALID');for(const key of ['supported','verified','authoritative','trusted','citationEligible','verificationStatus','verifierResult'])assert.throws(()=>contracts.claim({...claimPayload(),[key]:true}),e=>e.code==='CLAIM_INVALID');});
test('claim schema enforces type, NFC, controls, CR, and UTF-16 length',()=>{assert.equal(contracts.claim(claimPayload()).claimType,'FACT');assert.throws(()=>contracts.claim(claimPayload({claimType:'UNKNOWN'})),e=>e.code==='CLAIM_INVALID');for(const statement of ['',`A\rB`,'e\u0301','A\u0000B','x'.repeat(1025)])assert.throws(()=>contracts.claim(claimPayload({statement})),e=>e.code==='CLAIM_INVALID');assert.equal('😀'.length,2);assert.doesNotThrow(()=>contracts.claim(claimPayload({statement:'😀'.repeat(512)})));});
test('structuredFacts is additive, strict, immutable, and leaves legacy claims unchanged',()=>{const fact=evidenceFact();const item=retrieval.evidence({id:'e1',claims:[{key:'legacy',value:'unchanged',scope:'old'}],structuredFacts:[fact]});assert.deepEqual(item.claims,[{key:'legacy',value:'unchanged',scope:'old'}]);assert.equal(item.structuredFacts[0].factId,fact.factId);assert.equal(Object.isFrozen(item.structuredFacts),true);assert.deepEqual(retrieval.evidence({id:'e2'}).structuredFacts,[]);assert.throws(()=>retrieval.evidence({id:'e1',structuredFacts:[{...fact,authority:'authoritative'}]}),e=>e.code==='CLAIM_INVALID');});
test('exact-span support is exact, hash-bound, authentic, and deterministic',()=>{const evidence=selected();const claim=verifiedClaim();const first=verifier.verify(claim,{selected:[evidence]});const second=verifier.verify(claim,{selected:[evidence]});assert.equal(first.status,'CLAIM_SUPPORTED');assert.equal(first.citationEligible,true);assert.equal(verifier.isAuthenticResult(first),true);assert.deepEqual(first,second);assert.equal(JSON.stringify(first),JSON.stringify(second));assert.equal(verifier.isAuthenticResult({...first}),false);});
test('exact-span mutations fail at their single intended condition',()=>{const evidence=selected();const rows=[
  [verifiedClaim({statement:'Port',support:spanSupport()}),'CLAIM_UNSUPPORTED'],
  [verifiedClaim({support:spanSupport({evidenceId:'missing'})}),'CLAIM_UNSUPPORTED'],
  [verifiedClaim({support:spanSupport({startOffset:1,endOffset:5,spanHash:contracts.sha256(Buffer.from('afe '))})}),'CLAIM_UNSUPPORTED'],
  [verifiedClaim({support:spanSupport({spanHash:'0'.repeat(64)})}),'CLAIM_UNSUPPORTED'],
  [verifiedClaim({support:spanSupport({startOffset:-1})}),'CLAIM_INVALID'],
  [verifiedClaim({support:spanSupport({startOffset:.5})}),'CLAIM_INVALID'],
  [verifiedClaim({support:spanSupport({endOffset:0})}),'CLAIM_INVALID'],
  [verifiedClaim({support:spanSupport({startOffset:5,endOffset:4})}),'CLAIM_INVALID'],
  [verifiedClaim({support:spanSupport({endOffset:99})}),'CLAIM_INVALID'],
  [verifiedClaim({support:{mode:'CROSS_CHUNK',evidenceId:'e1'}}),'CLAIM_UNVERIFIABLE']
];for(const [claim,status] of rows){const out=verifier.verify(claim,{selected:[evidence]});assert.equal(out.status,status);assert.equal(out.citationEligible,false);assert.equal(evidence.provenance.authorityDecision,'TRUST_POLICY_GRANTED');}});
test('UTF-16 surrogate boundaries are strict while complete pairs verify',()=>{const content='A😀B';const evidence=selected({content,provenance:lineage(content)});const good=verifiedClaim({statement:'😀',support:spanSupport({startOffset:1,endOffset:3,spanHash:contracts.sha256(Buffer.from('😀'))})});assert.equal(verifier.verify(good,{selected:[evidence]}).status,'CLAIM_SUPPORTED');for(const support of [spanSupport({startOffset:2,endOffset:3}),spanSupport({startOffset:1,endOffset:2})])assert.equal(verifier.verify(verifiedClaim({statement:'x',support}),{selected:[evidence]}).status,'CLAIM_INVALID');});
test('changed evidence hash propagates HASH_MISMATCH and missing provenance propagates PROVENANCE_INCOMPLETE',()=>{const good=selected();assert.throws(()=>verifier.verify(verifiedClaim(),{selected:[selected({provenance:lineage('different')})]}),e=>e.code==='HASH_MISMATCH');assert.throws(()=>verifier.verify(verifiedClaim(),{selected:[selected({provenance:{}})]}),e=>e.code==='PROVENANCE_INCOMPLETE');assert.equal(good.content,'Safe harbor rule.');});
test('structured facts support exact typed facts and classify contradiction before scope mismatch',()=>{const fact=evidenceFact();const evidence=selected({structuredFacts:[fact]});assert.equal(verifier.verify(factClaim(),{selected:[evidence]}).status,'CLAIM_SUPPORTED');const contradictionCases=[factPayload({value:'11'}),factPayload({polarity:'NEGATIVE'})];for(const changed of contradictionCases)assert.equal(verifier.verify(factClaim(changed),{selected:[evidence]}).status,'CLAIM_CONTRADICTED');const mustFact=evidenceFact('e1',{predicate:'OBLIGATION_STATE',value:'required',valueType:'ENUM',unit:'NONE',modality:'MUST'});const mustEvidence=selected({structuredFacts:[mustFact]});assert.equal(verifier.verify(factClaim(factPayload({predicate:'OBLIGATION_STATE',value:'required',valueType:'ENUM',unit:'NONE',modality:'MAY'})),{selected:[mustEvidence]}).status,'CLAIM_CONTRADICTED');const scopeCases=[factPayload({unit:'KILOMETRE_PER_HOUR'}),factPayload({effectiveAt:'2025-01-01'}),factPayload({jurisdiction:'GR'}),factPayload({qualifiers:[{key:'gt',operator:'GTE',value:'500',valueType:'INTEGER',unit:'GROSS_TONNAGE'}]})];for(const changed of scopeCases)assert.equal(verifier.verify(factClaim(changed),{selected:[evidence]}).status,'CLAIM_SCOPE_MISMATCH');});
test('fact identity, ordinal, registries, and ambiguous encodings fail closed',()=>{const fact=evidenceFact();const evidence=selected({structuredFacts:[fact]});assert.equal(verifier.verify(factClaim(factPayload(),{support:{mode:'STRUCTURED_FACT',evidenceId:'e1',factOrdinal:1,factHash:contracts.factHash(factPayload()),fact:factPayload()}}),{selected:[evidence]}).status,'CLAIM_UNSUPPORTED');for(const mutation of [{predicate:'UNKNOWN'},{unit:'FURLONG'},{valueType:'FLOAT'},{modality:'PERMITTED',polarity:'NEGATIVE'}])assert.throws(()=>contracts.factPayload(factPayload(mutation)),e=>e.code==='CLAIM_INVALID');assert.throws(()=>retrieval.evidence({id:'e1',structuredFacts:[{...fact,factHash:'0'.repeat(64)}]}),e=>e.code==='CLAIM_INVALID');assert.throws(()=>retrieval.evidence({id:'e1',structuredFacts:[{...fact,factId:'fact:bad'}]}),e=>e.code==='CLAIM_INVALID');});
test('authority and evidence classes fail closed without caller elevation',()=>{const claim=verifiedClaim();assert.equal(verifier.verify(claim,{selected:[selected({evidenceClass:'secondary',authority:'secondary',verified:false})]}).status,'CLAIM_AUTHORITY_INSUFFICIENT');for(const evidenceClass of ['memory-context','user-provided'])assert.equal(verifier.verify(verifiedClaim({requiresAuthoritative:false}),{selected:[selected({evidenceClass})]}).status,'CLAIM_UNSUPPORTED');assert.equal(verifier.verify(claim,{selected:[selected()],rejected:[{id:'e1',reason:'LOW_RELEVANCE'}]}).status,'CLAIM_UNSUPPORTED');});
test('historical facts require explicit matching historical scope and never satisfy authority',()=>{const fact=evidenceFact();const evidence=selected({structuredFacts:[fact],authority:'secondary',verified:false,evidenceClass:'secondary',provenance:lineage('Safe harbor rule.',{editionStatus:'historical',authorityDecision:'EDITION_STALE'})});assert.equal(verifier.verify(factClaim(factPayload(),{requiresAuthoritative:false}),{selected:[evidence],historical:true}).status,'CLAIM_SUPPORTED');assert.equal(verifier.verify(factClaim(),{selected:[evidence],historical:true}).status,'CLAIM_AUTHORITY_INSUFFICIENT');assert.equal(verifier.verify(factClaim(factPayload(),{requiresAuthoritative:false}),{selected:[evidence]}).status,'CLAIM_SCOPE_MISMATCH');});
test('audit order and payload are content-minimized',()=>{const log=auditModule.create({now:()=> '2026-08-11T00:00:00.000Z'});const out=verifier.verify(verifiedClaim(),{selected:[selected()],audit:log});assert.equal(out.status,'CLAIM_SUPPORTED');assert.deepEqual(log.snapshot().map(x=>x.reason),['CLAIM_RECEIVED','CLAIM_VERIFICATION_STARTED','EVIDENCE_CANDIDATE_EVALUATED','CLAIM_SUPPORT_ACCEPTED','CITATION_ELIGIBILITY_GRANTED']);const serialized=JSON.stringify(log.snapshot());assert.equal(serialized.includes('Safe harbor rule.'),false);assert.equal(serialized.includes('"statement"'),false);});
test('verifyAll deduplicates identical claims and stabilizes result ordering',()=>{const a=verifiedClaim();const b=verifiedClaim({statement:'harbor',support:spanSupport({startOffset:5,endOffset:11,spanHash:contracts.sha256(Buffer.from('harbor'))})});const first=verifier.verifyAll([b,a,a],{selected:[selected()]});const second=verifier.verifyAll([a,b],{selected:[selected()]});assert.deepEqual(first,second);assert.equal(first.length,2);});
test('evidence insertion order cannot alter a verification result',()=>{const primary=selected(),other=selected({id:'e2',sourceId:'other',provenance:lineage('Safe harbor rule.',{sourceId:'other',chunkId:'chunk-2'})}),claim=verifiedClaim();assert.deepEqual(verifier.verify(claim,{selected:[primary,other]}),verifier.verify(claim,{selected:[other,primary]}));});
test('citation builder requires authentic verifier approval and preserves lineage',()=>{const evidence=selected();const claim=verifiedClaim();const forged={claimId:claim.claimId,status:'CLAIM_SUPPORTED',citationEligible:true};const denied=citationBuilder.build({selected:[evidence],claims:[claim],verifications:[forged]});assert.equal(denied.citations.length,0);assert.equal(denied.errors[0].reason,'VERIFICATION_REQUIRED');const approved=verifier.verify(claim,{selected:[evidence]});const accepted=citationBuilder.build({selected:[evidence],claims:[claim],verifications:[approved]});assert.equal(accepted.citations.length,1);assert.equal(accepted.claims[0].verificationStatus,'CLAIM_SUPPORTED');assert.equal(accepted.citations[0].provenance.chunkId,'chunk-1');});
test('authentic approval is claim-bound and duplicate claims cannot amplify citations',()=>{const evidence=selected(),claim=verifiedClaim(),approval=verifier.verify(claim,{selected:[evidence]});const mutated={...claim,statement:'Port'};const rebound=citationBuilder.build({selected:[evidence],claims:[mutated],verifications:[approval]});assert.equal(rebound.citations.length,0);assert.equal(rebound.errors[0].reason,'CLAIM_INVALID');const duplicate=citationBuilder.build({selected:[evidence],claims:[claim,{...claim}],verifications:[approval]});assert.equal(duplicate.claims.length,1);assert.equal(duplicate.citations.length,1);});
function retrievalResult(items,status='EVIDENCE_SUFFICIENT'){return {version:'sinbad-retrieval-engine/2A',status,evaluation:{selected:items,rejected:[],status},rejected:[]};}
test('grounding maps detailed claim statuses without losing claim-level reason',()=>{const evidence=selected();const cases=[
  [verifiedClaim({statement:'Port'}),'SOURCE_INSUFFICIENT','CLAIM_UNSUPPORTED'],
  [verifiedClaim({claimType:'INFERENCE'}),'INVALID_CLAIMS','CLAIM_UNVERIFIABLE'],
  [verifiedClaim({requiresAuthoritative:true}),'SOURCE_INSUFFICIENT','CLAIM_AUTHORITY_INSUFFICIENT',selected({evidenceClass:'secondary',authority:'secondary',verified:false})]
];for(const [claim,top,detail,item=evidence] of cases){const out=grounding.create().run({retrievalResult:retrievalResult([item]),claims:[claim]});assert.equal(out.status,top);assert.equal(out.claims[0].verificationStatus,detail);assert.equal(out.answer,null);assert.equal(out.citations.length,0);}});
test('grounding preserves contradicted and scope-mismatch top-level statuses',()=>{const evidence=selected({structuredFacts:[evidenceFact()]});for(const [fact,top] of [[factPayload({value:'11'}),'CLAIM_CONTRADICTED'],[factPayload({unit:'KILOMETRE_PER_HOUR'}),'CLAIM_SCOPE_MISMATCH']]){const out=grounding.create().run({retrievalResult:retrievalResult([evidence]),claims:[factClaim(fact)]});assert.equal(out.status,top);assert.equal(out.claims[0].verificationStatus,top);assert.equal(out.citations.length,0);}});
test('upstream conflict is preserved and verifier does not override it',()=>{const out=grounding.create().run({retrievalResult:retrievalResult([selected()],'EVIDENCE_CONFLICT'),claims:[verifiedClaim({claimType:'INFERENCE'})]});assert.equal(out.status,'EVIDENCE_CONFLICT');assert.equal(out.claims.length,0);assert.equal(out.citations.length,0);});
test('invalid claim maps to INVALID_CLAIMS with no citation',()=>{const invalid={...verifiedClaim(),supported:true};const out=grounding.create().run({retrievalResult:retrievalResult([selected()]),claims:[invalid]});assert.equal(out.status,'INVALID_CLAIMS');assert.equal(out.claims[0].verificationStatus,'CLAIM_INVALID');assert.equal(out.citations.length,0);});
test('permission reversal and qualifier operators are deterministic',()=>{const permitted=evidenceFact('e1',{predicate:'PERMISSION_STATE',value:'entry',valueType:'ENUM',unit:'NONE',modality:'PERMITTED'}),evidence=selected({structuredFacts:[permitted]});const prohibited=factPayload({predicate:'PERMISSION_STATE',value:'entry',valueType:'ENUM',unit:'NONE',modality:'PROHIBITED'});assert.equal(verifier.verify(factClaim(prohibited),{selected:[evidence]}).status,'CLAIM_CONTRADICTED');const scoped=factPayload({qualifiers:[{key:'gt',operator:'LTE',value:'10',valueType:'INTEGER',unit:'GROSS_TONNAGE'}]}),scopedEvidence=selected({structuredFacts:[evidenceFact('e1',{qualifiers:scoped.qualifiers})]});for(const qualifiers of [[],[{key:'gt',operator:'LT',value:'10',valueType:'INTEGER',unit:'GROSS_TONNAGE'}],[{key:'gt',operator:'GTE',value:'500',valueType:'INTEGER',unit:'GROSS_TONNAGE'}]])assert.equal(verifier.verify(factClaim(factPayload({qualifiers})),{selected:[scopedEvidence]}).status,'CLAIM_SCOPE_MISMATCH');});
test('structured fact cannot carry an unrelated free-form statement',()=>{const claim=factClaim(),tampered={...claim,statement:'Unrelated maritime assertion'};tampered.claimId=contracts.deriveClaimId(tampered);assert.equal(verifier.verify(tampered,{selected:[selected({structuredFacts:[evidenceFact()]})]}).status,'CLAIM_INVALID');});
test('prose never synthesizes facts and revoked evidence is inaccessible',()=>{assert.equal(verifier.verify(factClaim(),{selected:[selected()]}).status,'CLAIM_UNSUPPORTED');assert.throws(()=>verifier.verify(verifiedClaim(),{selected:[selected({provenance:lineage('Safe harbor rule.',{editionStatus:'revoked'})})]}),e=>e.code==='EDITION_REVOKED');});
test('audit includes frozen common identities and exact transaction without content',()=>{const log=auditModule.create({now:()=> '2026-08-11T00:00:00.000Z'});verifier.verify(verifiedClaim(),{selected:[selected()],audit:log,transactionId:'tx-2e'});for(const entry of log.snapshot()){assert.equal(entry.details.transactionId,'tx-2e');assert.equal(entry.details.verifierVersion,contracts.VERIFIER_VERSION);assert.equal(entry.details.claimSchemaVersion,contracts.CLAIM_SCHEMA);assert.equal(typeof entry.reason,'string');}const raw=JSON.stringify(log.snapshot());assert.equal(raw.includes('Safe harbor rule.'),false);});
test('unexpected verifier failure cannot fabricate support or citation',()=>{const evidence=new Proxy(selected(),{get(target,key,receiver){if(key==='content')throw new Error('INJECTED_VERIFIER_FAILURE');return Reflect.get(target,key,receiver);}}),claim=verifiedClaim();assert.throws(()=>verifier.verify(claim,{selected:[evidence]}),/INJECTED_VERIFIER_FAILURE/);const result=citationBuilder.build({selected:[selected()],claims:[claim],verifications:[]});assert.equal(result.citations.length,0);assert.equal(result.errors[0].reason,'VERIFICATION_REQUIRED');});
test('claim identity public boundary has no bypass and binds every frozen identity field',()=>{const golden=verifiedClaim(),same=verifiedClaim();assert.equal(golden.claimId,same.claimId);for(const mutation of [{schemaVersion:'sinbad-claim/2E-v2'},{claimType:'INFERENCE'},{statement:'Safe!'},{support:spanSupport({endOffset:3})},{requiresAuthoritative:false}])assert.notEqual(contracts.deriveClaimId({...golden,...mutation}),golden.claimId);assert.throws(()=>contracts.claim({...golden,claimId:'clm:'+('f'.repeat(64)),skipIdentityValidation:true}),e=>e.code==='CLAIM_INVALID');assert.equal(Object.keys(contracts).some(key=>/bypass|skip|inject/i.test(key)),false);const approval=verifier.verify(golden,{selected:[selected()]});assert.equal(citationBuilder.build({selected:[selected()],claims:[{...golden,claimId:'clm:'+('e'.repeat(64))}],verifications:[approval]}).citations.length,0);});
test('SPECULATION is unverifiable and cannot produce answer or citation',()=>{const claim=verifiedClaim({claimType:'SPECULATION'}),out=grounding.create().run({retrievalResult:retrievalResult([selected()]),claims:[claim]});assert.equal(out.status,'INVALID_CLAIMS');assert.equal(out.claims[0].verificationStatus,'CLAIM_UNVERIFIABLE');assert.equal(out.citations.length,0);assert.equal(out.answer,null);});
test('generic unknown claim field is invalid and cannot cite',()=>{const claim={...verifiedClaim(),unrecognizedChannel:'UNTRUSTED'},out=grounding.create().run({retrievalResult:retrievalResult([selected()]),claims:[claim]});assert.equal(out.status,'INVALID_CLAIMS');assert.equal(out.claims[0].verificationStatus,'CLAIM_INVALID');assert.equal(out.citations.length,0);});
test('one-character statement mutation alone is unsupported',()=>{const evidence=selected(),golden=verifiedClaim(),mutated=verifiedClaim({statement:'Sabe'});assert.equal(golden.support.evidenceId,mutated.support.evidenceId);assert.equal(golden.support.startOffset,mutated.support.startOffset);assert.equal(golden.support.endOffset,mutated.support.endOffset);assert.equal(golden.support.spanHash,mutated.support.spanHash);assert.deepEqual(evidence.provenance,lineage(evidence.content));const out=verifier.verify(mutated,{selected:[evidence]});assert.equal(out.status,'CLAIM_UNSUPPORTED');assert.equal(out.citationEligible,false);});
test('canonical LF text is the only exact-span offset basis',()=>{const content='Line A\nLine B',evidence=selected({content,provenance:lineage(content)}),canonical=verifiedClaim({statement:'Line B',support:spanSupport({startOffset:7,endOffset:13,spanHash:contracts.sha256(Buffer.from('Line B'))})});assert.equal(verifier.verify(canonical,{selected:[evidence]}).status,'CLAIM_SUPPORTED');const rawOffset=verifiedClaim({statement:'Line B',support:spanSupport({startOffset:8,endOffset:14,spanHash:contracts.sha256(Buffer.from('Line B'))})});assert.equal(verifier.verify(rawOffset,{selected:[evidence]}).status,'CLAIM_INVALID');const crlf=verifiedClaim({statement:'Line A\r\nLine B',support:spanSupport({startOffset:0,endOffset:14,spanHash:contracts.sha256(Buffer.from(content))})});assert.equal(verifier.verify(crlf,{selected:[evidence]}).status,'CLAIM_INVALID');});
test('edition qualifier mismatch is scope mismatch independent of effective date',()=>{const editionQualifier=[{key:'edition',operator:'EQ',value:'2025',valueType:'INTEGER',unit:'NONE'}],evidenceFactValue=evidenceFact('e1',{qualifiers:editionQualifier}),evidence=selected({structuredFacts:[evidenceFactValue]}),claimFact=factPayload({qualifiers:[{...editionQualifier[0],value:'2024'}]});assert.equal(claimFact.effectiveAt,evidenceFactValue.effectiveAt);assert.equal(claimFact.jurisdiction,evidenceFactValue.jurisdiction);const out=verifier.verify(factClaim(claimFact),{selected:[evidence]});assert.equal(out.status,'CLAIM_SCOPE_MISMATCH');assert.equal(out.citationEligible,false);});
test('frozen multiple-claim severity ordering preserves every lower detail',()=>{const structured=selected({structuredFacts:[evidenceFact()]}),secondary=selected({id:'e2',evidenceClass:'secondary',authority:'secondary',verified:false,provenance:lineage('Safe harbor rule.',{chunkId:'chunk-2'})}),invalidBase=verifiedClaim({statement:'harbor',support:spanSupport({startOffset:5,endOffset:11,spanHash:contracts.sha256(Buffer.from('harbor'))})});const ordered=[factClaim(factPayload({value:'11'})),factClaim(factPayload({unit:'KILOMETRE_PER_HOUR'})),{...invalidBase,supported:true},verifiedClaim({claimType:'INFERENCE'}),verifiedClaim({support:spanSupport({evidenceId:'e2'})}),verifiedClaim({support:spanSupport({evidenceId:'missing'}),requiresAuthoritative:false}),verifiedClaim()];const expectations=[['CLAIM_CONTRADICTED','CLAIM_CONTRADICTED'],['CLAIM_SCOPE_MISMATCH','CLAIM_SCOPE_MISMATCH'],['INVALID_CLAIMS','CLAIM_INVALID'],['INVALID_CLAIMS','CLAIM_UNVERIFIABLE'],['SOURCE_INSUFFICIENT','CLAIM_AUTHORITY_INSUFFICIENT'],['SOURCE_INSUFFICIENT','CLAIM_UNSUPPORTED'],['GROUNDED','CLAIM_SUPPORTED']];for(let start=0;start<ordered.length;start++){const active=ordered.slice(start),out=grounding.create().run({retrievalResult:retrievalResult([structured,secondary]),claims:active});assert.equal(out.status,expectations[start][0]);const details=new Set(out.claims.map(x=>x.verificationStatus));assert.equal(details.has(expectations[start][1]),true);for(let lower=start+1;lower<ordered.length;lower++)assert.equal(details.has(expectations[lower][1]),true);if(out.status!=='GROUNDED')assert.equal(out.citations.length,0);}});
test('upstream integrity provenance conflict retrieval and insufficiency precedence are direct',()=>{const claim=verifiedClaim();assert.throws(()=>grounding.create().run({retrievalResult:retrievalResult([selected({provenance:lineage('DIFFERENT')})]),claims:[claim]}),e=>e.code==='HASH_MISMATCH');const missing=grounding.create().run({retrievalResult:retrievalResult([selected({provenance:{}})]),claims:[claim]});assert.equal(missing.status,'PROVENANCE_INCOMPLETE');assert.equal(missing.citations.length,0);const conflict=grounding.create().run({retrievalResult:retrievalResult([selected()],'EVIDENCE_CONFLICT'),claims:[claim]});assert.equal(conflict.status,'EVIDENCE_CONFLICT');const retrievalFailure=grounding.create().run({retrievalResult:{...retrievalResult([],'SOURCE_INSUFFICIENT'),rejected:[{adapterId:'broken',reason:'ADAPTER_ERROR'}]},claims:[claim]});assert.equal(retrievalFailure.status,'RETRIEVAL_FAILURE');const insufficient=grounding.create().run({retrievalResult:retrievalResult([],'SOURCE_INSUFFICIENT'),claims:[claim]});assert.equal(insufficient.status,'SOURCE_INSUFFICIENT');for(const out of [missing,conflict,retrievalFailure,insufficient])assert.equal(out.citations.length,0);});
test('all required failure audit events have applicable common fields and deterministic order',()=>{function runAudit(claim,evidence=selected(),options={}){const log=auditModule.create({now:()=> '2026-08-11T00:00:00.000Z'});let output;try{output=verifier.verify(claim,{selected:[evidence],audit:log,transactionId:'tx-failure',...options});}catch(error){output=error;}return {output,entries:log.snapshot()};}const structured=selected({structuredFacts:[evidenceFact()]}),secondary=selected({evidenceClass:'secondary',authority:'secondary',verified:false});const flows=[
  [{...verifiedClaim(),arbitrary:'x'},selected(),'CLAIM_SCHEMA_REJECTED'],
  [verifiedClaim({support:spanSupport({evidenceId:'missing'})}),selected(),'CLAIM_SUPPORT_REJECTED'],
  [factClaim(factPayload({value:'11'})),structured,'CLAIM_CONTRADICTION_DETECTED'],
  [factClaim(factPayload({unit:'KILOMETRE_PER_HOUR'})),structured,'CLAIM_SCOPE_MISMATCH'],
  [verifiedClaim(),secondary,'CLAIM_AUTHORITY_INSUFFICIENT'],
  [verifiedClaim({claimType:'SPECULATION'}),selected(),'CLAIM_UNVERIFIABLE']
];for(const [claim,evidence,event] of flows){const first=runAudit(claim,evidence),second=runAudit(claim,evidence);assert.deepEqual(first.entries.map(x=>x.reason),second.entries.map(x=>x.reason));assert.equal(first.entries.some(x=>x.reason===event),true);assert.equal(first.entries.at(-1).reason,'CITATION_ELIGIBILITY_DENIED');for(const entry of first.entries){assert.equal(entry.details.transactionId,'tx-failure');assert.equal(entry.details.verifierVersion,contracts.VERIFIER_VERSION);assert.equal(entry.details.claimSchemaVersion,contracts.CLAIM_SCHEMA);assert.equal(typeof entry.outcome,'string');assert.equal(typeof entry.reason,'string');if(entry.reason!=='CLAIM_RECEIVED'&&claim.support){assert.equal(entry.details.claimId,claim.claimId);assert.equal(entry.details.supportMode,claim.support.mode);if(entry.details.evidenceId!=null)assert.equal(entry.details.evidenceId,claim.support.evidenceId);}if(entry.reason===event||entry.reason==='CITATION_ELIGIBILITY_DENIED')assert.ok(entry.details.status);}const evaluated=first.entries.find(x=>x.reason==='EVIDENCE_CANDIDATE_EVALUATED');if(evaluated){for(const field of ['indexId','indexHash','policyId','policyHash','chunkId','chunkHash'])assert.ok(evaluated.details[field],`${event}:${field}`);const resultEntry=first.entries.find(x=>x.reason===event);for(const field of ['indexId','indexHash','policyId','policyHash','chunkId','chunkHash'])assert.ok(resultEntry.details[field],`${event}:result:${field}`);}}});
test('audit explicitly excludes claim span evidence query and excerpt sentinels',()=>{const statement='SENTINEL_EXACT_SPAN',content=`PREFIX ${statement} SENTINEL_EVIDENCE_BODY SENTINEL_LONG_EXCERPT_ABCDEFGHIJKLMNOPQRSTUVWXYZ`,evidence=selected({content,provenance:lineage(content)}),start=content.indexOf(statement),claim=verifiedClaim({statement,support:spanSupport({startOffset:start,endOffset:start+statement.length,spanHash:contracts.sha256(Buffer.from(statement))})}),log=auditModule.create({now:()=> '2026-08-11T00:00:00.000Z'});verifier.verify(claim,{selected:[evidence],audit:log,transactionId:'tx-sentinel',query:'SENTINEL_FULL_QUERY'});const serialized=JSON.stringify(log.snapshot());for(const forbidden of [statement,'SENTINEL_EVIDENCE_BODY','SENTINEL_FULL_QUERY','SENTINEL_LONG_EXCERPT_ABCDEFGHIJKLMNOPQRSTUVWXYZ'])assert.equal(serialized.includes(forbidden),false);});
test('full functional result is insertion-order invariant and contains no nondeterministic fields',()=>{const claim=verifiedClaim(),reordered={requiresAuthoritative:claim.requiresAuthoritative,support:{offsetEncoding:claim.support.offsetEncoding,spanHash:claim.support.spanHash,endOffset:claim.support.endOffset,startOffset:claim.support.startOffset,evidenceId:claim.support.evidenceId,mode:claim.support.mode},statement:claim.statement,claimType:claim.claimType,claimId:claim.claimId,schemaVersion:claim.schemaVersion},first=verifier.verify(claim,{selected:[selected()]}),second=verifier.verify(reordered,{selected:[selected()]});assert.equal(JSON.stringify(first),JSON.stringify(second));const serialized=JSON.stringify(first);for(const forbiddenKey of ['timestamp','duration','randomId','environmentPath','stack','message'])assert.equal(Object.prototype.hasOwnProperty.call(first,forbiddenKey),false);assert.equal(/[A-Z]:\\|\/home\/|node:internal|ClaimValidationError/u.test(serialized),false);});
test('legacy claims never become typed facts and structuredFacts do not alter Phase 2A conflict semantics',()=>{const evaluator=require('../retrieval/evidence-evaluator.js'),legacyA={key:'depth',value:'4m',scope:'port'},legacyB={key:'depth',value:'5m',scope:'port'},factA=evidenceFact('e1'),factB=evidenceFact('e2'),a=selected({claims:[legacyA],structuredFacts:[factA]}),b=selected({id:'e2',sourceId:'other',claims:[legacyB],structuredFacts:[factB],provenance:lineage('Safe harbor rule.',{sourceId:'other',chunkId:'chunk-2'})});assert.deepEqual(a.claims,[legacyA]);assert.equal(retrieval.evidence({id:'empty'}).structuredFacts.length,0);const legacyOnly=selected({claims:[legacyA],structuredFacts:[]});assert.equal(verifier.verify(factClaim(),{selected:[legacyOnly]}).status,'CLAIM_UNSUPPORTED');const withFacts=evaluator.evaluate({items:[a,b],requireAuthoritative:true}),withoutFacts=evaluator.evaluate({items:[selected({claims:[legacyA]}),selected({id:'e2',sourceId:'other',claims:[legacyB],provenance:lineage('Safe harbor rule.',{sourceId:'other',chunkId:'chunk-2'})})],requireAuthoritative:true});assert.equal(withFacts.status,'EVIDENCE_CONFLICT');assert.equal(withFacts.status,withoutFacts.status);assert.deepEqual(withFacts.conflicts,withoutFacts.conflicts);});
test('all-supported distinct multi-claim grounding preserves citations lineage and PLAN_ONLY boundaries',()=>{const evidence=selected(),firstClaim=verifiedClaim(),secondClaim=verifiedClaim({statement:'harbor',support:spanSupport({startOffset:5,endOffset:11,spanHash:contracts.sha256(Buffer.from('harbor'))})});assert.notEqual(firstClaim.claimId,secondClaim.claimId);let claimGeneration=0,expert=0,navigation=0,network=0;const priorGenerator=globalThis.SinbadClaimGenerator,priorExpert=globalThis.SinbadExpert,priorNavigation=globalThis.SinbadNavigation,priorFetch=globalThis.fetch;try{globalThis.SinbadClaimGenerator={generate(){claimGeneration++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};const execute=()=>grounding.create({clock:()=>100}).run({transactionId:'phase2e-multi-success',retrievalResult:retrievalResult([evidence]),claims:[firstClaim,secondClaim]}),first=execute(),second=execute(),expectedCitationIds=new Map([firstClaim,secondClaim].map(claim=>[claim.claimId,`citation:${claim.claimId}:e1`])),lineageKeys=['indexId','indexHash','policyId','policyHash','issuerId','sourceId','documentId','editionId','canonicalHash','chunkId','chunkContentHash','chunkerVersion','license','authorityDecision','editionStatus'];assert.equal(first.status,'GROUNDED');assert.deepEqual(first.claims.map(claim=>claim.verificationStatus),['CLAIM_SUPPORTED','CLAIM_SUPPORTED']);assert.equal(first.citations.length,2);assert.equal(new Set(first.citations.map(citation=>citation.id)).size,2);for(const claim of first.claims)assert.deepEqual(claim.citationIds,[expectedCitationIds.get(claim.claimId)]);assert.deepEqual(first.evidenceUsed,['e1']);for(const citation of first.citations){assert.equal(citation.evidenceId,'e1');for(const key of lineageKeys)assert.deepEqual(citation.provenance[key],evidence.provenance[key]);}assert.deepEqual(first,second);const phase2c=orchestrationContract.result({transactionId:'phase2e-multi-success',status:'GROUNDED_PLAN_READY'});assert.equal(phase2c.execution.mode,'PLAN_ONLY');assert.equal(phase2c.execution.allowed,false);assert.equal(phase2c.execution.expertExecutionPerformed,false);assert.equal(phase2c.security.navigationExecutionPerformed,false);assert.equal(phase2c.security.navigationMathematicsActivated,false);assert.equal(claimGeneration,0);assert.equal(expert,0);assert.equal(navigation,0);assert.equal(network,0);}finally{globalThis.SinbadClaimGenerator=priorGenerator;globalThis.SinbadExpert=priorExpert;globalThis.SinbadNavigation=priorNavigation;globalThis.fetch=priorFetch;}});
module.exports={spanSupport,claimPayload,factPayload,evidenceFact};
