'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {createHash}=require('node:crypto');const adapter=require('../adapters/supabase-rollout-recovery-authorization-audit.js');
const actor='a'.repeat(64),attestation='b'.repeat(64),purpose='c'.repeat(64),decidedAt=1000;function event(overrides={}){const value={version:adapter.AUDIT_VERSION,actorHash:actor,attestationHash:attestation,purposeHash:purpose,decision:'AUTHORIZED',decidedAt,...overrides};value.eventHash=createHash('sha256').update([value.version,value.actorHash,value.attestationHash,value.purposeHash,value.decision,value.decidedAt].join('\n')).digest('hex');return Object.freeze(value);}function create(handler){return adapter.create({serviceRole:true,client:{rpc:handler}});}
const GOLDEN_HASH='b9ce830595d270d8777f5627aeefdd5d16a44bd7eb23bcbd912a3ab111bc2287';
test('requires service role and exposes a frozen durable append-only adapter',()=>{assert.throws(()=>adapter.create(),/service-role/u);assert.throws(()=>adapter.create({serviceRole:false,client:{rpc(){}}}),/service-role/u);const value=create(async()=>({data:'RECORDED',error:null}));assert.equal(value.version,adapter.AUDIT_VERSION);assert.equal(value.durable,true);assert.ok(Object.isFrozen(value));assert.deepEqual(Object.keys(value),['version','durable','append']);});
test('appends exact minimal fields and accepts idempotent replay',async()=>{for(const data of ['RECORDED','ALREADY_RECORDED']){let seen;const value=create(async(name,args)=>{seen=[name,args];return {data,error:null};});assert.equal(await value.append(event()),true);assert.deepEqual(seen,['append_rollout_recovery_authorization_audit',{p_actor_hash:actor,p_attestation_hash:attestation,p_purpose_hash:purpose,p_decision:'AUTHORIZED',p_decided_at_ms:decidedAt,p_event_hash:event().eventHash}]);}});
test('locks the JS and SQL canonical hash recipe to one golden vector',()=>{assert.equal(event().eventHash,GOLDEN_HASH);const sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260817_rollout_recovery_authorization_audit.sql'),'utf8');for(const fragment of ["'sinbad-trusted-rollout-recovery-authorization-audit/3N-v1'","p_actor_hash || chr(10)","p_attestation_hash || chr(10)","p_purpose_hash || chr(10)","p_decision || chr(10) || p_decided_at_ms::text"])assert.ok(sql.includes(fragment));});
test('invalid malformed denied and transport failures fail closed before or after RPC',async()=>{let calls=0;const value=create(async()=>{calls++;throw new Error('offline');});for(const changed of [{actorHash:'bad'},{decision:'OTHER'},{decidedAt:-1},{eventHash:'bad'},{version:'wrong'}])assert.equal(await value.append({...event(),...changed}),false);assert.equal(calls,0);assert.equal(await value.append(event()),false);for(const response of [{data:'DENIED',error:null},{data:'HASH_MISMATCH',error:null},{data:true,error:null},{data:'RECORDED',error:{message:'no'}}])assert.equal(await create(async()=>response).append(event()),false);});
test('forward migration enforces recomputed hashes immutability RLS and service role RPC',()=>{const sql=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20260817_rollout_recovery_authorization_audit.sql'),'utf8');for(const pattern of [/^begin;/iu,/create table public\.rollout_recovery_authorization_audit/iu,/create extension if not exists pgcrypto/iu,/enable row level security/iu,/event_hash text not null unique/iu,/rows are immutable/iu,/before update or delete/iu,/before truncate/iu,/auth\.role\(\)<>'service_role'/iu,/p_event_hash<>v_expected/iu,/on conflict \(event_hash\) do nothing/iu,/a\.actor_hash=p_actor_hash/iu,/return 'ALREADY_RECORDED'/iu,/return 'CONFLICT'/iu,/revoke all on function public\.append_rollout_recovery_authorization_audit/iu,/grant execute on function public\.append_rollout_recovery_authorization_audit/iu,/commit;/iu])assert.match(sql,pattern);});
test('the internal Supabase audit subpath remains outside package exports',()=>{assert.equal(require('../package.json').exports['./supabase-rollout-recovery-authorization-audit'],undefined);assert.throws(()=>require('@sinbad-ai/core-terminal-delivery/supabase-rollout-recovery-authorization-audit'),error=>error&&error.code==='ERR_PACKAGE_PATH_NOT_EXPORTED');});
