'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const receipts=require('../delivery/terminal-delivery-receipt.js');const verifier=require('../verification/terminal-delivery-receipt-verifier.js');
let sequence=0;function fixture(outcome='DELIVERED'){const n=++sequence,answer=`Doğrulanmış yanıt ${n}`,transactionId=`tx-2q-${n}`,sessionId='session-a',channelId='atlas-ui',attemptId=`attempt-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse})),authorization=authorizer.authorize(delivery,{sessionId,channelId,deliveryNonce:`nonce-${n}`,now:()=>1000}),receipt=receipts.record(authorization,{outcome,sessionId,channelId,attemptId});return {receipt,expected:{transactionId,sessionId,channelId,outcome,attemptId},answer};}
test('independently verifies an authentic terminal receipt and exposes no response target or upstream hashes',()=>{const f=fixture(),result=verifier.verify(f.receipt,f.expected),manifest={version:verifier.VERIFICATION_VERSION,verifierVersion:verifier.VERIFIER_VERSION,status:'DELIVERY_RECEIPT_VERIFIED',...f.expected,authorizationHash:f.receipt.authorizationHash,deliveryHash:f.receipt.deliveryHash,receiptHash:f.receipt.receiptHash,sourceCount:f.receipt.sourceCount};assert.equal(result.status,'DELIVERY_RECEIPT_VERIFIED');assert.equal(result.reasonCode,null);assert.equal(result.receiptHash,f.receipt.receiptHash);assert.equal(result.sourceCount,1);assert.equal(result.verificationHash,verifier.sha256(verifier.canonical(manifest)));assert.equal(JSON.stringify(result).includes(f.answer),false);for(const key of ['transactionId','sessionId','channelId','attemptId','authorizationHash','deliveryHash'])assert.equal(key in result,false);assert.ok(Object.isFrozen(result));assert.equal(verifier.isAuthenticVerification(result),true);});
test('verifies FAILED as a valid terminal outcome',()=>{const f=fixture('FAILED');assert.equal(verifier.verify(f.receipt,f.expected).status,'DELIVERY_RECEIPT_VERIFIED');});
test('an authentic receipt can produce only one verification',()=>{const f=fixture();assert.equal(verifier.verify(f.receipt,f.expected).status,'DELIVERY_RECEIPT_VERIFIED');const replay=verifier.verify(f.receipt,f.expected);assert.equal(replay.status,'DELIVERY_RECEIPT_INVALID');assert.equal(replay.reasonCode,'DELIVERY_RECEIPT_VERIFICATION_DENIED');assert.equal(verifier.isAuthenticVerification(replay),false);});
test('isBound and boundSnapshot require every hidden and public binding',()=>{const f=fixture(),value=verifier.verify(f.receipt,f.expected),snapshot=verifier.boundSnapshot(value,f.expected);assert.equal(verifier.isBound(value,f.expected),true);assert.equal(snapshot.outcome,f.expected.outcome);assert.ok(Object.isFrozen(snapshot));for(const expected of [{...f.expected,transactionId:'other'},{...f.expected,sessionId:'other'},{...f.expected,channelId:'other'},{...f.expected,attemptId:'other'},{...f.expected,outcome:'FAILED'},{}]){assert.equal(verifier.isBound(value,expected),false);assert.equal(verifier.boundSnapshot(value,expected),null);}for(const candidate of [{...value,verificationHash:'0'.repeat(64)},{...value,status:'other'},{...value,sourceCount:2}])assert.equal(verifier.isBound(candidate,f.expected),false);});
test('copied cloned proxy and altered receipts fail closed uniformly',()=>{const f=fixture(),cases=[{...f.receipt},structuredClone(f.receipt),new Proxy(f.receipt,{}),Object.freeze({...f.receipt,sourceCount:2}),Object.freeze({...f.receipt,receiptHash:'0'.repeat(64)}),Object.freeze({...f.receipt,version:'other'}),Object.freeze({...f.receipt,reasonCode:'other'}),Object.freeze({...f.receipt,sourceCount:NaN})];for(const value of cases){const result=verifier.verify(value,f.expected);assert.equal(result.status,'DELIVERY_RECEIPT_INVALID');assert.equal(result.reasonCode,'DELIVERY_RECEIPT_VERIFICATION_DENIED');assert.equal('transactionId' in result,false);assert.equal(result.receiptHash,null);}});
test('receipt hash matches the independently normalized payload oracle',()=>{const f=fixture();assert.equal(f.receipt.receiptHash,verifier.sha256(verifier.canonical(receipts.receiptPayload(f.receipt))));assert.equal(receipts.receiptPayload({...f.receipt,sourceCount:NaN}).sourceCount,null);});
test('shared payload bounds source count and verifier pins the exact Phase 2P version',()=>{assert.equal(verifier.EXPECTED_RECEIPT_VERSION,receipts.RECEIPT_VERSION);for(const sourceCount of [-1,65,1.5,NaN])assert.equal(receipts.receiptPayload({sourceCount}).sourceCount,null);for(const sourceCount of [0,64])assert.equal(receipts.receiptPayload({sourceCount}).sourceCount,sourceCount);});
test('blocked receipts are non-authentic and cannot cross the verification boundary',()=>{const blocked=receipts.record({},{}),result=verifier.verify(blocked,{});assert.equal(receipts.isAuthenticReceipt(blocked),false);assert.equal(result.status,'DELIVERY_RECEIPT_INVALID');assert.equal(verifier.isAuthenticVerification(result),false);assert.ok(Object.isFrozen(result));});
test('retargeted or malformed expectations fail closed without identifier echo',()=>{const f=fixture(),cases=[{...f.expected,transactionId:'other'},{...f.expected,sessionId:'other'},{...f.expected,channelId:'other'},{...f.expected,attemptId:'other'},{...f.expected,outcome:'FAILED'},{...f.expected,attemptId:'bad\u200bid'},{}];for(const expected of cases){const result=verifier.verify(f.receipt,expected);assert.equal(result.status,'DELIVERY_RECEIPT_INVALID');for(const key of ['transactionId','sessionId','channelId','attemptId'])assert.equal(key in result,false);}});
test('receipt verifier invokes no model expert navigation or network',()=>{const f=fixture();let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(verifier.verify(f.receipt,f.expected).status,'DELIVERY_RECEIPT_VERIFIED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
