'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const recovery=require('../adapters/trusted-terminal-rollout-recovery.js');
const hash='c'.repeat(64);
function journal(status='UNKNOWN',overrides={}){return {version:recovery.EXPECTED_JOURNAL_VERSION,durable:true,inspect:async()=>({status:'FOUND',state:{status}}),settle:async()=>({status:'SETTLED'}),...overrides};}
function create(overrides={}){return recovery.create({activationJournal:journal(),resolve:async()=>'PENDING',recoveryTimeoutMs:5000,...overrides});}
test('requires trusted bounded dependencies and exposes a frozen minimal API',()=>{assert.throws(()=>recovery.create(),/activationJournal/u);assert.throws(()=>create({activationJournal:journal('UNKNOWN',{inspect:null})}),/activationJournal/u);assert.throws(()=>create({resolve:null}),/resolve/u);assert.throws(()=>create({recoveryTimeoutMs:999}),/timeout/u);const value=create();assert.deepEqual(Object.keys(value),['version','recover']);assert.ok(Object.isFrozen(value));});
test('returns existing terminal journal states without querying provider',async()=>{for(const [state,status] of [['APPLIED','ROLLOUT_RECOVERY_APPLIED'],['REJECTED','ROLLOUT_RECOVERY_REJECTED']]){let resolves=0;const value=create({activationJournal:journal(state),resolve:async()=>{resolves++;return 'APPLIED';}}),result=await value.recover(hash);assert.equal(result.status,status);assert.equal(resolves,0);}});
test('resolves pending or unknown and durably compare-and-sets terminal state',async()=>{for(const [current,provider,status] of [['PENDING','APPLIED','ROLLOUT_RECOVERY_APPLIED'],['UNKNOWN','REJECTED','ROLLOUT_RECOVERY_REJECTED']]){const calls=[],value=create({activationJournal:journal(current,{settle:async(...args)=>{calls.push(args);return {status:'SETTLED'};}}),resolve:async input=>{calls.push([input]);return provider;}}),result=await value.recover(hash);assert.equal(result.status,status);assert.deepEqual(calls[1],[hash,current,provider]);assert.ok(Object.isFrozen(calls[0][0]));}});
test('absence outage invalid provider and settlement failure fail closed',async()=>{const cases=[[journal('UNKNOWN',{inspect:async()=>({status:'ABSENT',state:null})}),async()=>'APPLIED','ROLLOUT_RECOVERY_BLOCKED'],[journal('UNKNOWN',{inspect:async()=>({status:'UNAVAILABLE',state:null})}),async()=>'APPLIED','ROLLOUT_RECOVERY_BLOCKED'],[journal(),async()=>'OTHER','ROLLOUT_RECOVERY_UNSETTLED'],[journal('UNKNOWN',{settle:async()=>({status:'CONFLICT'})}),async()=>'APPLIED','ROLLOUT_RECOVERY_UNSETTLED']];for(const [activationJournal,resolve,status] of cases)assert.equal((await create({activationJournal,resolve}).recover(hash)).status,status);assert.equal((await create().recover('bad')).reasonCode,'RECOVERY_HASH_INVALID');});
test('ALREADY_SETTLED requires inspection of the identical target state',async()=>{for(const [observed,status] of [['APPLIED','ROLLOUT_RECOVERY_APPLIED'],['REJECTED','ROLLOUT_RECOVERY_UNSETTLED']]){let inspections=0;const value=create({activationJournal:journal('UNKNOWN',{inspect:async()=>({status:'FOUND',state:{status:inspections++===0?'UNKNOWN':observed}}),settle:async()=>({status:'ALREADY_SETTLED'})}),resolve:async()=>'APPLIED'});assert.equal((await value.recover(hash)).status,status);}});
test('concurrent recovery across adapter instances performs one provider query',async()=>{let release,resolves=0;const wait=new Promise(done=>{release=done;}),resolve=async()=>{resolves++;await wait;return 'APPLIED';},firstAdapter=create({resolve}),secondAdapter=create({resolve}),first=firstAdapter.recover(hash),second=secondAdapter.recover(hash);release();const results=await Promise.all([first,second]);assert.equal(resolves,1);assert.equal(results.filter(x=>x.status==='ROLLOUT_RECOVERY_APPLIED').length,1);assert.equal(results.filter(x=>x.reasonCode==='RECOVERY_IN_PROGRESS').length,1);});
test('distinguishes a durable CAS conflict from settlement transport failure',async()=>{for(const [settleStatus,reason,diagnostic] of [['CONFLICT','RECOVERY_JOURNAL_CONFLICT','RECOVERY_JOURNAL_CONFLICT'],['UNAVAILABLE','RECOVERY_JOURNAL_SETTLEMENT_REQUIRED','RECOVERY_JOURNAL_SETTLEMENT_FAILED']]){const events=[],value=create({activationJournal:journal('UNKNOWN',{settle:async()=>({status:settleStatus})}),resolve:async()=>'APPLIED',diagnose:event=>events.push(event)}),result=await value.recover(hash);assert.equal(result.reasonCode,reason);assert.equal(events.at(-1).code,diagnostic);}});
