'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const gate=require('../verification/grounded-answer-release-gate.js');
function fixture(overrides={}){const sealInput={transactionId:'tx-2l',query:'Güvenlik şartı',answerHash:'a'.repeat(64),mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:['e2','e1']};const answerSeal=sealer.seal(sealInput);const groundedAnswer={status:'GROUNDED',answer:'Güvenlik şartı',composition:{answerHash:sealInput.answerHash},evidenceUsed:['e1','e2'],citations:[{id:'c2'},{id:'c1'}]};return {sealInput,answerSeal,groundedAnswer,...overrides};}
function binding(value){return {transactionId:value.sealInput.transactionId,queryHash:value.answerSeal.queryHash,answerHash:value.groundedAnswer.composition.answerHash,sealHash:value.answerSeal.sealHash,evidenceIds:value.groundedAnswer.evidenceUsed,citationIds:value.groundedAnswer.citations.map(item=>item.id)};}
test('authentic sealed answer receives deterministic immutable release',()=>{const value=fixture(),first=gate.release(value,{answerSealer:sealer}),second=gate.release(value,{answerSealer:sealer});assert.equal(first.status,'ANSWER_RELEASED');assert.deepEqual(first,second);assert.deepEqual(first.evidenceIds,['e1','e2']);assert.deepEqual(first.citationIds,['c1','c2']);assert.equal(gate.isAuthenticRelease(first),true);assert.equal(gate.isBound(first,binding(value)),true);assert.ok(Object.isFrozen(first));assert.ok(Object.isFrozen(first.citationIds));});
test('release cannot replay across any delivery binding',()=>{const value=fixture(),release=gate.release(value,{answerSealer:sealer}),base=binding(value),mutations=[{transactionId:'other'},{queryHash:'b'.repeat(64)},{answerHash:'b'.repeat(64)},{sealHash:'b'.repeat(64)},{evidenceIds:['e1']},{citationIds:['c1']}];for(const mutation of mutations)assert.equal(gate.isBound(release,{...base,...mutation}),false);});
test('copied forged unsealed and mismatched answers fail closed',()=>{const value=fixture(),valid=gate.release(value,{answerSealer:sealer});assert.equal(gate.isBound({...valid},binding(value)),false);const cases=[{...value,answerSeal:{...value.answerSeal}},{...value,groundedAnswer:{...value.groundedAnswer,composition:{answerHash:'b'.repeat(64)}}},{...value,groundedAnswer:{...value.groundedAnswer,evidenceUsed:['e1']}},{...value,groundedAnswer:{...value.groundedAnswer,citations:[]}}];for(const candidate of cases){const result=gate.release(candidate,{answerSealer:sealer});assert.equal(result.status,'RELEASE_BLOCKED');assert.equal(result.releaseHash,null);}});
test('release gate invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(gate.release(fixture(),{answerSealer:sealer}).status,'ANSWER_RELEASED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
