'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const receipts=require('../delivery/terminal-delivery-receipt.js');
let sequence=0;function authorization(){const n=++sequence,answer=`Güvenlik şartı ${n}`,answerHash=projector.sha256(answer),sealInput={transactionId:`tx-2p-${n}`,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId:sealInput.transactionId,publicResponse}));return authorizer.authorize(delivery,{sessionId:'session-a',channelId:'atlas-ui',deliveryNonce:`nonce-${n}`,now:()=>1000});}
function input(overrides={}){return {outcome:'DELIVERED',sessionId:'session-a',channelId:'atlas-ui',attemptId:`attempt-${sequence}`,...overrides};}
test('records one minimal terminal receipt without answer or sources',()=>{const auth=authorization(),result=receipts.record(auth,input());assert.equal(result.status,'DELIVERY_RECEIPT_RECORDED');assert.equal(result.outcome,'DELIVERED');assert.equal(result.sourceCount,1);assert.equal('answer' in result,false);assert.equal('sources' in result,false);assert.ok(/^[a-f0-9]{64}$/u.test(result.receiptHash));assert.ok(Object.isFrozen(result));});
test('failed presentation is a valid terminal outcome without response data',()=>{const result=receipts.record(authorization(),input({outcome:'FAILED'}));assert.equal(result.status,'DELIVERY_RECEIPT_RECORDED');assert.equal(result.outcome,'FAILED');assert.equal(JSON.stringify(result).includes('Güvenlik şartı'),false);});
test('same authorization can record only one terminal result',()=>{const auth=authorization();assert.equal(receipts.record(auth,input()).status,'DELIVERY_RECEIPT_RECORDED');for(const outcome of ['DELIVERED','FAILED']){const result=receipts.record(auth,input({outcome,attemptId:`retry-${outcome}`}));assert.equal(result.status,'DELIVERY_RECEIPT_BLOCKED');assert.equal(result.reasonCode,'DELIVERY_RECEIPT_DENIED');}});
test('copied proxy mismatched target invalid outcome and malformed attempt fail closed without identifier echo',()=>{const auth=authorization(),cases=[[{...auth},input()],[new Proxy(auth,{}),input()],[auth,input({sessionId:'other'})],[auth,input({channelId:'other'})],[auth,input({outcome:'PENDING'})],[auth,input({attemptId:'bad\u200bid'})]];for(const [value,data] of cases){const result=receipts.record(value,data);assert.equal(result.status,'DELIVERY_RECEIPT_BLOCKED');assert.equal(result.transactionId,null);}});
test('receipt recorder invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(receipts.record(authorization(),input()).status,'DELIVERY_RECEIPT_RECORDED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
