'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const gate=require('../delivery/terminal-completion-gate.js');const state=require('../adapters/terminal-state-transition.js');
let sequence=0;function fixture(outcome='DELIVERED'){const n=++sequence,answer=`Durum yanıtı ${n}`,transactionId=`tx-2w-${n}`,sessionId='session-a',channelId='atlas-ui',attemptId=`attempt-${n}`,closureId=`closure-${n}`,auditId=`audit-${n}`,transitionId=`transition-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse})),authorization=authorizer.authorize(delivery,{sessionId,channelId,deliveryNonce:`nonce-${n}`,now:()=>1000}),context={transactionId,sessionId,channelId,attemptId,closureId,auditId,outcome},completion=gate.complete(authorization,context);return {completion,context:{...context,transitionId},answer};}
test('applies one bound DELIVERED completion as a terminal success state',()=>{const f=fixture(),result=state.transition(f.completion,f.context),manifest={version:state.TRANSITION_VERSION,status:'TERMINAL_STATE_APPLIED',transitionId:f.context.transitionId,transactionId:f.context.transactionId,sessionId:f.context.sessionId,channelId:f.context.channelId,terminalState:'DELIVERY_SUCCEEDED',outcome:'DELIVERED',sourceCount:result.sourceCount,completionHash:result.completionHash};assert.equal(result.terminalState,'DELIVERY_SUCCEEDED');assert.equal(result.transitionHash,state.sha256(state.canonical(manifest)));for(const key of ['transitionId','transactionId','sessionId','channelId','answer','sources'])assert.equal(key in result,false);assert.equal(state.isAuthenticTransition(result),true);assert.ok(Object.isFrozen(result));});
test('maps FAILED only to a verified terminal failure state',()=>{const f=fixture('FAILED'),result=state.transition(f.completion,f.context);assert.equal(result.terminalState,'DELIVERY_FAILED');assert.equal(result.outcome,'FAILED');});
test('a completion can update terminal state only once',()=>{const f=fixture();assert.equal(state.transition(f.completion,f.context).status,'TERMINAL_STATE_APPLIED');assert.equal(state.transition(f.completion,{...f.context,transitionId:'retry'}).status,'TERMINAL_STATE_BLOCKED');});
test('copies clones proxies and binding mismatches fail closed',()=>{const f=fixture(),cases=[[{...f.completion},f.context],[structuredClone(f.completion),f.context],[JSON.parse(JSON.stringify(f.completion)),f.context],[new Proxy(f.completion,{}),f.context],[f.completion,{...f.context,transactionId:'other'}],[f.completion,{...f.context,sessionId:'other'}],[f.completion,{...f.context,channelId:'other'}],[f.completion,{...f.context,attemptId:'other'}],[f.completion,{...f.context,closureId:'other'}],[f.completion,{...f.context,auditId:'other'}],[f.completion,{...f.context,outcome:'FAILED'}],[f.completion,{...f.context,transitionId:'bad\u200bid'}],[f.completion,{}]];for(const [value,context] of cases){const result=state.transition(value,context);assert.equal(result.status,'TERMINAL_STATE_BLOCKED');assert.equal(result.transitionHash,null);assert.equal(state.isAuthenticTransition(result),false);}});
test('intermediate chain objects can never update adapter terminal state',()=>{const context={transactionId:'tx',sessionId:'session',channelId:'ui',attemptId:'attempt',closureId:'closure',auditId:'audit',outcome:'DELIVERED',transitionId:'transition'};for(const value of [{},Object.freeze({status:'DELIVERY_RECEIPT_RECORDED'}),Object.freeze({status:'TERMINAL_CLOSURE_CONFIRMED'}),Object.freeze({status:'TERMINAL_AUDIT_VERIFIED'})])assert.equal(state.transition(value,context).status,'TERMINAL_STATE_BLOCKED');});
test('state transition invokes no model expert navigation or network',()=>{const f=fixture();let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(state.transition(f.completion,f.context).status,'TERMINAL_STATE_APPLIED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
