'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const activation=require('../adapters/trusted-terminal-rollout-activation.js');
const actor='b'.repeat(64);let time=1000;
function journal(overrides={}){return {version:activation.EXPECTED_JOURNAL_VERSION,durable:true,begin:async()=>({status:'BEGUN'}),settle:async()=>({status:'SETTLED'}),inspect:async()=>({status:'ABSENT',state:null}),...overrides};}
function create(overrides={}){return activation.create({serviceRole:true,actorHash:actor,client:{rpc:async name=>name.startsWith('verify_')?{data:true,error:null}:{data:[],error:null}},limit:10,slaMs:120000,pageSize:10,maxEvents:100,ttlMs:5000,purpose:'terminal-rollout',now:()=>time,activationTimeoutMs:5000,activate:async()=>true,resolve:async()=>'PENDING',activationJournal:journal(),...overrides});}
test('requires the exact durable journal contract',()=>{for(const activationJournal of [null,{},journal({version:'wrong'}),journal({durable:false}),journal({begin:null}),journal({settle:null}),journal({inspect:null})])assert.throws(()=>create({activationJournal}),/trusted durable journal/u);});
test('begins before activation and settles an applied outcome',async()=>{time=1000;const calls=[],gate=create({activationJournal:journal({begin:async hash=>{calls.push(['begin',hash]);return {status:'BEGUN'};},settle:async(hash,expected,status)=>{calls.push(['settle',hash,expected,status]);return {status:'SETTLED'};}}),activate:async({attestationHash})=>{calls.push(['activate',attestationHash]);return true;}}),result=await gate.activate(await gate.issue());assert.equal(result.status,'TRUSTED_ROLLOUT_ACTIVATION_APPLIED');assert.deepEqual(calls.map(x=>x[0]),['begin','activate','settle']);assert.deepEqual(calls[2].slice(2),['PENDING','APPLIED']);assert.equal(new Set(calls.map(x=>x[1])).size,1);});
test('begin denial blocks before the side effect',async()=>{time=1000;for(const status of ['EXISTS','DENIED','UNAVAILABLE']){let activations=0;const gate=create({activationJournal:journal({begin:async()=>({status})}),activate:async()=>{activations++;return true;}}),result=await gate.activate(await gate.issue());assert.equal(result.status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');assert.equal(result.reasonCode,'ACTIVATION_JOURNAL_REQUIRED');assert.equal(activations,0);}});
test('journal transport rejection is contained before activation',async()=>{time=1000;let activations=0;const gate=create({activationJournal:journal({begin:async()=>{throw new Error('offline');}}),activate:async()=>{activations++;return true;}}),result=await gate.activate(await gate.issue());assert.equal(result.status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');assert.equal(result.reasonCode,'ACTIVATION_JOURNAL_REQUIRED');assert.equal(activations,0);});
test('ambiguous activation durably settles UNKNOWN before reconciliation',async()=>{time=1000;const settles=[],gate=create({activationJournal:journal({settle:async(...args)=>{settles.push(args);return {status:'SETTLED'};}}),activate:async()=>{throw new Error('ambiguous');},resolve:async()=>'APPLIED'}),pending=await gate.activate(await gate.issue());assert.equal(pending.reasonCode,'ACTIVATION_OUTCOME_UNKNOWN');assert.deepEqual(settles[0].slice(1),['PENDING','UNKNOWN']);const done=await gate.reconcile(pending);assert.equal(done.status,'TRUSTED_ROLLOUT_ACTIVATION_RECONCILED');assert.deepEqual(settles[1].slice(1),['UNKNOWN','APPLIED']);});
test('settlement failure remains unsettled and reconciliation retries no activation',async()=>{time=1000;let activations=0,settles=0;const gate=create({activationJournal:journal({settle:async()=>({status:++settles===1?'UNAVAILABLE':'SETTLED'})}),activate:async()=>{activations++;return true;},resolve:async()=>'APPLIED'}),pending=await gate.activate(await gate.issue());assert.equal(pending.reasonCode,'ACTIVATION_JOURNAL_SETTLEMENT_REQUIRED');const done=await gate.reconcile(pending);assert.equal(done.status,'TRUSTED_ROLLOUT_ACTIVATION_RECONCILED');assert.equal(activations,1);assert.equal(settles,2);});
test('ALREADY_SETTLED succeeds only after inspecting the identical target state',async()=>{time=1000;for(const [observed,expected] of [['APPLIED','TRUSTED_ROLLOUT_ACTIVATION_APPLIED'],['REJECTED','TRUSTED_ROLLOUT_ACTIVATION_UNSETTLED']]){const gate=create({activationJournal:journal({settle:async()=>({status:'ALREADY_SETTLED'}),inspect:async()=>({status:'FOUND',state:{status:observed}})})}),result=await gate.activate(await gate.issue());assert.equal(result.status,expected);}});
