'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');const authorizer=require('../delivery/single-use-delivery-authorizer.js');const receipts=require('../delivery/terminal-delivery-receipt.js');const rv=require('../verification/terminal-delivery-receipt-verifier.js');const closure=require('../delivery/single-use-terminal-closure.js');const cv=require('../verification/terminal-closure-verifier.js');const audit=require('../audit/terminal-delivery-audit-record.js');const verifier=require('../verification/terminal-delivery-audit-verifier.js');
let sequence=0;function fixture(outcome='DELIVERED'){const n=++sequence,answer=`Audit doğrulaması ${n}`,transactionId=`tx-2u-${n}`,sessionId='session-a',channelId='atlas-ui',attemptId=`attempt-${n}`,closureId=`closure-${n}`,auditId=`audit-${n}`,answerHash=projector.sha256(answer),sealInput={transactionId,query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:[`e${n}`]},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:[`e${n}`],citations:[{id:`c${n}`,title:'SOLAS',location:{},verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate}),delivery=adapter.adapt(contract.result({status:'GROUNDED_PLAN_READY',transactionId,publicResponse})),authorization=authorizer.authorize(delivery,{sessionId,channelId,deliveryNonce:`nonce-${n}`,now:()=>1000}),receipt=receipts.record(authorization,{outcome,sessionId,channelId,attemptId}),r=rv.verify(receipt,{transactionId,sessionId,channelId,outcome,attemptId}),closed=closure.close(r,{transactionId,sessionId,channelId,outcome,attemptId,closureId}),c=cv.verify(closed,{closureId,outcome}),record=audit.record(c,{closureId,outcome,auditId});return {record,expected:{auditId,closureId,outcome},answer};}
test('independently verifies one authentic audit record with a full-chain hash oracle',()=>{const f=fixture(),snapshot=audit.boundSnapshot(f.record,f.expected),result=verifier.verify(f.record,f.expected),manifest={version:verifier.VERIFICATION_VERSION,verifierVersion:verifier.VERIFIER_VERSION,status:'TERMINAL_AUDIT_VERIFIED',auditId:snapshot.auditId,closureId:snapshot.closureId,outcome:snapshot.outcome,sourceCount:snapshot.sourceCount,closureHash:snapshot.closureHash,closureVerificationHash:snapshot.closureVerificationHash,auditHash:snapshot.auditHash};assert.equal(result.status,'TERMINAL_AUDIT_VERIFIED');assert.equal(result.auditVerificationHash,verifier.sha256(verifier.canonical(manifest)));for(const key of ['auditId','closureId','transactionId','sessionId','channelId','attemptId','answer','sources','closureHash','closureVerificationHash'])assert.equal(key in result,false);assert.equal(JSON.stringify(result).includes(f.answer),false);assert.equal(verifier.isAuthenticResult(result),true);assert.ok(Object.isFrozen(result));});
test('verifies FAILED terminal audit records',()=>{const f=fixture('FAILED');assert.equal(verifier.verify(f.record,f.expected).outcome,'FAILED');});
test('pins Phase 2T and preserves a hidden bound snapshot',()=>{const f=fixture(),value=verifier.verify(f.record,f.expected);assert.equal(verifier.EXPECTED_RECORD_VERSION,audit.RECORD_VERSION);assert.equal(verifier.isBound(value,f.expected),true);assert.ok(Object.isFrozen(verifier.boundSnapshot(value,f.expected)));for(const expected of [{...f.expected,auditId:'other'},{...f.expected,closureId:'other'},{...f.expected,outcome:'FAILED'},{}])assert.equal(verifier.isBound(value,expected),false);});
test('blocked audit records are non-authentic and cannot verify',()=>{const blocked=audit.record({},{}),result=verifier.verify(blocked,{});assert.equal(audit.isAuthenticRecord(blocked),false);assert.equal(result.status,'TERMINAL_AUDIT_INVALID');assert.equal(verifier.isAuthenticResult(result),false);});
test('one audit record verifies only once',()=>{const f=fixture();assert.equal(verifier.verify(f.record,f.expected).status,'TERMINAL_AUDIT_VERIFIED');assert.equal(verifier.verify(f.record,f.expected).status,'TERMINAL_AUDIT_INVALID');});
test('copies clones proxies and retargeting fail closed uniformly',()=>{const f=fixture(),cases=[[{...f.record},f.expected],[structuredClone(f.record),f.expected],[new Proxy(f.record,{}),f.expected],[f.record,{...f.expected,auditId:'other'}],[f.record,{...f.expected,closureId:'other'}],[f.record,{...f.expected,outcome:'FAILED'}],[f.record,{}]];for(const [value,expected] of cases){const result=verifier.verify(value,expected);assert.equal(result.status,'TERMINAL_AUDIT_INVALID');assert.equal(result.reasonCode,'TERMINAL_AUDIT_VERIFICATION_DENIED');assert.equal(result.auditHash,null);}});
test('audit verifier invokes no model expert navigation or network',()=>{const f=fixture();let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(verifier.verify(f.record,f.expected).status,'TERMINAL_AUDIT_VERIFIED');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
