'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const sealer=require('../verification/grounded-answer-seal.js');const releaseGate=require('../verification/grounded-answer-release-gate.js');const projector=require('../delivery/public-grounded-response.js');const contract=require('../orchestrator/grounded-orchestration-contract.js');const adapter=require('../adapters/public-response-adapter.js');
function fixture(){const answer='Güvenlik şartı',answerHash=projector.sha256(answer),sealInput={transactionId:'tx-2n',query:answer,answerHash,mapVerifierVersion:'sinbad-independent-answer-citation-map-verifier/2J-v1',evidenceIds:['e1']},answerSeal=sealer.seal(sealInput),groundedAnswer={status:'GROUNDED',answer,composition:{answerHash},evidenceUsed:['e1'],citations:[{id:'c1',title:'SOLAS',location:{section:'II-2',page:'12',chunk:'7',uri:'https://imo.example/solas'},publishedAt:'2026-01-01',version:'2026',authority:'authoritative',verified:true,metadataComplete:true}]},answerRelease=releaseGate.release({sealInput,answerSeal,groundedAnswer},{answerSealer:sealer}),publicResponse=projector.project({answerRelease,groundedAnswer},{answerReleaseGate:releaseGate});return contract.result({status:'GROUNDED_PLAN_READY',transactionId:'tx-2n',publicResponse,groundedAnswer:{secret:'internal-grounded'},claimPlan:{secret:'internal-claim'},provenance:{secret:'internal-provenance'}});}
function authentic(base,overrides={}){return contract.result({status:overrides.status??base.status,transactionId:overrides.transactionId??base.transactionId,publicResponse:overrides.publicResponse??base.publicResponse,groundedAnswer:base.groundedAnswer,claimPlan:base.claimPlan,provenance:base.provenance});}
test('adapts only the verified public projection into an exact minimal delivery shape',()=>{const result=adapter.adapt(fixture());assert.equal(result.status,'DELIVERY_READY');assert.equal(result.answer,'Güvenlik şartı');assert.equal(result.sources[0].title,'SOLAS');assert.equal(result.contentType,'text/plain; charset=utf-8');assert.deepEqual(Object.keys(result).sort(),['answer','contentType','deliveryHash','reasonCode','renderingPolicy','responseHash','sources','status','transactionId','version'].sort());assert.deepEqual(Object.keys(result.sources[0]).sort(),['authority','id','location','metadataComplete','publishedAt','title','verified','version'].sort());assert.equal(JSON.stringify(result).includes('internal-'),false);assert.ok(/^[a-f0-9]{64}$/u.test(result.deliveryHash));assert.ok(Object.isFrozen(result.sources[0].location));});
test('wrong orchestrator status version transaction and policy fail closed',()=>{const base=fixture(),cases=[{...base,version:'sinbad-grounded-orchestrator/2L'},authentic(base,{status:'PIPELINE_ERROR'}),authentic(base,{transactionId:'other'}),{...base,security:{publicProjectionRequired:false}}];for(const value of cases){const result=adapter.adapt(value);assert.equal(result.status,'DELIVERY_BLOCKED');assert.equal(result.answer,null);assert.deepEqual(result.sources,[]);}});
test('tampered response hash answer citations and URI fail closed inside authentic results',()=>{const base=fixture(),p=base.publicResponse,c=p.citations[0],mutations=[{...p,responseHash:'b'.repeat(64)},{...p,answer:'changed'},{...p,citations:[c,c]},{...p,citations:[{...c,location:{...c.location,uri:'javascript:alert(1)'}}]},{...p,citations:[{...c,location:{...c.location,uri:'   '}}]}];for(const publicResponse of mutations)assert.equal(adapter.adapt(authentic(base,{publicResponse})).status,'DELIVERY_BLOCKED');});
test('copied serialized and fully rehashed forged orchestration results fail authenticity',()=>{const base=fixture(),serialized=JSON.parse(JSON.stringify(base)),body=adapter.responsePayload(serialized.publicResponse);serialized.publicResponse.responseHash=adapter.sha256(adapter.canonical(body));assert.equal(adapter.adapt({...base}).status,'DELIVERY_BLOCKED');assert.equal(adapter.adapt(serialized).status,'DELIVERY_BLOCKED');});
test('proxy wrapped authentic orchestration result fails object-identity authenticity',()=>{const base=fixture();assert.equal(contract.isAuthenticResult(base),true);assert.equal(contract.isAuthenticResult(new Proxy(base,{})),false);assert.equal(adapter.adapt(new Proxy(base,{})).status,'DELIVERY_BLOCKED');});
test('adapter invokes no model expert navigation or network',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{assert.equal(adapter.adapt(fixture()).status,'DELIVERY_READY');assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});
