'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const planner=require('../verification/claim-planner.js');const gate=require('../verification/query-coverage-gate.js');const grounding=require('../grounding/grounded-answer-pipeline.js');

test('coverage tokenization is deterministic, Unicode aware, and removes common Turkish glue words',()=>{assert.deepEqual(gate.tokens('Bu GÜVENLİK için güvenlik şartı nedir?'),['guvenlik','sartı']);assert.deepEqual(gate.tokens('alpha beta alpha'),['alpha','beta']);});

test('non-claim plans and empty concept queries fail closed',()=>{const plan=planner.unavailable({transactionId:'tx',queryHash:planner.queryHash('safety')}),first=gate.evaluate({transactionId:'tx',query:'safety',claimPlan:plan}),second=gate.evaluate({transactionId:'tx',query:'ve ile bir',claimPlan:plan});assert.equal(first.status,'COVERAGE_INSUFFICIENT');assert.equal(first.reasonCode,'INVALID_OR_UNBOUND_PLAN');assert.equal(second.status,'COVERAGE_INSUFFICIENT');assert.equal(gate.isAuthenticResult(first),true);assert.equal(gate.isAuthenticResult({...first}),false);});

test('coverage results cannot be replayed or copied across trust boundaries',()=>{const plan=planner.unavailable({transactionId:'tx',queryHash:planner.queryHash('safety')}),result=gate.evaluate({transactionId:'tx',query:'safety',claimPlan:plan});assert.equal(gate.isBoundSufficient(result,{transactionId:'other',query:'safety'}),false);assert.equal(gate.isBoundSufficient(result,{transactionId:'tx',query:'different'}),false);assert.equal(gate.isBoundSufficient({...result},{transactionId:'tx',query:'safety'}),false);});

test('coverage threshold is inclusive and deterministic at its exact boundary',()=>{assert.equal(gate.MIN_COVERAGE_RATIO,0.8);assert.equal(4/5>=gate.MIN_COVERAGE_RATIO,true);assert.equal(3/5>=gate.MIN_COVERAGE_RATIO,false);});

test('coverage evaluation invokes no model, expert, navigation, or network capability',()=>{let model=0,expert=0,navigation=0,network=0;const before=[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch];globalThis.SinbadModel={generate(){model++;}};globalThis.SinbadExpert={execute(){expert++;}};globalThis.SinbadNavigation={answer(){navigation++;}};globalThis.fetch=async()=>{network++;};try{const plan=planner.unavailable({transactionId:'tx',queryHash:planner.queryHash('safety')});gate.evaluate({transactionId:'tx',query:'safety',claimPlan:plan});assert.deepEqual({model,expert,navigation,network},{model:0,expert:0,navigation:0,network:0});}finally{[globalThis.SinbadModel,globalThis.SinbadExpert,globalThis.SinbadNavigation,globalThis.fetch]=before;}});

test('grounding rejects a forged sufficient coverage result for planned claims',()=>{const retrievalResult={status:'EVIDENCE_SUFFICIENT',evaluation:{selected:[],rejected:[]},rejected:[]},result=grounding.create().run({transactionId:'tx',retrievalResult,claims:[{claimId:'c',statement:'safety'}],claimPlan:{status:'CLAIMS_PLANNED'},planningQuery:'safety',claimCoverage:{status:'COVERAGE_SUFFICIENT'}});assert.equal(result.status,'INVALID_CLAIMS');assert.equal(result.answer,null);assert.equal(result.citations.length,0);});

test('an authentic but unbound coverage result cannot soften invalid planned input',()=>{const retrievalResult={status:'EVIDENCE_SUFFICIENT',evaluation:{selected:[],rejected:[]},rejected:[]},plan=planner.unavailable({transactionId:'other',queryHash:planner.queryHash('safety')}),coverage=gate.evaluate({transactionId:'other',query:'safety',claimPlan:plan}),result=grounding.create().run({transactionId:'tx',retrievalResult,claims:[{claimId:'c',statement:'safety'}],claimPlan:{status:'CLAIMS_PLANNED'},planningQuery:'safety',claimCoverage:coverage});assert.equal(result.status,'INVALID_CLAIMS');});
