'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const activation=require('../adapters/trusted-terminal-rollout-activation.js');
const actor='b'.repeat(64);let time=1000;
function rpc(){return async name=>name.startsWith('verify_')?{data:true,error:null}:{data:[],error:null};}
function create(overrides={}){return activation.create({serviceRole:true,actorHash:actor,client:{rpc:rpc()},limit:10,slaMs:120000,pageSize:10,maxEvents:100,ttlMs:5000,purpose:'terminal-rollout',now:()=>time,activationTimeoutMs:5000,activate:async()=>true,resolve:async()=>'PENDING',...overrides});}
test('requires trusted activation and exposes a frozen minimal API',()=>{assert.throws(()=>create({activate:null}),/trusted activate/u);assert.throws(()=>create({diagnose:'log'}),/diagnose/u);assert.throws(()=>create({activationTimeoutMs:999}),/timeout/u);const value=create({resolve:undefined});assert.deepEqual(Object.keys(value),['issue','activate','reconcile']);assert.ok(Object.isFrozen(value));assert.deepEqual(Object.keys(activation),['ACTIVATION_VERSION','EXPECTED_ATTESTATION_VERSION','EXPECTED_JOURNAL_VERSION','create']);});
test('activates exactly once only after consuming an authentic attestation',async()=>{time=1000;let calls=0,seen;const gate=create({activate:async value=>{calls++;seen=value;return true;}}),attested=await gate.issue(),applied=await gate.activate(attested);assert.equal(applied.status,'TRUSTED_ROLLOUT_ACTIVATION_APPLIED');assert.equal(calls,1);assert.deepEqual(seen,{attestationHash:attested.attestationHash});assert.ok(Object.isFrozen(seen));assert.equal((await gate.activate(attested)).status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');assert.equal(calls,1);});
test('copies proxies blocked readiness and expiry never invoke activation',async()=>{time=1000;let calls=0;const gate=create({activate:async()=>{calls++;return true;}}),value=await gate.issue();for(const candidate of [{...value},structuredClone(value),new Proxy(value,{})])assert.equal((await gate.activate(candidate)).status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');time=6000;assert.equal((await gate.activate(value)).status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');assert.equal(calls,0);});
test('false and non-boolean outcomes fail while exceptions are unsettled',async()=>{for(const [activate,status,reason] of [[async()=>false,'TRUSTED_ROLLOUT_ACTIVATION_FAILED','ACTIVATION_REJECTED'],[async()=>({ok:true}),'TRUSTED_ROLLOUT_ACTIVATION_FAILED','ACTIVATION_REJECTED'],[async()=>{throw new Error('secret');},'TRUSTED_ROLLOUT_ACTIVATION_UNSETTLED','ACTIVATION_OUTCOME_UNKNOWN']]){time=1000;const events=[],gate=create({activate,diagnose:event=>events.push(event)}),value=await gate.issue(),output=await gate.activate(value);assert.equal(output.status,status);assert.equal(output.reasonCode,reason);assert.equal((await gate.activate(value)).status,'TRUSTED_ROLLOUT_ACTIVATION_BLOCKED');assert.equal(JSON.stringify(events).includes('secret'),false);assert.ok(events.every(Object.isFrozen));}});
test('concurrent activation attempts invoke the side effect once',async()=>{time=1000;let release,calls=0;const wait=new Promise(resolve=>{release=resolve;}),gate=create({activate:async()=>{calls++;await wait;return true;}}),value=await gate.issue(),first=gate.activate(value),second=gate.activate(value);release();const results=await Promise.all([first,second]);assert.equal(calls,1);assert.deepEqual(results.map(x=>x.status).sort(),['TRUSTED_ROLLOUT_ACTIVATION_APPLIED','TRUSTED_ROLLOUT_ACTIVATION_BLOCKED']);});
