'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const attestation=require('../adapters/supabase-terminal-recovery-attestation.js');
const actor='b'.repeat(64);let time=1000;
function create(handler,overrides={}){return attestation.create({serviceRole:true,actorHash:actor,client:{rpc:handler},limit:10,slaMs:120000,pageSize:10,maxEvents:100,ttlMs:5000,purpose:'terminal-rollout',now:()=>time,...overrides});}
function healthy(){return async name=>name.startsWith('verify_')?{data:true,error:null}:{data:[],error:null};}
test('requires explicit bounded TTL clock purpose and trusted readiness policy',()=>{const base={serviceRole:true,actorHash:actor,client:{rpc:healthy()},limit:10,slaMs:120000,pageSize:10,maxEvents:100,ttlMs:5000,purpose:'terminal-rollout',now:()=>0};for(const value of [{ttlMs:999},{ttlMs:300001},{now:undefined},{purpose:''},{purpose:'bad purpose'}])assert.throws(()=>attestation.create({...base,...value}),/TTL|clock|purpose/u);assert.deepEqual(Object.keys(attestation),['ATTESTATION_VERSION','EXPECTED_READINESS_VERSION','create']);});
test('issues and consumes one authentic fresh content-free attestation',async()=>{time=1000;const gate=create(healthy()),value=await gate.issue();assert.equal(value.status,'READINESS_ATTESTED');assert.equal(value.issuedAt,1000);assert.equal(value.expiresAt,6000);assert.ok(/^[a-f0-9]{64}$/u.test(value.attestationHash));assert.equal('claims'in value,false);assert.equal('events'in value,false);const accepted=gate.consume(value);assert.equal(accepted.status,'READINESS_ATTESTATION_ACCEPTED');assert.equal(gate.consume(value).status,'READINESS_ATTESTATION_BLOCKED');assert.ok(Object.isFrozen(value));assert.ok(Object.isFrozen(gate));});
test('blocked readiness never receives an attestation',async()=>{time=1000;const gate=create(async name=>name==='verify_terminal_recovery_access'?{data:false,error:null}:{data:[],error:null}),value=await gate.issue();assert.equal(value.status,'READINESS_ATTESTATION_BLOCKED');assert.equal(value.attestationHash,null);assert.equal(gate.consume(value).status,'READINESS_ATTESTATION_BLOCKED');});
test('copies proxies other instances expiry and clock rollback fail closed',async()=>{time=1000;const first=create(healthy()),value=await first.issue(),second=create(healthy());for(const candidate of [{...value},structuredClone(value),new Proxy(value,{})])assert.equal(first.consume(candidate).status,'READINESS_ATTESTATION_BLOCKED');assert.equal(second.consume(value).status,'READINESS_ATTESTATION_BLOCKED');time=6000;assert.equal(first.consume(value).status,'READINESS_ATTESTATION_BLOCKED');time=999;const rollbackGate=create(healthy()),fresh=await rollbackGate.issue();time=998;assert.equal(rollbackGate.consume(fresh).status,'READINESS_ATTESTATION_BLOCKED');});
