const test=require('node:test');
const assert=require('node:assert/strict');
const fsp=require('node:fs').promises;
const os=require('node:os');
const path=require('node:path');
const compiler=require('../engines/studio/virtual-artifact-compiler.js'),staticVerifier=require('../engines/studio/static-artifact-verifier.js'),sandboxWriter=require('../engines/studio/sandbox-writer.js'),persistedVerifier=require('../engines/studio/persisted-workspace-verifier.js'),runnerModule=require('../engines/studio/docker-sandbox-test-runner.js'),writerModule=require('../engines/studio/docker-test-evidence-writer.js');
async function fixture(t){const base=await fsp.mkdtemp(path.join(os.tmpdir(),'sinbad-test-evidence-'));t.after(()=>fsp.rm(base,{recursive:true,force:true}));const bundle=compiler.compile({instruction:'Yazılım hazırla',projectName:'Evidence',audience:'owner',acceptanceCriteria:'tests'}),staticReport=staticVerifier.verify(bundle),source=sandboxWriter.create({approvedBase:base,clock:()=>1000});await source.persist(bundle,source.authorize(bundle,{approvedBy:'owner-001',purpose:'source-001',nonce:'source-001',expiresAt:2000}));const report=await persistedVerifier.create({approvedBase:base}).verify(staticReport),runner=runnerModule.create({approvedBase:base,clock:()=>1000,launch:async()=>({exitCode:0,timedOut:false,output:'pass 1'})}),result=await runner.run(report,runner.authorize(report,{approvedBy:'owner-001',purpose:'test-001',nonce:'test-001',expiresAt:2000}));return {base,result,writer:writerModule.create({approvedBase:base,clock:()=>1000})};}
const approval={approvedBy:'owner-001',purpose:'evidence-001',nonce:'evidence-001',expiresAt:2000};
test('atomically persists an authentic hash-bound test receipt without source writes',async t=>{const {base,result,writer}=await fixture(t),saved=await writer.persist(result,writer.authorize(result,approval)),payload=JSON.parse(await fsp.readFile(path.join(base,...saved.evidence.split('/'),'TEST_RESULT.json'),'utf8'));assert.equal(saved.status,'DOCKER_TEST_EVIDENCE_PERSISTED');assert.equal(saved.testStatus,'SANDBOX_TESTS_PASSED');assert.equal(payload.status,result.status);assert.equal(payload.outputSha256.length,64);assert.equal(payload.receiptHash,saved.receiptHash);assert.equal(saved.sourceModified,false);});
test('rejects forged results grants replay and overwrite',async t=>{const {result,writer}=await fixture(t);assert.throws(()=>writer.authorize({...result},approval),/authentic/);const auth=writer.authorize(result,approval);await assert.rejects(writer.persist(result,{...auth}),/NOT_AUTHORIZED/);await writer.persist(result,auth);await assert.rejects(writer.persist(result,auth),/NOT_AUTHORIZED/);const second=writer.authorize(result,{...approval,nonce:'evidence-002'});await assert.rejects(writer.persist(result,second),/ALREADY_EXISTS/);});
test('writer exposes no execution source mutation network or publish surface',()=>{const writer=writerModule.create();for(const field of ['run','execute','shell','command','overwrite','delete','writeSource','fetch','publish','deploy'])assert.equal(field in writer,false);});
