const test=require('node:test');
const assert=require('node:assert/strict');
const fsp=require('node:fs').promises;
const os=require('node:os');
const path=require('node:path');
const compiler=require('../engines/studio/virtual-artifact-compiler.js');
const staticVerifier=require('../engines/studio/static-artifact-verifier.js');
const sandboxWriter=require('../engines/studio/sandbox-writer.js');
const persistedVerifier=require('../engines/studio/persisted-workspace-verifier.js');
const sessionModule=require('../engines/studio/guided-docker-test-session.js');
async function fixture(t,launch=async()=>({exitCode:0,timedOut:false,output:'pass 1'})){const base=await fsp.mkdtemp(path.join(os.tmpdir(),'sinbad-guided-docker-'));t.after(()=>fsp.rm(base,{recursive:true,force:true}));const bundle=compiler.compile({instruction:'Yazılım hazırla',projectName:'Guided Docker',audience:'owner',acceptanceCriteria:'tests'}),staticReport=staticVerifier.verify(bundle),writer=sandboxWriter.create({approvedBase:base,clock:()=>1000});await writer.persist(bundle,writer.authorize(bundle,{approvedBy:'owner-001',purpose:'workspace-001',nonce:'workspace-001',expiresAt:2000}));const report=await persistedVerifier.create({approvedBase:base}).verify(staticReport);return {base,report,session:sessionModule.create({approvedBase:base,clock:()=>1000,launch})};}
const approval={approvedBy:'owner-001',purpose:'guided-test-001',nonce:'guided-test-001',expiresAt:2000};
test('shows policy then separately approves one run and verifies its receipt',async t=>{const {base,report,session}=await fixture(t),ready=session.prepare(report);assert.equal(ready.status,'DOCKER_TEST_APPROVAL_REQUIRED');assert.deepEqual(ready.tests,['software/tests/index.test.js']);assert.equal(ready.policy.network,'NONE');assert.equal(ready.policy.hostMount,'READ_ONLY');const result=await session.runVerifiedTests(approval);assert.equal(result.status,'SANDBOX_TESTS_PASSED');assert.equal(result.nextAction,'APPROVE_TEST_EVIDENCE_WRITE');assert.deepEqual(result.writes,{host:false,core:false,production:false});const saved=await session.persistEvidence({approvedBy:'owner-001',purpose:'evidence-001',nonce:'evidence-001',expiresAt:2000});assert.equal(saved.status,'DOCKER_TEST_EVIDENCE_VERIFIED');assert.equal(saved.nextAction,'REVIEW_VERIFIED_TEST_EVIDENCE');assert.equal(JSON.parse(await fsp.readFile(path.join(base,...saved.evidence.split('/'),'TEST_RESULT.json'),'utf8')).status,'SANDBOX_TESTS_PASSED');assert.equal((await session.runVerifiedTests(approval)).reason,'TEST_RUN_OUT_OF_ORDER');});
test('copied report invalid approval and nonzero test result fail closed',async t=>{const first=await fixture(t);assert.equal(first.session.prepare({...first.report}).reason,'AUTHENTIC_PERSISTED_REPORT_REQUIRED');assert.equal((await first.session.runVerifiedTests(approval)).reason,'TEST_RUN_OUT_OF_ORDER');const second=await fixture(t);second.session.prepare(second.report);assert.match((await second.session.runVerifiedTests({...approval,approvedBy:''})).reason,/approval identity/u);const third=await fixture(t,async()=>({exitCode:1,timedOut:false,output:'failed'}));third.session.prepare(third.report);const failed=await third.session.runVerifiedTests({...approval,nonce:'guided-test-002'});assert.equal(failed.status,'SANDBOX_TESTS_FAILED');assert.equal(failed.nextAction,'APPROVE_TEST_EVIDENCE_WRITE');});
test('session exposes no generic command shell source write merge or publish surface',()=>{const session=sessionModule.create({launch:async()=>({exitCode:1})});for(const field of ['run','execute','shell','command','write','writeCore','merge','fetch','publish','deploy'])assert.equal(field in session,false);assert.deepEqual(session.status().capabilities,{inspectVerifiedTests:true,verifiedSoftwareTestExecution:true,persistTestEvidence:true,generalCommandExecution:false,shell:false,network:false,hostWrite:false,coreWrite:false,merge:false,publish:false});});
