const test=require('node:test');
const assert=require('node:assert/strict');
const fsp=require('node:fs').promises;
const os=require('node:os');
const path=require('node:path');
const compiler=require('../engines/studio/virtual-artifact-compiler.js'),staticVerifier=require('../engines/studio/static-artifact-verifier.js'),sandboxWriter=require('../engines/studio/sandbox-writer.js'),persistedVerifier=require('../engines/studio/persisted-workspace-verifier.js'),runnerModule=require('../engines/studio/docker-sandbox-test-runner.js'),writerModule=require('../engines/studio/docker-test-evidence-writer.js'),verifierModule=require('../engines/studio/docker-test-evidence-verifier.js');
async function fixture(t){const base=await fsp.mkdtemp(path.join(os.tmpdir(),'sinbad-evidence-verify-'));t.after(()=>fsp.rm(base,{recursive:true,force:true}));const bundle=compiler.compile({instruction:'Yazılım hazırla',projectName:'Verify Evidence',audience:'owner',acceptanceCriteria:'tests'}),staticReport=staticVerifier.verify(bundle),source=sandboxWriter.create({approvedBase:base,clock:()=>1000});await source.persist(bundle,source.authorize(bundle,{approvedBy:'owner-001',purpose:'source-001',nonce:'source-001',expiresAt:2000}));const report=await persistedVerifier.create({approvedBase:base}).verify(staticReport),runner=runnerModule.create({approvedBase:base,clock:()=>1000,launch:async()=>({exitCode:0,timedOut:false,output:'pass 1'})}),result=await runner.run(report,runner.authorize(report,{approvedBy:'owner-001',purpose:'test-001',nonce:'test-001',expiresAt:2000})),writer=writerModule.create({approvedBase:base,clock:()=>1000}),receipt=await writer.persist(result,writer.authorize(result,{approvedBy:'owner-001',purpose:'evidence-001',nonce:'evidence-001',expiresAt:2000}));return {base,receipt,verifier:verifierModule.create({approvedBase:base}),file:path.join(base,...receipt.evidence.split('/'),'TEST_RESULT.json')};}
test('independently verifies the exact persisted receipt and hashes',async t=>{const {receipt,verifier}=await fixture(t),verified=await verifier.verify(receipt);assert.equal(verified.status,'DOCKER_TEST_EVIDENCE_VERIFIED');assert.equal(verified.receiptHash,receipt.receiptHash);assert.equal(verified.testStatus,'SANDBOX_TESTS_PASSED');assert.equal(verified.filesystemWrite,false);});
test('copied receipt and output or receipt tampering fail closed',async t=>{const first=await fixture(t);assert.equal((await first.verifier.verify({...first.receipt})).reason,'AUTHENTIC_EVIDENCE_RECEIPT_REQUIRED');const payload=JSON.parse(await fsp.readFile(first.file,'utf8'));payload.output='tamper';await fsp.writeFile(first.file,JSON.stringify(payload,null,2)+'\n');assert.equal((await first.verifier.verify(first.receipt)).reason,'EVIDENCE_OUTPUT_HASH_MISMATCH');const second=await fixture(t);const payload2=JSON.parse(await fsp.readFile(second.file,'utf8'));payload2.approvedBy='attacker';await fsp.writeFile(second.file,JSON.stringify(payload2,null,2)+'\n');assert.equal((await second.verifier.verify(second.receipt)).reason,'EVIDENCE_RECEIPT_HASH_MISMATCH');});
test('extra files and missing evidence fail closed without execution surface',async t=>{const {base,receipt,verifier}=await fixture(t),target=path.join(base,...receipt.evidence.split('/'));await fsp.writeFile(path.join(target,'extra'),'x');assert.equal((await verifier.verify(receipt)).reason,'EVIDENCE_FILESET_INVALID');await fsp.rm(path.join(target,'extra'));await fsp.rm(path.join(target,'TEST_RESULT.json'));assert.equal((await verifier.verify(receipt)).reason,'EVIDENCE_FILESET_INVALID');for(const field of ['run','execute','write','fetch','publish','deploy'])assert.equal(field in verifier,false);});
