const test=require('node:test');
const assert=require('node:assert/strict');
const fsp=require('node:fs').promises;
const os=require('node:os');
const path=require('node:path');
const sessionModule=require('../engines/studio/guided-pro-model-session.js');
const modelApproval={approvedBy:'owner-001',purpose:'model-call-001',nonce:'model-nonce-001',expiresAt:2000,timeoutMs:500},writeApproval={approvedBy:'owner-001',purpose:'proposal-write-001',nonce:'write-nonce-001',expiresAt:2000},previewApproval={approvedBy:'owner-001',purpose:'preview-write-001',nonce:'preview-nonce-001',expiresAt:2000};
const proposal=JSON.stringify({version:1,projectSlug:'guided-pro',artifacts:[{path:'web/index.html',mediaType:'text/html; charset=utf-8',content:'<!doctype html><html><head></head><body>Pro</body></html>'}]}),input={endpoint:'http://127.0.0.1:11434/api/generate',model:'local-coder',instruction:'JSON web önerisi oluştur',context:'offline Studio Pro'};
async function fixture(t,response=proposal){const base=await fsp.mkdtemp(path.join(os.tmpdir(),'sinbad-guided-pro-'));t.after(()=>fsp.rm(base,{recursive:true,force:true}));return {base,session:sessionModule.create({approvedBase:base,clock:()=>1000,transport:async()=>({statusCode:200,body:JSON.stringify({response})})})};}
test('guides an authorized local model proposal into isolated persistence and scriptless preview',async t=>{const {base,session}=await fixture(t);assert.equal(session.prepare(input).status,'PRO_MODEL_CALL_READY');assert.equal((await session.generate(modelApproval)).status,'PRO_MODEL_PROPOSAL_READY');const persisted=await session.persist(writeApproval);assert.equal(persisted.status,'PRO_MODEL_PROPOSAL_PERSISTED_UNTRUSTED');assert.equal(persisted.nextAction,'APPROVE_SCRIPTLESS_MODEL_PREVIEW_WRITE');assert.equal(await fsp.stat(path.join(base,...persisted.proposal.split('/'),'web','index.html')).then(item=>item.isFile()),true);const preview=await session.createPreview(previewApproval);assert.equal(preview.status,'PRO_MODEL_SCRIPTLESS_PREVIEW_READY');assert.deepEqual({executed:preview.executed,opened:preview.opened,published:preview.published},{executed:false,opened:false,published:false});const html=await fsp.readFile(path.join(base,...preview.preview.split('/'),'web','index.html'),'utf8');assert.match(html,/Content-Security-Policy/u);assert.doesNotMatch(html,/<script\b/iu);});
test('guides invalid input model output and approval failures without writing',async t=>{const first=await fixture(t);assert.equal(first.session.prepare({...input,endpoint:'https://example.com/model'}).nextAction,'REVISE_LOCAL_MODEL_INPUT');const second=await fixture(t,'not-json');second.session.prepare(input);assert.equal((await second.session.generate(modelApproval)).nextAction,'REVISE_MODEL_PROMPT_OR_OUTPUT');const third=await fixture(t);third.session.prepare(input);assert.equal((await third.session.generate({...modelApproval,approvedBy:''})).nextAction,'REVIEW_MODEL_CALL_APPROVAL_OR_LOCAL_RUNTIME');await assert.rejects(fsp.stat(path.join(third.base,'studio-proposals')),error=>error.code==='ENOENT');});
test('rejects out-of-order repeated calls and keeps independent approval gates',async t=>{const {session}=await fixture(t);assert.equal((await session.generate(modelApproval)).reason,'MODEL_CALL_OUT_OF_ORDER');assert.equal((await session.persist(writeApproval)).reason,'PROPOSAL_WRITE_OUT_OF_ORDER');assert.equal((await session.createPreview(previewApproval)).reason,'MODEL_PREVIEW_OUT_OF_ORDER');assert.equal(session.prepare(input).status,'PRO_MODEL_CALL_READY');assert.equal(session.prepare(input).reason,'SESSION_ALREADY_PREPARED');assert.equal((await session.generate(modelApproval)).status,'PRO_MODEL_PROPOSAL_READY');assert.equal((await session.generate(modelApproval)).reason,'MODEL_CALL_OUT_OF_ORDER');assert.equal((await session.persist(writeApproval)).status,'PRO_MODEL_PROPOSAL_PERSISTED_UNTRUSTED');assert.equal((await session.persist(writeApproval)).reason,'PROPOSAL_WRITE_OUT_OF_ORDER');assert.equal((await session.createPreview(previewApproval)).status,'PRO_MODEL_SCRIPTLESS_PREVIEW_READY');assert.equal((await session.createPreview(previewApproval)).reason,'MODEL_PREVIEW_OUT_OF_ORDER');});
test('Pro session exposes no generated-code runner Core writer remote client or publisher',()=>{const session=sessionModule.create({transport:async()=>({statusCode:500,body:'{}'})});for(const field of ['run','execute','testCode','writeCore','fetchRemote','connectRemote','publish','deploy','overwrite'])assert.equal(field in session,false);assert.deepEqual(session.status().capabilities,{loopbackModelDraft:true,validateArtifactProposal:true,persistIsolatedProposal:true,createScriptlessPreview:true,generatedCodeExecution:false,coreWrite:false,remoteNetwork:false,publish:false});});
test('always binds the exact artifact schema and JSON controls into the local prompt',async t=>{let body;const {base}=await fixture(t),session=sessionModule.create({approvedBase:base,clock:()=>1000,transport:async request=>{body=JSON.parse(request.body);return {statusCode:200,body:JSON.stringify({response:proposal})};}});session.prepare(input);await session.generate(modelApproval);assert.equal(body.format,'json');assert.equal(body.think,false);assert.match(body.prompt,/Every path must start with web\//u);assert.match(body.prompt,/Do not use Markdown fences/u);});
test('binds every canonical extension to its exact case-sensitive media type',()=>{
  for(const [extension,mediaType] of Object.entries(require('../engines/studio/static-artifact-verifier.js').TYPE_BY_EXTENSION))assert.match(sessionModule.MEDIA_TYPE_INSTRUCTION,new RegExp(`${extension.replace('.','\\.')}=${mediaType.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`,'u'));
  assert.match(sessionModule.ARTIFACT_SCHEMA_INSTRUCTION,/case-sensitive and exact/u);
});
